### ISSUE TITLE
RFID Reader

### ISSUE THREAD

**Issue by deathly87** [MiczFlor/RPi-Jukebox-RFID#10]
Komme leider bei der Einrichtung nicht weiter:
Habe als RFID Reader einen RC522 und diesen per GPIO angeschlossen.
Mit folgender Anleitung: https://tutorials-raspberrypi.de/raspberry-pi-rfid-rc522-tueroeffner-nfc/ 
bekomme ich ihn einzeln ohne Probleme zu laufen.

Mein eigentliches Problem ist, dass ich leider nicht weiß, wie ich diesen hier genau integrieren soll.
Da ich kein USB-Reader habe bin ich mit "python2 RegisterDevice.py" leider total aufgeschmissen und weiß mir ehrlich gesagt auch nicht zu helfen.

Gruß
André

**Comment by MiczFlor** [comment]
Hallo André,

Eine ähnliche Frage hatte ich in Englisch schon mal beantwortet: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/9

Kurzum: deine Analyse ist korrekt, wenn es sich um einen RFID Reader handelt, der nicht per USB Device angeschlossen ist, funktioniert diese Lösung nicht. Vielleicht findest du was anderes unter den Projekten, die im Readme File unter Acknowledgements verlinkt sind? 
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/README.md#acknowledgments

Viel Spaß mit deinem Projekt,

micz
