### ISSUE TITLE
🐛 | Web UI error - shuffles everytime a song is directly selected from playlist

### ISSUE THREAD

**Issue by princemaxwell** [MiczFlor/RPi-Jukebox-RFID#1027]
### What I did

I started playing a playlist, where shuffle is activated. Then i opened the playlist in the web player. When direct selecting a song then, not the selected song is starting. It will be played a random song from the playlist.

### Further information that might help

Everytime i select a song from playlist (only playlists which have shuffle activated), the playerplay routine (**playout_controls.sh**) is called, and within that another script is called:

```
        # Change some settings according to current folder IF the folder.conf exists
        . ${PATHDATA}/inc.settingsFolderSpecific.sh
```

I don't know why, but **inc.settingsFolderSpecific.sh** is calling:

```
        if [ $SHUFFLE == "ON" ]
        then 
		    if [ "${DEBUG_inc_settingsFolderSpecific_sh}" == "TRUE" ]; then echo "  # # CHANGING: mpc shuffle" >> $PATHDATA/../logs/debug.log; fi
            **mpc shuffle**
        else

```

Because of that, the playlist will be shuffled again, BEFORE the selected song is starting. The problem is then, that the selected song now has another playlist position.

I have now commented out **mpc shuffle** in line 53 of **inc.settingsFolderSpecific.sh**.
Now the song selection ist working fine.

Can someone explain, whats the reason of shuffeling in **inc.settingsFolderSpecific.sh**???
**_Isn't it done by shuffle_play.sh???_**

If there is no disadvantage of doing that, i could pull request the fix.

### Base image and version

Raspbian GNU/Linux 10 (buster)

### Branch / Release

master

### RaspberryPi version

Raspberry Pi 3 Model B Rev 1.2

### RFID Reader

13ba:0018 PCPlay Barcode PCP-BCG4209

### Soundcard

08bb:2902 Texas Instruments PCM2902 Audio Codec

**Comment by s-martin** [comment]
We fixed many shuffle issues in 2.2. 
I’m closing this now, feel free to reopen the issue or open a new issue, if this still persists in 2.2
