### ISSUE TITLE
🐛 | mpd / seekcur -15 is not working

### ISSUE THREAD

**Issue by PsychoD** [MiczFlor/RPi-Jukebox-RFID#1031]
### What I did
I used the latest buster one line install script to update my installation from october 2019 (where this bug already was present) . Then I checked gpio button configuration: 

def def_next():
    check_call("./scripts/playout_controls.sh -c=playerseek -v=+15", shell=True)

def def_prev():
    check_call("./scripts/playout_controls.sh -c=playerseek -v=-15", shell=True)

### What happened
The next button works as expected, the prev button does not. You can hear a little skip, but no jumping back in the track. 

### I expected this to happen

Pressing prev jumps -15 sec in the current track

### Further information that might help

I debugged this down to mpd: 
`echo seekcur 15 | nc -w 1 localhost 6600`
`echo status | nc -w 1 localhost 6600 | grep -o -P '(?<=elapsed: ).*'`
`echo seekcur +15 | nc -w 1 localhost 6600`
`echo status | nc -w 1 localhost 6600 | grep -o -P '(?<=elapsed: ).*'`
`echo seekcur -15 | nc -w 1 localhost 6600`
`echo status | nc -w 1 localhost 6600 | grep -o -P '(?<=elapsed: ).*'`

results in: 
```
OK MPD 0.21.4
OK
16.782
OK MPD 0.21.4
OK
34.570
OK MPD 0.21.4
OK
37.358
```

Also, I wonder why it says version 0.21.4, while it should say 0.21.5, right? 

```
pi@phoniebox:~ $ which mpd
/usr/bin/mpd
pi@phoniebox:~ $ mpd --version
Music Player Daemon 0.21.5 (0.21.5)
```

### Base image and version
```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Branch / Release

master

### RaspberryPi version

Raspberry Pi 2 Model B Rev 1.1

### Soundcard
Hifiberry MiniAmp

**Comment by pinguin42** [comment]
I have the same problem here. My phoniebox doesn't rewind either.

**Comment by PsychoD** [comment]
Does anyone know where I can specify / look up which MPD the phoniebox uses? It seems my system wide installed version is not used.

**Comment by s-martin** [comment]
> Does anyone know where I can specify / look up which MPD the phoniebox uses? It seems my system wide installed version is not used.

You could search for multiple `mpd` binaries...

**Comment by s-martin** [comment]
Please check https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/878#issuecomment-672283454

**Comment by MiczFlor** [comment]
Hi @PsychoD 
I added your fix to the develop branch. You can see it here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/d6408b4d574a1f0f216c4fd5f6d283ce57569800
Could you check if it works? I am only on my laptop. Reading this thread, I thought: why not just seek to the absolute position if the *minus* creates... and before I could finish that thought: here you posted it :) Thanks
If it works, please close the ticket.

**Comment by PsychoD** [comment]
Hi, thanks for including the fix! 
I currently have some issues updating my version so I can't test the development branch quickly, but will as soon as I manage to get the update running. From the code it looks exactly like my playout-controls (I only am lacking the whole "VOLFILE" part, but I guess that has nothing to do with the fix). Also I used awk, and am not 100% sure if this dependency is already met by any raspberry pi os.
