### ISSUE TITLE
Asterisk Support to stop playback on incoming Phone call

### ISSUE THREAD

**Issue by Luegengladiator** [MiczFlor/RPi-Jukebox-RFID#104]
While I'm testing the Phonie (mpd version) now, it's running 6-10h a day. 
Once in a while the phone rings and i have to stop the phonie to answer the phone. 

I'm looking for a solution to stop the phonie on incoming calls. Asterisk seems to be the tool of choice.
Playing around with this thought it would be nice to pause the phonie and shout the number calling or the reference in the Phone-book.

I know this is only a nice feature far away from normal use cases. But with mpd as a backend, the phonie is no longer a kids-player its now a full blown rfid/ean Mediacenter.

**Comment by Raspfarbend** [comment]
Hi @Luegengladiator ,
in my opinion, this is a feature from far far away.´;)
I'm also testing this branch, good work for now.
Currently i'm looking for a no iron soldering solution for "Stop on removal"
and a real-time-clock support for features like 'lullaby (fade-out/max volume at a specific time)'

The Phoniebox should focus it on kids usecases.

**Comment by MiczFlor** [comment]
Hi @Luegengladiator @Raspfarbend 
soon Phoniebox will control smart homes :) 
I like to keep an open mind when it comes to innovation - so let‘s see what comes of this issue. 
When I am done with the RFID triggered „makeCoffeeNow“ for my Phoniebox, I‘ll spend more time on this issue ;)

**Comment by Luegengladiator** [comment]
Oh nice idea. Coffee Controf is no big deal. All you have to use is a RFC 2324 and RFC 7168 Coffeepot, use the api and here you are ;)

**Comment by Luegengladiator** [comment]
Finally I got it working. But the way is to complex to get it running in this context.
