### ISSUE TITLE
I2C for LCD not working after phoniebox script installer runs and reboot

### ISSUE THREAD

**Issue by DSteg** [MiczFlor/RPi-Jukebox-RFID#1081]
## System
Rasberry Pi 3A+
Raspbian Buster Lite

## Bug
I2C for LCD not working after phoniebox script installer and reboot

### What I did
On a fresh rasbian buster the i2c can be enabled and the display is detected by 'sudo i2cdetect -y 1' with ID 27
After reboot, display still found with 'sudo i2cdetect -y 1'
I can write text on the display with python code too.

No I am installing phoniebox with the script installer
After script is finished, I reboot the system.

### What happened
After system is rebooted, 'sudo i2cdetect -y 1' can't detect the display again.  'sudo i2cdetect -y 1' runs slow

If I disable and enable I2C again, 'sudo i2cdetect -y 1' can detect the display again.

I tried this many times, always the same problem occures.

Can someone else confirm this bug?

Thank you and regards
Dominik

And sorry for the bad english. :-)

**Comment by s-martin** [comment]
Duplicate of #1080
