### ISSUE TITLE
🐛 | Status LED no longer working in 2.1.1 (likely also 2.1)

### ISSUE THREAD

**Issue by olli83** [MiczFlor/RPi-Jukebox-RFID#1094]
## Bug
Status LED not working

### What I did
Upgraded to 2.1.1
Status LED connected to GPIO12, was working before.

### I expected this to happen

Expected the status LED to continue function.

### Further information that might help

Status LED is not listed in the new GPIO settings file. It appears an entry is missing.

**Comment by s-martin** [comment]
There is documentation missing.

Could you please try to add

```
[StatusLED] 
enable: True 
Type: MPDStatusLED 
Pin: 12
```

to the GPIO settings file?

See also #900

**Comment by s-martin** [comment]
See also https://www.github.com/MiczFlor/RPi-Jukebox-RFID/tree/develop/components%2Fgpio_control%2Fexample_configs%2Fgpio_settings_rotary_and_led.ini

**Comment by olli83** [comment]
Nope, not working. Also tried "enabled" instead of "enable", I am confused as you link above use enable several times, whereas in the previous version it was always "enabled".
Also, would it not need a pull_up: true or similar? Tried that, but did not change anything.

**Comment by s-martin** [comment]
Did you restart the service?

**Comment by s-martin** [comment]
Please see #1096, the paths for `gpio_settings.ini` were mixed up. This is now fixed in `develop` branch.

Please give some info, if these changes fix this issue.

**Comment by s-martin** [comment]
I added some updates to the wiki
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Using-GPIO-hardware-buttons

**Comment by topas-rec** [comment]
(Accidently saw this issue - haven't updated my box for longer)
I have made some documentation at https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Using-GPIO-hardware-status-led about the status led. Perhaps that helps or has to be updated to recent or upcoming changes.

**Comment by s-martin** [comment]
> (Accidently saw this issue - haven't updated my box for longer)
> I have made some documentation at https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Using-GPIO-hardware-status-led about the status led. Perhaps that helps or has to be updated to recent or upcoming changes.

I’ve added that article to the navigation bar, so people will find it 😁

**Comment by olli83** [comment]
Solved by #1096 and with the above comments. Thanks!

**Comment by topas-rec** [comment]
Thanks @s-martin, but that entry was already there and is now doubled. :smiley: 
![Screenshot from 2020-11-23 17-02-01](https://user-images.githubusercontent.com/20391449/99985019-12543500-2dae-11eb-9439-04eeebb8d7d5.png)
I thinks yours is more intuitive to find and I'll remove my entry in the navigation bar.

**Comment by s-martin** [comment]
:D sorry, didn't see that.
________________________________

**Comment by s-martin** [comment]
Sorry, didn't see that.
