### ISSUE TITLE
Volume Change % does not work properly

### ISSUE THREAD

**Issue by harleking** [MiczFlor/RPi-Jukebox-RFID#1099]
## Bug
Volume Change % does not work properly
### What I did
Did a clean install with 2020-05-27-raspios-buster-lite-armhf. Using non standard GPIO Pins for Buttons as some std pins are used by RC522 and DAC

### What happened

Selected volume manager: amixer or mpd
Selected Vol. Change % 1%
Using GPIO-Button for Volume UP jumps from 1% to 28%
Using GPIO-Button for Volume Down jumps from 28% to 6%

Selected volume manager: amixer or mpd
Selected Vol. Change % 2%
Using GPIO-Button for Volume UP jumps from 1% to 55%
Using GPIO-Button for Volume Down jumps from 55% to 10%

Selected volume manager: amixer or mpd
Selected Vol. Change % 3%
Using GPIO-Button for Volume UP jumps from 1% to 82%
Using GPIO-Button for Volume Down jumps from 82% to 16%

### Got no Problem with this version:
2.0 - ed888da - master 
Volume set 3% does 4% jumps up/down

### I expected this to happen
Using Vol UP/DOWN increase Volume by given Selected Vol. Change %

### Further information that might help

Noticed during install (might be useless):
numid=1,iface=MIXER,name='Master'
  ; type=INTEGER,access=rw---RW-,values=2,min=0,max=255,step=0
  : values=255,255
  | dBscale-min=-51.00dB,step=0.20dB,mute=0

output of 'tail -n 500 /var/log/syslog'
https://pastebin.com/YdUAasue

### Classic edition (barebones)

2020-05-27-raspios-buster-lite-armhf.zip

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Branch / Release

i.e. `master`

the following command will help with that
`cd /home/pi/RPi-Jukebox-RFID/ && git status | head -2`

### Installscript
i.e. `scripts/installscripts/buster-install-default.sh`

### RFID Reader
RC522 works

### Soundcard
I2S PCM5102 DAC Decoder
Followed theese steps for installation: https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/External-Non-USB-Audio-DAC-ES9023

### GPIO Settings

```
GPIO Buttons:
PinUp: 27
PinDown: 22
PREV Pin1: 4
NEXT Pin2: 17
Play Pause Pin: 23
All other functions set to False

Tried [VolumeUp] and [VolumeDown] instead of [VolumeControl] GPIO settings, same result.

```
-->

**Comment by s-martin** [comment]
Please check #1091, looks like it's a similar issue.

**Comment by harleking** [comment]
Thank you.
