### ISSUE TITLE
PR80: resume lastplayed not working with folders witch contains whitespace

### ISSUE THREAD

**Issue by Raspfarbend** [MiczFlor/RPi-Jukebox-RFID#110]
resume lastplayed not working with folders witch contains whitespace.

if folder is triggered it starts everytime from begining

branch: pr80-mpd-as-audio-player

**Comment by MiczFlor** [comment]
Hi @Raspfarbend 
Good catch. I will temodel the lastplayed.dat fole into shell vars. that should fox it

**Comment by MiczFlor** [comment]
Thanks @zxa :)
