### ISSUE TITLE
Fast forward and rewind

### ISSUE THREAD

**Issue by harryliebteuch** [MiczFlor/RPi-Jukebox-RFID#113]
it would be great if you can use buttons, RFID cards and the web interface to fast forward and rewind

**Comment by MiczFlor** [comment]
Hi @harryliebteuch 
I added seek ahead and seek back arrows in the web app. You can see them in the player at the left and right (following the way my podcast app does it). Works for me, please have a look.
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/edb34f0b48c57a8bc3d98308645da3f816dde42b
All the best, micz
