### ISSUE TITLE
🚀 | FMention, that "pin" in gpio_settings.ini means number of GPIO (not PIN-Number)

### ISSUE THREAD

**Issue by RiekeIcke** [MiczFlor/RPi-Jukebox-RFID#1137]
### What functionality would you like to see in your phoniebox?

When I configured the gpio_settings.ini I first was not able to get the buttons working because I was confused to write GPIO numbers after "pin:"

### How do you envision the feature to work from a users perspective?

When I configure the gpio_settings I want to be sure which number I need to write after "pin:". It should be clarified in the file itself and the wiki that a GPIO-Number and not PIN-Number is expected. This might help to find other issues, in the case that the configuration does not work. 

### Further information that might help

Thank you for your work and all the new features! This is my 4th Phoniebox, the first one works for about 2 years now :-).

**Comment by s-martin** [comment]
I fixed this in https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/components/gpio_control/README.md
