### ISSUE TITLE
How to switch on and off your powerbank powerd Phoniebox?

### ISSUE THREAD

**Issue by MrReSc** [MiczFlor/RPi-Jukebox-RFID#1180]
I have just ordered all the missing material to build a Phoniebox.
Among other things a powerbank with two USB-A outputs and a Micro USB for charging as well as the USB speakers that are recommended.

I still wonder how you solved the switching on and off. With a GPIO button the box can be shut down. How do I turn the box back on? I wanted to connect the loudspeakers directly to the powerbank, because the RPi can't supply that much power. This means that the loudspeakers always draw a small current.

How did you solve this with your powerbank powerd Phoniebox?

**Comment by domu83** [comment]
Hi @MrReSc
I use this one: https://shop.pimoroni.com/products/onoff-shim but connect the speakers to the Pi.
Good read recommondation is this @splitti's blog here: https://splittscheid.de/selfmade-phoniebox/

Cheers

**Comment by s-martin** [comment]
> Hi @MrReSc
> I use this one: https://shop.pimoroni.com/products/onoff-shim but connect the speakers to the Pi.
> Good read recommondation is this @splitti's blog here: https://splittscheid.de/selfmade-phoniebox/
> 
> Cheers

Yes, I can recommend that, too.

**Comment by MrReSc** [comment]
The OnOff SHIM works perfectly with my Powerbank. Thanks.

**Comment by Sheepiely** [comment]
@MrReSc which power bank do you use?

**Comment by MrReSc** [comment]
> @MrReSc which power bank do you use?

BOM: https://github.com/MrReSc/PhonieboxSetup

**Comment by Sheepiely** [comment]
@MrReSc  Thanks for the speedy response. The onoff shim can't turn the pi zero back on when my Mi power bank 3 goes into deep sleep. I'm going to order the Adata powerbank now.
