### ISSUE TITLE
Music playback is interrupted for a few seconds every 20-30 seconds

### ISSUE THREAD

**Issue by SchreibAl** [MiczFlor/RPi-Jukebox-RFID#1199]
Music playback is interrupted for a few seconds every 20-30 seconds. However, I have not changed the system since the last time I used it. I have also checked all the sound settings that I know of. Seems like it could be buffer problem. Can anyone help or give tips? 

Thanks in advance

**Comment by s-martin** [comment]
Do you use classic or Spotify edition?

Are you playing local files or streams?

**Comment by SchreibAl** [comment]
Thank you for your quick response.
-> I'm using the Spotify Edition playing streams.

**Comment by s-martin** [comment]
Could you post results of `journalctl -u mopidy`?

Are you experiencing any issues, if you play spotify with another player from your network?

**Comment by SchreibAl** [comment]
Oh no, just found the problem... my smartphone had connected to the bluetooth speaker I use for the phoniebox and kept getting in the way. Stupid mistake... but might help someone else....
Thank you anyway for your quick responses to my issue.
