### ISSUE TITLE
Subfolder

### ISSUE THREAD

**Issue by thisisstevi** [MiczFlor/RPi-Jukebox-RFID#12]
Hi,

first of all, I want to compliment your work on this project.

Everything works fine for me, but i've got a question.

Is it possible to link the RFID-Card to a subfolder?

For example:

Card Nr. 1 plays the files in folder /audiofolders/folder1/folder2

Thanks for all
Steffen

**Comment by MiczFlor** [comment]
Hi Steffen, 
the way the script is set up, this is not possible at the moment. It might work to add a relative path in the shortcut files. However, the master shell script creates a list of files from the main folder (in your example 'folder1'). And what it does not find in there, it does not play. So, in short, there is no quick fix or workaround.
All the best, micz
