### ISSUE TITLE
Support for radio remote control

### ISSUE THREAD

**Issue by Franzformator** [MiczFlor/RPi-Jukebox-RFID#121]
Hi,

I would like to have support for a remote control (i. e. https://www.amazon.com/Andoer-Wireless-Controller-TV-Dongle-Projector/dp/B015SO37SY).

That would make the jukebox more smartphone independent. It also would rise the user friendliness for non-technically skilled people (such as grandparents).

I think for the media commands (Volume, Play, Pause,…) most things OS based. Additional nice functions could come with a mapping of Keycodes to special Jukebox functions. For example, a key on the remote could be used to start a lullaby timer.

**Comment by ekorn** [comment]
While I was looking for parts for my Phoniebox I stumbled upon the the Logitech Z5 speaker. It has a remote control and probably will be recognized as USB-Keyboard and USB-Soundcard. You can get it second hands nowadays. It should work like the [Logitech  V20](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/MANUAL.md#using-logitech-v20-speaker)
