### ISSUE TITLE
🚀 | Make audio configuration more „bullet proof“

### ISSUE THREAD

**Issue by s-martin** [MiczFlor/RPi-Jukebox-RFID#1224]
### What functionality would you like to see in your phoniebox?

Configuration of audio during installation should be improved, e.g.

- automatically configure sound cards (#1112 already improves installation for some sound cards)
- Consider RPi audio changes from [here](https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Troubleshooting-FAQ#raspberry-pi-update-may-2020-broke-my-audio) and https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1208
- Improve wiki section https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Troubleshooting-FAQ#audio-is-not-working
- consider behavior, when hdmi cable is connected or not, see https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1202#issuecomment-749158614
- Use multiple ifaces (outputs) #1213 

### How do you envision the feature to work from a users perspective?

Installation easier for users 

### Further information that might help

Users have to ask lots of questions(e.g. #1220), because it’s difficult and the current state is not very well documented.

**Comment by Andreas-Roth-27** [comment]
Is there a short cut to circumference difficult installation for the time being?

**Comment by s-martin** [comment]
New future3 implementation already addresses this.
