### ISSUE TITLE
🚀 | Rework SPOTIFY_INTEGRATION.md

### ISSUE THREAD

**Issue by s-martin** [MiczFlor/RPi-Jukebox-RFID#1238]
[SPOTIFY-INTEGRATION.md](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/docs/SPOTIFY-INTEGRATION.md) is still the only document describing how to use the Spotify edition.

however, most of the content is outdated, because it describes how to manually extend the Classic edition to Spotify.

should be reworked to the current state of implementation or merged with https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Spotify-FAQ

**Comment by s-martin** [comment]
See also #1252

**Comment by Groovylein** [comment]
Since there is only one script for both installation paths, I would merge it with the Spotify-FAQ and delete this readme

**Comment by Groovylein** [comment]
Looks like the information after the section **MUST READ** is not necessary. Therefore I would just erase [SPOTIFY-INTEGRATION.md](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/docs/SPOTIFY-INTEGRATION.md)

**Comment by pabera** [comment]
I might have addressed this issue a little with [this change](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1297). But I agree, it could use a little more care.

**Comment by Groovylein** [comment]
Now this can be closed @s-martin :)
