### ISSUE TITLE
unneeded additional output on mpc call

### ISSUE THREAD

**Issue by Luegengladiator** [MiczFlor/RPi-Jukebox-RFID#124]
calling playoutcontrols and rfid_trigger_play ends up in additional mpc output like:
Updating DB (#28) ...
volume: 92%   repeat: off   random: on    single: off   consume: off

fixed in playout controls playlistclear with:
       - mpc clear >/dev/null
       - mpc --no-status clear

**Comment by MiczFlor** [comment]
Hi,
I am closing this issue, because it has been silent for over two weeks. If it's not resolved, please open a new issue. Thanks.
All the best, micz
