### ISSUE TITLE
Bluetooth Headphones

### ISSUE THREAD

**Issue by mimi-ac** [MiczFlor/RPi-Jukebox-RFID#1293]
Hello,

I want to complete my Phoniebox by adding a bluetooth headphones.

Does anybody sucessfully installed bluetooth headphones?
I hope that I can switch between headphones and speaker by RFID-Card. 

By the way: I use the normal version of Phoniebox without Spotify and an old version of Raspbian Lite (with Alsa)

Thankx

**Comment by s-martin** [comment]
we have an open PR #1262 for this feature, but it's not yet merged.
