### ISSUE TITLE
What's the reason behind working with absolute paths instead of relative paths?

### ISSUE THREAD

**Issue by pabera** [MiczFlor/RPi-Jukebox-RFID#1315]
[I was refactoring](https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1298) the `playout_controls.sh` file a little and I noticed that this line is omnipresent

https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/5be26c528f7731cd4fd1d4ba23913e5f2622d8fa/scripts/playout_controls.sh#L75

this is then used like this

https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/5be26c528f7731cd4fd1d4ba23913e5f2622d8fa/scripts/playout_controls.sh#L90

Is there a specific reason why you have decided to go with absolute paths instead of relative paths?

```
echo "$1" >> ../logs/debug.log;
```

I am thinking of changing that but I want to hear if I am missing something right of the bat.

**Comment by MiczFlor** [comment]
Hi @pabera 
that's a good question. It's a heritage from the very first hacks I did, carving everything in stone... And it just stayed there. 
Let's turn this around :) if you find any place where this would make sense, then we need to think about the best practice. Until then, make it as simple, light, human and well documented as you seem fit.
