### ISSUE TITLE
HD44780-i2c implementation Typ error in track_time

### ISSUE THREAD

**Issue by derchan** [MiczFlor/RPi-Jukebox-RFID#1328]
Im develop Branch, 
habe ich zur Zeit das Problem das ich einen Typen Error bekomme. Sobald Track Time ausgelesen wird. 
Erscheint folgende Fehlermeldung:
 
File "i2c_lcd.py", line 329, in <module>
    track_time = track_time.replace("\n", "")                                         #
TypeError: a bytes-like object is required, not 'str'

Test durch Auschluss: File funktioniert wieder sobald ich alle track_time Zeilen auskommentiere .

**Comment by derchan** [comment]
Found the error fixed in commit 9f18caa

**Comment by s-martin** [comment]
PR #1323 is merged, closing this issue
