### ISSUE TITLE
Phoniebox / MQTT / HomeAssistant

### ISSUE THREAD

**Issue by TeGuy** [MiczFlor/RPi-Jukebox-RFID#1351]
### What functionality would you like to see in your phoniebox?

I would like to add my Phonieboxes to my HomeAssistant. The MQTT-Plugin in the Phoniebox transmits data to the MQTT broker, but I don't know how to add it to my HomeAssistant bc I found no example config.

### How do you envision the feature to work from a users perspective?

A user would see an example config in the repository which he or she may use...;-)

**Comment by s-martin** [comment]
Did you check https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Smart-Home-remote-control-with-MQTT
?
