### ISSUE TITLE
Best way to update to the new version 1.0?

### ISSUE THREAD

**Issue by MiczFlor** [MiczFlor/RPi-Jukebox-RFID#138]
The new master version as of 1.0 has only been tested on `stretch` and NOT `jessie`. Read the following if you [run Phoniebox on `jessie`](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/137).

If you have a running version of Phoniebox on `stretch`, your best bet would be the [one line install script](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/INSTALL-stretch.md#oneLineInstall).

The install script will detect your existing installation and move it to a folder `BACKUP` and allow you to cherry pick what you want to use from the existing install (audio files, shortcuts, config files, startup sounds, etc.)

**Comment by webjochen** [comment]
great thank you,
has worked wonderfully.
only problem where I had:
the idle shutdown timer was with me on 10 minutes
my phono box went out exactly during the installation
So I had to start again "the one line installation"
everything is going great,
very good work
