### ISSUE TITLE
Minor issue: playout_controls.sh uses lsof, which is not installed by default

### ISSUE THREAD

**Issue by T0bi79** [MiczFlor/RPi-Jukebox-RFID#1456]
First: I don't experience any unexpected behaviour. I just noticed some error messages on the console and traced them.

lsof is not part of a standard Raspberry Pi OS lite installation and is also not added by the phoniebox install script.
However, it is called by playout_controls.sh on several locations, obviously to release locks during shutdown.
Affects both, master and develop branch.

I did not try to add it manually. Probably it is even unneeded (at least I did not notice any negative effects)

**Comment by s-martin** [comment]
Please check #1457, if this fixes the issue.
