### ISSUE TITLE
🐛 | idle-watchdog not working with amixer volume control

### ISSUE THREAD

**Issue by philister** [MiczFlor/RPi-Jukebox-RFID#1497]
### What I did
I'm using amixer volume control. 

### What happened
idle-watchdog.sh doesn't recognize volume above 0 properly.

### Further information that might help

In playout_controls we have a lot of switchs to take this into account. (eg [getvolume](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/2a99a25f7f9f34bbd94afbca1699357d464ea62d/scripts/playout_controls.sh#L508) )
In idle-watchdg.sh this distinction is missing: https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/32981ecd9b43d964e5aab0b7b4efe671af646d80/scripts/idle-watchdog.sh#L25

There is no result from grep, so VOLPERCENT remains empty:
``` bash
$ echo -e "status\nclose" | nc.openbsd -w 1 localhost 6600
OK MPD 0.21.4
repeat: 0
random: 0
single: 0
consume: 0
playlist: 4
playlistlength: 23
mixrampdb: 0.000000
state: pause
song: 2
songid: 3
time: 521:679
elapsed: 521.474
bitrate: 32
duration: 679.131
audio: 44100:24:2
nextsong: 3
nextsongid: 4
OK
```

Quickfix:
Add `[ -z "$VOLPERCENT" ]` (respectivly `[ ! -z "$VOLPERCENT" ]`) to the following lines (which checks, if the Var is set at all)

**Comment by s-martin** [comment]
Thanks for finding this, could you open a PR?
