### ISSUE TITLE
Neuftech: Swipe or place a card Functionality not working

### ISSUE THREAD

**Issue by arvidortwig** [MiczFlor/RPi-Jukebox-RFID#1498]
Hi,

first of all thank you for this wonderful project. I got the phoniebox working so far. RFID (Neuftech) scanner works fine but i cant use the "swipe or place" option properly. When i place the card it just starts the audiofile to play for  a second and then stops. The green light of the reader indicates it still recognizes the card lying on it.  Swiping works flawlessly. Any idea ?

	
Version
2.3 - 2425890 - master
Edition
Classic edition (barebones)

Thanks,
Apunkt

**Comment by s-martin** [comment]
What’s the output of `tail -n 200 /var/log/syslog`?

**Comment by ChisSoc** [comment]
Place does not work with Neuftech readers. They only support Swipe.

Reason: Neuftech only gives a single event when a new card is placed.

You will need to change the reader to RDM6300. 

Or MFRC522 - but that uses a different NFC standard.

**Comment by arvidortwig** [comment]
hi, guys. thank you for answering. I will stick to the neuftech as the RDM6300 needs some kind of voltage altering through an additional board. usb is so comfortable :-)
