### ISSUE TITLE
after upload a song, the song didn`t play

### ISSUE THREAD

**Issue by pwstechnik** [MiczFlor/RPi-Jukebox-RFID#1499]
after upload a song, the song didn`t play. after refresh with Iris scan folders, the song played.

 

> Sep  1 23:37:27 raspberrypi mopidy[25929]: INFO     [MpdSession-2623] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40934
Sep  1 23:37:27 raspberrypi mopidy[25929]: INFO     [MpdSession-2624] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40938
Sep  1 23:37:27 raspberrypi mopidy[25929]: INFO     [MpdSession-2625] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40942
Sep  1 23:37:27 raspberrypi mopidy[25929]: INFO     [MpdSession-2626] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40946
Sep  1 23:37:27 raspberrypi mopidy[25929]: INFO     [MpdSession-2627] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40950
Sep  1 23:37:27 raspberrypi mopidy[25929]: INFO     [MpdSession-2628] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40954
Sep  1 23:37:44 raspberrypi lighttpd[6366]: chown: changing ownership of '/home/pi/RPi-Jukebox-RFID/shared/audiofolders/3Band': Operation not permitted
Sep  1 23:37:44 raspberrypi lighttpd[6366]: chown: changing ownership of '/home/pi/RPi-Jukebox-RFID/shared/audiofolders/3Band/Band Of Horses - No One'\''s Gonna Love Y$
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2629] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40958
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2630] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40962
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2631] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40966
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2632] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40970
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2633] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40974
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2634] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40978
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2635] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40982
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2636] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40986
Sep  1 23:37:52 raspberrypi mopidy[25929]: INFO     [MpdSession-2637] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40990
Sep  1 23:37:56 raspberrypi lighttpd[6366]: /home/pi/RPi-Jukebox-RFID/scripts/inc.writeFolderConfig.sh: line 106: /home/pi/RPi-Jukebox-RFID/shared/audiofolders/3Band/f$
Sep  1 23:37:56 raspberrypi lighttpd[6366]: rm: cannot remove '/home/pi/RPi-Jukebox-RFID/shared/audiofolders/3Band/folder.conf': No such file or directory
Sep  1 23:37:57 raspberrypi mopidy[25929]: INFO     [MpdSession-2638] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40994
Sep  1 23:37:57 raspberrypi mopidy[25929]: INFO     [MpdSession-2639] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:40998
Sep  1 23:37:57 raspberrypi mopidy[25929]: INFO     [MpdSession-2640] mopidy_mpd.session New MPD connection from [::ffff:127.0.0.1]:41002

Any Ideas, what can I do?

**Comment by s-martin** [comment]
So does it play after the scan folders? That’s intended, the database needs to be refreshed after uploading new files.

**Comment by pwstechnik** [comment]
Yes, after the manual scan, play the songs again, not before. Normal white it was automatically updated after uploading. Is  something wrong at permission and which file ?
