### ISSUE TITLE
🐛 | hold time on shutdown button is ignored

### ISSUE THREAD

**Issue by lenlennart** [MiczFlor/RPi-Jukebox-RFID#1509]
### What I did

install fresh phoniebox
connect push button to GPIO 3 and GRD
activate (enabled : True) shutdown button in config
leave other parameters on default (in particular "hold_time : 2")
press shutdown button only briefly (0.2 sec)

### What happened

phoniebox goes in shutdown

### I expected this to happen

phoniebox stay on, as hold time not reached

### Further information that might help

tried setting holdtime to "2.0"

### Base image and version

2.3 - 2425890 - master

### RaspberryPi version

3 B

**Comment by T0bi79** [comment]
Can you post the entire section of this button in settings/gpio_settings.ini?

**Comment by lenlennart** [comment]
after digging thorugh the documentation, it seems the default gpio_settings.ini is missing "hold_mode" (-> Postpone) for the shutdown button.
Works like a charm once added.

**Comment by T0bi79** [comment]
Ah, you're right, that's the problem. It's the same on my test installation.

However, in \components\gpio_control\example_configs\gpio_settings.ini the shutdown button example is correct. It seems another file is copied to 'settings' during installation. I have a look on this later...
