### ISSUE TITLE
GPIO Pin setting change cause issues. "PrevSong"-Button not working 

### ISSUE THREAD

**Issue by scratchplate** [MiczFlor/RPi-Jukebox-RFID#1537]
Hello, i've some trouble getting the GPIO Pins to work. 
Every change in the settings.ini causes other Problems

Some Examples:

- Change "PrevNextControl" to False -> play-pause = no function 
- Change "PrevSong" to pin 7 -> every Button is disabled

-i've to change the GPIO setting for "PrevSong" [pin20] cause there is no function,  even after a new installation 

Can someone help me please? I've no idea what causes the problem. 
Every other Button that i'm using is working, but i'm unable to get this button "PrevSong"-button to work. 

[PrevSong]enabled: True
Type: Button
Pin: 20
pull_up: True
hold_time: 0.3
functionCall: functionCallPlayerNext

Also i've noticed that every other Pin that is enabled have 4,05V, except the Button for "PrevSong". 
Every time i change the Pinout for this Button, the GPIO Pin for "PrevSong" has only 0,45V

Has someone an idea what causes this Problem. I'm looking forward for your suggestions. Thanks!

Greetings

**Comment by s-martin** [comment]
Closing as no interaction for a couple of months.
Feel free to reopen the issue, if the problem still occurs.
