### ISSUE TITLE
Karten Id auf top directory spielt subdirectories nicht ab

### ISSUE THREAD

**Issue by ASchmidt84** [MiczFlor/RPi-Jukebox-RFID#1555]
Moin Moin,

habe jetzt (da CIFS no nicht klappt) bei meinem Sohn einfach mal "kleiner Major Tom" auf die Karte in shared geschubst. Habe vorher via Web die Ordner angelegt. Soweit alles gut. Rechte geändert und dann die Karte auf den Hauptordner angelegt. In der Webapp klicke ich play und alles läuft. Scannt der kleine nun die Karte die mit dem Hauptordner verknüpft ist, passiert leider gar nichts. Muss ich da noch irgendwas machen?

Danke

**Comment by MiczFlor** [comment]
Hi @ASchmidt84 
wenn ich dich richtig verstehe und ich mich richtig erinnere, dann ist das so:

* eine RFID Karte spielt alle Files in einem Ordner ab, mit dem sie verknüpft ist.
* in der Web App gibt es die Option alle Files in einem Ordner abzuspielen ODER alle Files in einem Ordner PLUS Subdirectories abzuspielen

Die zweite Variante mit Subdirectories haben wir später für die Web App hinzugefügt. Diese Möglichkeit gibt es nicht für die RFID Karten. Versuch bitte mal ein File in den Ordner zu legen, der verknüpft ist und dann die Karte zu swipen - dann sollte dieses eine File abgespielt werden.
Dass das nur in der Web App geht hat eine Reihe von Gründen. Weil wir gerade alles noch einmal neu machen ([siehe den branch im Code: **future3**](https://github.com/MiczFlor/RPi-Jukebox-RFID#-version-3-is-coming-), wird das sicherlich erst in Zukunft bedacht, das ist kein einfacher Hack sondern beinhaltet eine Reihe von notwendigen Änderungen von der Web App bis hin zu der Art wie die Verknüpfungen gespeichert sind.
Beste Grüße, micz

**Comment by ASchmidt84** [comment]
Hi Micz,

gut dann bin ich ja nicht bescheuert 😄 
Habe mich schon gefragt ob ich mich gleich bei den Idioten melden soll. Hatte das jetzt x-mal versucht. Gut okay. Dann mache ich für jeden einzelnen Unterordner eine Karte.

Ich freue mich auf future3.
