### ISSUE TITLE
USB Encode Arcade Buttons how to

### ISSUE THREAD

**Issue by ASchmidt84** [MiczFlor/RPi-Jukebox-RFID#1566]
Hallo,

habe jetzt schon einige Tage versucht etwas zu finden. Ich wollte ohne löten einfach mit dem empfohlenen USB Encoder (https://www.amazon.de/gp/product/B01N0GZQZI/ref=as_li_ss_tl?ie=UTF8&psc=1&linkCode=sl1&tag=diebarnfeld-21&linkId=e0d16eed4d011a54edf25f6956a2f758&language=de_DE) ein paar Buttons einbinden.

Ist via USB Verbunden, nun ist die Frage wie kann ich die ansteuern? Ist dafür irgendwo ein howto?

Danke euch

**Comment by MiczFlor** [comment]
Hi @ASchmidt84 
sorry für die Verzögerung. Ich habe es selber noch nicht installiert, aber als *component* findest du den encoder hier im repo:
https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/develop/components/controls/buttons_usb_encoder
