### ISSUE TITLE
🐛 | 'place card' setting doesn't work, audio starts for two seconds, then stops

### ISSUE THREAD

**Issue by SebastianNachtigall** [MiczFlor/RPi-Jukebox-RFID#1576]
### What I did

1. Installed the current 2.3  (2425890 - master) on my Raspberry4 b. 
2. connected my Neuftech USB reader, some speakers directly on Headphone and got everything up&running
3. uploaded an MP3 via Youtube DL --> works fine together with associated RFID card in "Swipe mode"
4. go to settings --> switching to "Placing the card..." and click "Set"
5.  placed the RFID card on the reader

### What happened

song started for about two seconds, then stopped. Removing the card and placing it again didn't change the behaviour. Song would always only play for two seconds.

### I expected this to happen

Placing the card would result in playing the song as long as the card is on the reader
 
### Further information that might help

After some time I found the  "second swipe" options and tried some combinations, which all seemed without effect on the described behaviour. I especially tried the "two second delay" setting and gave different values, no effect.

### Base image and version

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

### Branch / Release

`master`

### Installscript

`scripts/installscripts/buster-install-default.sh`

### RaspberryPi version
`4 B`

### RFID Reader

Bus 001 Device 003: ID 16c0:27db Van Ooijen Technische Informatica Keyboard
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x16c0 Van Ooijen Technische Informatica
  idProduct          0x27db Keyboard
  bcdDevice            0.01
  iManufacturer           1 HXGCoLtd
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)

### Soundcard

none (using the onboard "Headphone" jack)

**Comment by steveleader** [comment]
Seems like you use the USB RFID reader. Those do not trigger a data submission when the card is removed. Only at the first identification of the RFID card data are provided. That's why this function doesn't work with your setup.

Solutions, if you want to use this feature:

- get a RC522 RFID reader, which supports this function out of the box. The installation is not as trivial as the USB connection though (see wiki https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Wiring_for_RC522_card_reader)
- use this hack provided in the wiki, this is a way to achive the desired behaviour with the USB reader with a small adaption (soldering required). https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Stop-on-removal-with-USB-RFID-Reader
