### ISSUE TITLE
No Samba 1.0 support under Windows 10

### ISSUE THREAD

**Issue by Franzformator** [MiczFlor/RPi-Jukebox-RFID#159]
After the first installation of my phoniebox I had to realize that windows 10 (I am using Win 10 Pro) isn’t supporting SAMBA 1.0 anymore. You can reinstall it, but I have still issues with it (can’t open the explored computers).

As I found out, this is no new problem:
•	https://www.raspberrypi.org/forums/viewtopic.php?t=199507 
•	https://support.microsoft.com/de-de/help/4034314/smbv1-is-not-installed-by-default-in-windows 

To make the phoniebox usable for Windows users I would suggest, FTP support as alternative for SAMBA. 

I think it would be nice to decide during the Install-Script whether to use SAMBA or FTP.

**Comment by Franzformator** [comment]
Thank You!
I will try this the next days. For now, I installed a FTP Server to test my Phoniebox.

I also found this Link: https://www.cyberciti.biz/faq/how-to-configure-samba-to-use-smbv2-and-disable-smbv1-on-linux-or-unix/

Checking the comments, it seems to me I should also define Client max and Server min. 
server min protocol = SMB2_10
client min protocol = SMB2
client max protocol = SMB3

I will give it a try.

**Comment by MiczFlor** [comment]
Hi,
Thanks for the feedback. Please don‘t close this thread, I am on holidays and will work this into the script an web app in the coming days 
All the best, micz

**Comment by MiczFlor** [comment]
Hi @Franzformator 
I will work on the FTP idea. Sounds good, the only downside: I need to find a way to manage a setup where somebody is using a different file for `audiofolders`
Please post a SAMBA solution here for windows, if you find any.
Thanks

**Comment by MiczFlor** [comment]
HI @Franzformator 
I added a web uploader. However, that does not yet work with the subfolder issue that I am working on. However, it "solves" the samba issue in a way.
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/htdocs/fileUpload.php
I close this ticket - but if you solve the samba issue, please commit a MANUAL.md pull request or post it in a thread, so I can include it.
Thanks, micz

**Comment by ottk3** [comment]
Hi @Franzformator 

have you tried to add the line `force user pi` [1] to the shared folders in the **/etc/samba/smb.conf** ?
That worked for me with Win10 (not sure which samba version I use on the pi.

[1] replace pi user to another samba user depending on your installation
