### ISSUE TITLE
🐛 | File upload limited to 30

### ISSUE THREAD

**Issue by Hans-Haefner** [MiczFlor/RPi-Jukebox-RFID#1590]
## Bug

File upload limited to 30, is this a Bug or wanted?

### What I did

Files uploaded to the Files and Folders page of the WebGUI.

### What happened

I tried to upload more than 30 files

### I expected this to happen

Upload limited to 30?

## Software

2.1rc1 

### Base image and version

raspbian-buster-lite.img`

Otherwise the output of `cat /etc/os-release`
-->

### Branch / Release

develop

### Installscript

scripts/installscripts/buster-install-default.sh

### Soundcard

DACBerry ONE+

### Other notable hardware

Buttons:
btn_vol0 = 9
btn_stop = 11
btn_next = 7
btn_prev = 27
btn_halt = 12

OnOff SHIM (micro-USB) - Pimoroni

OLED Display ssd1306

KY-040 Rotary Angle Encoder Rotary Encoder Module

**Comment by s-martin** [comment]
The number of files to be uploaded is set to 30 and it’s a reasonable value, see

https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/d76a7efd0ae4e97a897ef0910760b30702c67023/misc/sampleconfigs/php.ini-default.sample#L847-L844

If you want to change that limit, you could change it yourself in `/etc/php/7.4/cgi/php.ini`. This applies to V2 only.
