### ISSUE TITLE
Update-Option for Install-Script + Update Section for Manual

### ISSUE THREAD

**Issue by Franzformator** [MiczFlor/RPi-Jukebox-RFID#160]
I used the Install-Script to setup my fist Phoniebox. It does a very god job! 
Through a failure in the configuration afterwards I had to run the script again.
It would be nice to have an option in the script to decide between a complete new installation an update of the “core components”.

It would be also nice to have a section in the manual that describes the update process to get a newer Phoniebox version.

**Comment by MiczFlor** [comment]
Hi @Franzformator 
I had an update doc in the docs folder all along, but unlinked it due to the one-line-install script. And I will work on the install script, adding the upgrade option. I promise, I will keep it in mind, but will close this issue for now, to keep focus. Thanks, micz
