### ISSUE TITLE
ISSUE on future3

### ISSUE THREAD

**Issue by knuusi** [MiczFlor/RPi-Jukebox-RFID#1611]
### Describe your problem 

Core, Web application ...

#### What's your hardware set up? 

RPi version, RFID Reader, Audio devices etc.

#### If possible, try to attach logs from ... (paths from RPi)

  * `~/RPi-Jukebox-RFID/shared/logs` -> General Jukebox logs
  * `~/INSTALL-XXXXXXXXX.log` -> The logfile being generated when installing the Jukebox code

**Comment by s-martin** [comment]
Please provide some info…..
