### ISSUE TITLE
Read-Only NFS Folder not played on first swipe

### ISSUE THREAD

**Issue by janisHD** [MiczFlor/RPi-Jukebox-RFID#1621]
## Bug

A read-only NFS Folder is not played after first swipe. It works after 2nd swipe.
Assumption: The folder.conf can not be written (due to read-only) and hence the play does not work on the first swipe.
On the 2nd swipe the missing folder.conf is ignored (?) and play starts.

### What I did

- Mount a NFS Folder in the .../shared/audiofolders/... location -> confirmed readable / recognized in the web gui
- Assign RFID card to the folder via web gui
- Swipe card to start playback of the folder / files inside of the folder

#### Expectation
Playback starts

#### Observation
Payback is not starting after first swipe. Playback only starts after 2nd swipe.

#### Variation

- Change permission on NFS folder to Read/Write
- Swipe card to start playback of the folder / files inside of the folder

#### Observation
Folder/files are played back after first swipe

### Further information that might help

I think that the folder.conf can not be written on the first try. This might cause a lock / infinite wait for a script to finish.
Once I swipe the 2nd time the missing folder.conf is ignored and playback starts.

Output of the log with following enabled:
 - DEBUG_rfid_trigger_play_sh
 - DEBUG_single_play_sh

```
########### SCRIPT rfid_trigger_play.sh (2021-11-08.23:13:21) ##
Card ID '0010831805' was used
This ID has been used before.
The shortcut points to audiofolder 'Various Artists/100% Christmas [Disc 1]'.
# Attempting to play: /home/pi/RPi-Jukebox-RFID/shared/audiofolders/Various Artists/100% Christmas [Disc 1]
# Type of play $VALUE: 
$FOLDER set, not empty and dir exists: /home/pi/RPi-Jukebox-RFID/shared/audiofolders/Various Artists/100% Christmas [Disc 1]
  Var $LASTFOLDER: Various Artists/Christmas Swing
  Var $LASTPLAYLIST: Various Artists % Christmas Swing
Checking 'recursive' list? VAR $VALUE: 
recursive? NO
/home/pi/RPi-Jukebox-RFID/scripts/playlist_recursive_by_folder.php --folder "Various Artists/100% Christmas [Disc 1]" > "/home/pi/RPi-Jukebox-RFID/playlists/Various Artists % 100% Christmas [Disc 1].m3u"
  Var $SECONDSWIPE: PAUSE
  Var $PLAYLISTNAME: Various Artists % 100% Christmas [Disc 1]
  Var $LASTPLAYLIST: Various Artists % Christmas Swing
We must play the playlist no matter what: $PLAYPLAYLIST == yes
  VAR FOLDER: Various Artists/100% Christmas [Disc 1]
  VAR PLAYLISTPATH: /home/pi/RPi-Jukebox-RFID/playlists/Various Artists % 100% Christmas [Disc 1].m3u
## SCRIPT single_play.sh (2021-11-08.23:13:22) ##
VAR AUDIOFOLDERSPATH: /home/pi/RPi-Jukebox-RFID/shared/audiofolders
VAR COMMAND: single_check
VAR VALUE: 
VAR FOLDER: Various Artists/100% Christmas [Disc 1]
  - calling inc.writeFolderConfig.sh -c=createDefaultFolderConf -d=$FOLDER
  - back from inc.writeFolderConfig.sh
  content of /home/pi/RPi-Jukebox-RFID/shared/audiofolders/Various Artists/100% Christmas [Disc 1]/folder.conf
  Now doing what COMMAND wants: createDefaultFolderConf
  Command: /home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playlistaddplay -v="Various Artists % 100% Christmas [Disc 1]" -d="Various Artists/100% Christmas [Disc 1]"
```

## Software

Version2.3 - 2425890 - master
EditionClassic edition (barebones)

### Base image and version

`/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
`

### Branch / Release

Version2.3 - 2425890 - master
EditionClassic edition (barebones)

**Comment by pabera** [comment]
Your assumption will most likely be correct. This is a particular problem to your set up and can only be mitigated by updating the code to catch the exception when writing the `folder.conf` to the filesystem. In V2.x, this file is essential.

You can try providing a fix for it yourself or try out [Version 3](https://github.com/MiczFlor/RPi-Jukebox-RFID#-version-3-is-coming-), which is currently in development but it does not depend on the `folder.conf` file anymore which would resolve your problem.
