### ISSUE TITLE
🚀 | Assign RFID directly to track

### ISSUE THREAD

**Issue by zimbo86** [MiczFlor/RPi-Jukebox-RFID#1636]
### What functionality would you like to see in your phoniebox?

I want to assign an RFID chip directly to a track, not to a complete directory

### How do you envision the feature to work from a users perspective?

The idea is a set of animal sounds. RFID chips are tagged to animal toys. Actually (I think) I have to add a folder for every anmimal
DOG\dog.mp3
CAT\cat.mp3
etc.
and use the "single" option.

I´m looking for a way to create one folder and assign a chip directly to an audio file in ist
ANIMALS\cat.mp3
ANIMALS\dog.mp3

**Comment by pabera** [comment]
We will be able to release this feature with the [future3 release](https://github.com/MiczFlor/RPi-Jukebox-RFID#-version-3-is-coming-). I already have it running locally and I will merge it in the next couple of days.

**Comment by s-martin** [comment]
@pabera, now available on future3?

**Comment by s-martin** [comment]
Available for version 3.x (future3)
