### ISSUE TITLE
Mini typo (bluethooth)

### ISSUE THREAD

**Issue by jeverling** [MiczFlor/RPi-Jukebox-RFID#1693]
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/6b72a21f5c5e5906ded14eb87a79b763d6a5f2a9/installation/routines/customize_options.sh#L83

**Comment by ChisSoc** [comment]
Could you create a pull request with your typo fix?

**Comment by jeverling** [comment]
I thought I had, I think I just committed and then forgot the actual PR. Sorry about that.
