### ISSUE TITLE
Alias Missing - Inc_volume

### ISSUE THREAD

**Issue by maedball** [MiczFlor/RPi-Jukebox-RFID#1727]
Either the aliases inc and dec_volume are not done by now or the documentation is pointing to the wrong alias.

Invalid rpc command alias 'inc_volume' has been mapped to 'misc.empty_rpc_call()'

**Comment by Groovylein** [comment]
@ChisSoc I think this is due to the move to Pulseaudio. Or did we forget to change it on the WebApp @pabera ?

**Comment by Groovylein** [comment]
@maedball which version did you install?

**Comment by maedball** [comment]
I just did a pull, so latest ;-).

all other aliases are working i am currently trying to change it away from alias to rpc, but since i am still working at the same time i havent gone far by now ;-p

    volume:
        Type: RotaryEncoder
        Pins: [6, 12]
        FunctionCW: {volume.ctrl.change_volume, kwargs: {step: 1}}
        FunctionCCW:  {alias: dec_volume,kwargs: {step: 1}}
        action_after_increments: 2

**Comment by maedball** [comment]
It looks like i have it working, and it is just a documentation thing. 

    volume:
        Type: RotaryEncoder
        Pins: [6, 12]
        FunctionCW: {alias: change_volume, kwargs: {step: 5}}
        FunctionCCW:  {alias: change_volume, kwargs: {step: -5}}
        action_after_increments: 2

**Comment by Groovylein** [comment]
> It looks like i have it working, and it is just a documentation thing. 


The template needs to be changed as well.

**Comment by pabera** [comment]
> It looks like i have it working, and it is just a documentation thing.

@maedball: Great that you could figure it out yourself. Do you mind referring to the documentation that requires an update? :-)

**Comment by pabera** [comment]
Just saw this #1730 .. 👍

**Comment by maedball** [comment]
I am really bad in using Github so hope all is fine and it helps some ppl ;-)

By the way really nice and understandable structure. I wouldn't have figured it out without the well designed documents and structure! Now back to testing, next step gpio rfid reader...

**Comment by maedball** [comment]
> > It looks like i have it working, and it is just a documentation thing.
> 
> The template needs to be changed as well.

Sorry i just saw that comment, to what template are you referring?

**Comment by Groovylein** [comment]
This one :)

https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/develop/resources/default-settings/gpio.example.yaml
