### ISSUE TITLE
🚀 | Possibility to clean the "Last used Chip ID"

### ISSUE THREAD

**Issue by Lippsson** [MiczFlor/RPi-Jukebox-RFID#1738]
## Feature Description
I want to see the possibility to att new content without to link that with the last used chip ID.**

### What functionality would you like to see in your phoniebox?

I suggest a clean button in line with the "Submit" and "Cancel" button
or
a hypertext below the Last used Chip Id with text: "Clean ID field" 

### How do you envision the feature to work from a users perspective?
Some of my content (spotifly playlist, websadio) i control from the browser and dont need a NFC chip to link.

**Comment by pabera** [comment]
Unless you can do it yourself, there is no active development for version 2.x.
I think the behaviour you describe is already the case for version 3.x.
