### ISSUE TITLE
🚀 Possibility to delete folder from browser

### ISSUE THREAD

**Issue by Lippsson** [MiczFlor/RPi-Jukebox-RFID#1739]
## Feature Description
I wish i had the possibility to delete a folder from the Folder & Files section 

to have a new section in the manage filesfolder.php side 

to choose a existing folder/file/playlist and click on delete. 
It would be also be easy to have all existing audiofolders with a checkbox so user can delete 2 or more folder att the same time

Now the only way to delete folders are to remote in with ftp and delete:
the playlist in:
/home/pi/RPi-Jukebox-RFID/playlist
and the folder in:
/home/pi/RPi-Jukebox-RFID/shared/audiofolders

**Comment by pabera** [comment]
Unless you can do it yourself, there is no active development for version 2.x. 
If you wish you to see this feature in 3.x, just label it with `future3`.
