### ISSUE TITLE
Volume Controll does not work

### ISSUE THREAD

**Issue by toblinga** [MiczFlor/RPi-Jukebox-RFID#176]
Hi,
i've just updated to the newest release (master) with online install script.

But the Volume controll does not work. Following observations:
* In webfrontent the volume is always -1
* File "Audio_Volume_Level" does not exist in ~/RPi-Jukebox-RFID/settings
* the following script from (playout_controll.sh) returns always -1
```
getvolume)
        # read volume in percent
        VOLPERCENT=$(echo -e status\\nclose | nc -w 1 localhost 6600 | grep -o -P '(?<=volume: ).*')
        echo $VOLPERCENT
	;;
```
* following gets following result => i think there is the issue...
```
nc -w 1 localhost 6600
OK 
MPD 0.19.0
```

**Comment by toblinga** [comment]
could this issue base on a wrong mpd configuration?
I'm using a usb sound card...

**Comment by MiczFlor** [comment]
Hi @toblinga 
as often... difficult to make any guesses from a distance. Have you tried to make it work without the USB soundcard? If you plug the speakers straight into the Pi you need to change the settings in two places to "PCM". See here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/MANUAL.md#i-moved-my-audiofiles-now-the-playout-does-not-work
If that works, at least we would know: it must be the soundcard.

**Comment by toblinga** [comment]
had the wrong mixer name /etc/mpd.conf
thanks for the hint, and sorry for the use less issue ... :/
