### ISSUE TITLE
Installation as different user (not user pi)

### ISSUE THREAD

**Issue by bigi-io** [MiczFlor/RPi-Jukebox-RFID#1785]
## Feature Description
Right now, the installation routine does not work, if not run as the user pi

### What functionality would you like to see in your phoniebox?
it would be cool, if the installation would work without creating the user pi

### How do you envision the feature to work from a users perspective?
same installation procedure if logged in as other sudo-user

### Further information that might help
if not possible, it would be nice, if the installation guide is pointing to the necessity of creating user pi:
	sudo useradd pi
	sudo usermod -aG sudo pi

**Comment by s-martin** [comment]
Might be necessary anyways

https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

**Comment by s-martin** [comment]
@pabera is this adressed in future3?

**Comment by Kreiszahler** [comment]
I would highly appriciate a version running with the latest RaspiOS.

**Comment by s-martin** [comment]
Version 2.4 was released yesterday, which also includes PR #1543.

@bigi-io, you might want to check 2.4, if this fixes your issue.

**Comment by mikea** [comment]
Still has user `pi`  backed in:

e.g.:
```
$ cat /etc/systemd/system/phoniebox-gpio-control.service
[Unit]
Description=Phoniebox GPIO Control Service
After=network.target iptables.service firewalld.service

[Service]
Type=simple
User=pi
Group=pi
```

**Comment by mikea** [comment]
It is worth noting that fresh version of raspbian lite asks for a user-name as part of first boot. So it will be more and more likely not to have `pi` user.

**Comment by AlvinSchiller** [comment]
@s-martin @pabera as this isn't a trivial change, should there be a check on installation if the current user is "pi" and quit otherwise? This would at least prevent upcoming issues of this kind until a proper solution is implemented.

**Comment by s-martin** [comment]
I agree, a check on the name could at least give the user a hint what's going on.

In addition we should mention it in our docs that Phoniebox needs 'pi'.

**Comment by AlvinSchiller** [comment]
> In addition we should mention it in our docs that Phoniebox needs 'pi'.
The current docs already mention that the User "pi" should / needs to be used.

**Comment by s-martin** [comment]
#2132 will fix this for future3.

For 2.x we won't fix this.
