### ISSUE TITLE
run_configure_audio generates broken ~/.config/pulse/default.pa file because of missing '#' characters

### ISSUE THREAD

**Issue by marc-up** [MiczFlor/RPi-Jukebox-RFID#1797]
The current version of run_configure_audio.py generates a broken default.pa file because of missing `#` characters while parsing.

Furthermore some `/n` are missing.

This happens in future3/develop and future3/main

The generated output looks like this:

`The default sink. Note that is may still be changed at run time by various PulseAudio rulese.g. when connecting a USB Sound Cardset-default-sink equalizer_for_alsa_output.platform-soc_sound.stereo-fallback`

It should look like this:

```
# The default sink. Note that is may still be changed at run time by various PulseAudio rulese.g. when connecting a USB Sound Card
set-default-sink equalizer_for_alsa_output.platform-soc_sound.stereo-fallback
```

**Comment by s-martin** [comment]
Thanks for reporting this.
Seems like you fixed this already in your own repo.


Do you want to open a PR?
Thank you!
