### ISSUE TITLE
Problem with RFID Reader🐛 | BUG SUMMARY

### ISSUE THREAD

**Issue by CoachPaulJohnson** [MiczFlor/RPi-Jukebox-RFID#1799]
### What I did
I reset my previously running Phoniebox (~Fall 2020) and installed the buster legacy OS. I ran the installer script. My RFID Scanner makes noises and conrol LED is on. Since the RFID scanner was previously working I expected it to work again.

### What happened

I was unable to add new cards with the web App. Further digging showed that I was unable to execute RegisterDevice.py to manually set up the RFID scanner. 
![Troubleshooting](https://user-images.githubusercontent.com/102905616/161428012-24df76fa-da3a-43f8-b173-4a02fa19b4fb.PNG)

On another fresh install with more attention to detail this still prevailed.
![Troubleshooting2](https://user-images.githubusercontent.com/102905616/161427993-66d35959-e44b-4d08-9c5b-69d255d6463e.PNG)

### Installscript
scripts/installscripts/buster-install-default.sh

### RaspberryPi version
4B

### RFID Reader

M301 Mifare card reader.

Thanks already!

**Comment by ginandtronic** [comment]
HI Paul i had this very same problem with the Waveform PN532 tjis worked for me

`sudo apt-get install python3-evdev -y`

**Comment by CoachPaulJohnson** [comment]
Hi and thanks alot!

This worked for me as well.
