### ISSUE TITLE
Not playing mp3s but Podcasts will play????🐛 | BUG SUMMARY

### ISSUE THREAD

**Issue by ginandtronic** [MiczFlor/RPi-Jukebox-RFID#1803]
## Bug
Local files wont play but the podcasts in the example content will - I'm making this for my daughters birtday in 1 week and have spent hours getting it to function i finally heard joyous audio last night whilst shuffle playing the ZZZ example content and noticed the only files that will play are the podcast feeds....so strange??
### What I did
Intalled one line install buster as per guide, installed Waveform PN233 hat RFID reader, installed evdev & dependencies etc as per guide, RFID reader is working albeit after reinstalling it after boot. MPD fails to run on first boot, but works after sudo service mpd restart

### What happened
Only podcasts are played and not mp3s

### I expected this to happen
Upload and play mp3s

### RaspberryPi version
3+B

### RFID Reader
Waveform PN232 Hat

### Soundcard
Headphone jack

**Comment by s-martin** [comment]
Are you using Spotify or classic edition?

**Comment by ginandtronic** [comment]
Hi Martin i believe i installed both...

**Comment by ginandtronic** [comment]
Its working great now with classic edition....

**Comment by s-martin** [comment]
Unfortunately Spotify changed their API, so Spotify support is currently broken, see #1815

**Comment by s-martin** [comment]
@ginandtronic If this works now, you could close this issue.

**Comment by s-martin** [comment]
Closing this for now. Feel free to reopen, if the issue still exists.
