### ISSUE TITLE
gpio.yaml für V3.2.0 Beta

### ISSUE THREAD

**Issue by jens7885** [MiczFlor/RPi-Jukebox-RFID#1809]
Moin! Ich habe die Box noch für eine frühe V2-Version gebaut mit einfachen Druckknöpfen und externen Widerständen.
Ich wollte nun mal V3.2.0 Beta ausprobieren und stehe in Sachen GPIO-Konfiguration ein bisschen da wie der Ochs vorm Berg.
Hätte jemand eine beispielhafte gpio.yaml für mich, an der ich mich orientieren kann? Wie gesagt, diese ganzen Features wie Drehknöpfe etc. sind alle nicht relevant und die Pin-Nummerierung kann ich anpassen. Danke!

**Comment by ChisSoc** [comment]
Check out the [GPIO documentation](https://rpi-jukebox-rfid.readthedocs.io/en/latest/userguide/gpioz.html)

It will also point you to a sample file in your local installation `resources/default-settings/gpio.yaml`.

**Comment by s-martin** [comment]
Closing for now.
Feel free to open a new issue, if the problem still occurs.
