### ISSUE TITLE
Playlist display time wrong for longer audio files

### ISSUE THREAD

**Issue by ComicSans** [MiczFlor/RPi-Jukebox-RFID#184]
I have an audiobook with close to 10 hours length. The display in the web frontend however only shows minutes and seconds, so "9 hours, 13 minutes and 32 seconds" become "13:32".

The calculation of $playlistOverallTime and related variables in inc.loadedPlaylist.php are not sufficient in this case (and I don't think, "date" is the correct approach here anyway). 

What about something like this?

```
function secondsToTime($seconds) {
    if (empty($seconds)) { return false;}
    $seconds = floor($seconds);
    $dtF = new \DateTime('@0');
    $dtT = new \DateTime("@$seconds");
    return $dtF->diff($dtT)->format('%ad %hh %im %ss');
}
```

**Comment by MiczFlor** [comment]
Hi @ComicSans 
can you create a pull request?

**Comment by ComicSans** [comment]
This may take a few days :)

**Comment by princemaxwell** [comment]
I have fixed it in my new version.
I will make a pull request when i have completed testing for my spotify-version...
