### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by ComicSans** [MiczFlor/RPi-Jukebox-RFID#185]
Web console reports these files as missing:

```
http://pi/_assets/jQuery-File-Upload-9.22.0/css/jquery.fileupload.css
http://pi/_assets/jQuery-File-Upload-9.22.0/css/jquery.fileupload-ui.css
http://pi/_assets/MaterialDesign-Webfont-master/css/materialdesignicons.min.css.map
```

**Comment by MiczFlor** [comment]
@ComicSans 
thanks! Added it to the `develop` branch which I am merging to master - after my call for testing in the subfolder thread provoked no response :)

**Comment by ComicSans** [comment]
@MiczFlor What subfolder thread? Is there a better place to report error messages like this?
