### ISSUE TITLE
Cannot search for albums when connecting a new RFID tag on future3

### ISSUE THREAD

**Issue by varac** [MiczFlor/RPi-Jukebox-RFID#1852]
### Describe your problem 

Steps to reproduce:

* `Cards` -> `+`
* Swipe card
* `Select an action` -> `Select Music`
* When I try to enter sth in the search bar, nothing happens (not even my typed characters appear)

#### What's your hardware set up? 

* Phoniebox setup fresh using today's Rpi OS lite 32bit (bullseye)
* Installation following the [Installing Phoniebox future3](https://rpi-jukebox-rfid.readthedocs.io/en/latest/install.html) instructions

**Comment by handfrog** [comment]
Same here. I cannot make any input into the search input box.
Tried with: (latest version)
 - Chrome on Android
 - Chromium on ArchLinux
 - Firefox on ArchLinux

**Comment by s-martin** [comment]
@pabera @ChisSoc

**Comment by pabera** [comment]
I'll have a look soon!

**Comment by s-martin** [comment]
Works for me on future3/develop (will be 3.6 release), see 
![grafik](https://github.com/MiczFlor/RPi-Jukebox-RFID/assets/6143783/16215b0c-ff81-4c47-8b31-682719372250)

But you need to click on the lens first, so the search bar appears.

**Comment by s-martin** [comment]
Seems to work (again) for current future3.
@varac could you check?

**Comment by varac** [comment]
Oh cool, I tried again and it works now (fetaure3/develop) :partying_face:
