### ISSUE TITLE
Idea: Get rid of www-data in sudoers

### ISSUE THREAD

**Issue by leachiM2k** [MiczFlor/RPi-Jukebox-RFID#186]
Hello all,
thank you for this cool project, I really like it.
But I feel kind of uncomfortable by giving all root right to www-data.
It seems very insecure in many ways since the rasPI is handing in my network and is potentially accessible from the outside.

I would like to work on a solution to make this entry unnecessary.
What will break if I remove it? (Need to know it to make a fix/workaround.)

**Comment by MiczFlor** [comment]
Hi @leachiM2k 
"root" might not be needed but "sudo" is used in many places. The origin of "root" came from the time of using `VLC` as the media player through the webserver AND the scripts (which run as user *pi*).

The best way to tackle this would be a hackathon, half a day, a few people in one room. So if you are up for is AND based in Berlin, this might be the first *Phoniebox Hackathon* :)
