### ISSUE TITLE
default installation missing package "evdev"🐛 | BUG SUMMARY

### ISSUE THREAD

**Issue by MarkusF1895** [MiczFlor/RPi-Jukebox-RFID#1872]
## Bug
The https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/docs/INSTALL-COMPLETE-GUIDE.md#6-install-phoniebox-software runs into an error because package evdev is missing! 
### What I did
manuelly install evdev

**Comment by s-martin** [comment]
Fixed in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1791, but not yet merged to master.

**Comment by MarkusF1895** [comment]
Thanks for the hint. Please close this issue. I tried again, as described in #1791. see here: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/1874

Incidentally, I think it makes sense to either mention the installation of the requirements in the installation instructions or to include them in the "one-line command."
