### ISSUE TITLE
Nginx failing to start for non ipv6 setup

### ISSUE THREAD

**Issue by wastlmuc** [MiczFlor/RPi-Jukebox-RFID#1889]
### Describe your problem 

Nginx service fails to start with `nginx: [emerg] socket() [::]:80 failed `

#### What's your hardware set up? 

RPi veversion 1

#### Solution
In `/etc/nginx/sites-enabled/default ` comment out `listen [::]:80 default_server; ` . 
If this is the desired way, I can adapt the installation script for this.

**Comment by s-martin** [comment]
Hi, thanks for your suggestion.
Can you add a pull request with the necessary change?

**Comment by s-martin** [comment]
3.4 was just released, https://github.com/MiczFlor/RPi-Jukebox-RFID/releases/tag/v3.4.0

Could you check, if your problem was fixed?

**Comment by AlvinSchiller** [comment]
Will be fixed shortly in 3.5.1

**Comment by AlvinSchiller** [comment]
fixed with #2254
