### ISSUE TITLE
python3-evdev not installed - needs to be installed

### ISSUE THREAD

**Issue by LeDucCestMoin** [MiczFlor/RPi-Jukebox-RFID#1897]
### What I did

I installed the raspberry pi with above mentioned buster image and ran the installer script`

### What happened
ModuleNotFoundError: No module named 'evdev'

### I expected this to happen

No ModuleNotFoundError
### Base image and version

2022-09-22-raspbian-buster-lite.img

### Branch / Release
 
master
### Installscript

bust-install-default.sh

### RaspberryPi version

Raspberry Pi 3 Model B Rev 1.2

### RFID Reader
ffff:0035 Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader

### Soundcard
iqaudio-dacplus

### Other notable hardware
none

**Comment by s-martin** [comment]
Was fixed in https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/1791, but this is not part of master yet.

**Comment by s-martin** [comment]
V2.4.0 was released today - fixed.
