### ISSUE TITLE
Pirate Audio🐛 | Button Volume Up without function

### ISSUE THREAD

**Issue by Monikajosa** [MiczFlor/RPi-Jukebox-RFID#1974]
## How to fix

bcm20 = volume_up,active_low,150
change to
bcm24 = volume_up,active_low,150

**Comment by s-martin** [comment]
I made a PR.
Do these changes fix your issue?

Which Raspberry Pi are you using?

**Comment by Monikajosa** [comment]
yes these change fixed my issue. If ound the soloution at: https://github.com/pimoroni/pirate-audio/blob/master/mopidy/install.sh

i use raspberry pi 3 b +
