### ISSUE TITLE
🚀 | future3 - Add Hifiberry (Miniamp) support

### ISSUE THREAD

**Issue by s-martin** [MiczFlor/RPi-Jukebox-RFID#2014]
### What functionality would you like to see in your phoniebox?

I would love to have support for [Hifiberry Miniamp](https://www.hifiberry.com/shop/boards/miniamp) (or other Hifiberry boards) in future3 

### How do you envision the feature to work from a users perspective?

while configuring Phoniebox Hifiberry should be automatically detected and configured.

### Further information that might help

Configuring Hifiberry https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

work in progress on V2, which should show how this could be implemented https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/71b525782dd44a3f706dbf495edcbb5cc0f72c75/components/audio/Hifiberry/setup_Hifiberry.sh

**Comment by pabera** [comment]
It's been a while since I tried, but I had it working already in the past. What's the blocker that you are facing?

**Comment by s-martin** [comment]
After I read https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/develop/documentation/builders/audio.md#audio-configuration correctly it wasn't so difficult though :D
