### ISSUE TITLE
CMDNEXT and CMDPREV cards work, then playback stops

### ISSUE THREAD

**Issue by jkriss** [MiczFlor/RPi-Jukebox-RFID#203]
Next and previous track are working fine in the web interface, but when I trigger them with an RFID card, it works for a second, then playback stops.

If I run the script directly with the next or previous card id, I get output like this:

```
$ scripts/rfid_trigger_play.sh --cardid=22953027
The Beatles - Something
[playing] #2/17   0:00/3:02 (0%)
volume: 80%   repeat: off   random: off   single: off   consume: off
scripts/rfid_trigger_play.sh: line 292: [: ==: unary operator expected
/home/pi/RPi-Jukebox-RFID/scripts/resume_play.sh: line 68: [: ==: unary operator expected
volume: 80%   repeat: off   random: off   single: off   consume: off
loading:
mpd error: No such playlist
/home/pi/RPi-Jukebox-RFID/scripts/shuffle_play.sh: line 85: [: ==: unary operator expected
volume: 80%   repeat: off   random: off   single: off   consume: off
```

Any ideas? I installed the software today, using the one-line install script.

**Comment by MiczFlor** [comment]
Hi @jkriss 
One quesiton, the `scripts/rfid_trigger_play.sh --cardid=22953027` cardID is for a playlist or for the skip command?
And: is it possible (if it is for the skip command) that there is a folder with the name `22953027` in the audiofolders directory?

**Comment by MiczFlor** [comment]
HI @jkriss 
I pushed a fix to the branch `develop`. Could you see if this fixes the issue?
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/2db344b0179fc8ded77aedb6916e1558225c6d38

**Comment by jkriss** [comment]
Yep, this works! Thanks!

**Comment by MiczFlor** [comment]
HI @jkriss 
thanks for the feedback, I will push it to master later today then.
