### ISSUE TITLE
🐛 OneLineInstallScript installs future3?

### ISSUE THREAD

**Issue by ElHado** [MiczFlor/RPi-Jukebox-RFID#2033]
I wanted to clean install my phoniebox. I think the installscript installs the new version, not 2.4. Could that be? 

It looks not as my old version and it don't work correctly.

**Comment by s-martin** [comment]
If you followed the instructions here https://github.com/MiczFlor/RPi-Jukebox-RFID#quick-install-version-2 it should be 2.4.

What‘s the output of `cat ~/RPi-Jukebox-RFID/settings/version`?

**Comment by ElHado** [comment]
Thanks, had to be at the wront install tutorial. Took your link and now it works. Sorry :-(
