### ISSUE TITLE
Relativer Pfad in inc.viewFolderTree.php

### ISSUE THREAD

**Issue by oli82** [MiczFlor/RPi-Jukebox-RFID#204]
In der oben genannten Datei beziehst du dich noch auf einen relativen Pfad:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/e55c36c93b03168afd635a7efd9a805e13b1f403/htdocs/inc.viewFolderTree.php#L104

Gruß
Oli

**Comment by MiczFlor** [comment]
Hi @oli82 
nice catch. Silly me :) fixed here: https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/205
