### ISSUE TITLE
Service does not start on reboot on future3

### ISSUE THREAD

**Issue by votti** [MiczFlor/RPi-Jukebox-RFID#2056]
### Describe your problem 

Installing jukebox from `future3/develop` did not autostart the service on a brand new Rasbian lite.
The reason was that on the recent Raspbian user services do not seem to start with reboots per default.
This can be fixed by running once:
```
loginctl enable-linger
```
which enables user services to start at reboot.
This should be done as part of the installation script.

#### What's your hardware set up? 

Raspberry Pi 3 Model B Rev 1.2
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
Linux phnonie 6.1.21-v7+

#### If possible, try to attach logs from ... (paths from RPi)
Running `systemctl --user list-units --type=target ` immediately after reboot and login shows that the `default.target` (=target of jukebox service) is not started yet but just starting.

**Comment by pabera** [comment]
Just a question

> did not autostart the service

Which "service" are you referring to? `loginctl` is required to to login as a user but this was never a problem before.

**Comment by s-martin** [comment]
3.4 has been released and so far this was not reproducible.
Closing, but feel free to reopen, if the issue still occurs for you.
