### ISSUE TITLE
FHEM integration

### ISSUE THREAD

**Issue by no-Legend** [MiczFlor/RPi-Jukebox-RFID#208]
It is possible to integrate MPD of the phoniebox into FHEM.

Just do the following steps:
1. Login (u need super user rights)
2. sudo nano /etc/mpd.conf
2.1 search for port (ctrl + w)
2.2 remove # in front of port
3. reboot phoniebox (sudo reboot)
4. define in the device in them like "define phoniebox1 MPD 192.168.0.99 6600"
4.1 change port if you changed it at the mpd file on the phoniebox
4.2 additional FHEM informations see here https://wiki.fhem.de/wiki/MPD
5. save the FHEM config it the connection is working
6. use it and have fun

Cheers Robert

**Comment by Alwiz79** [comment]
as I am running a homematic installation here, I wondered which use case is behind your fhem integration.
Could you explain ?
