### ISSUE TITLE
Missing localization string for settings.dialogs.reboot.bye on future3

### ISSUE THREAD

**Issue by DivineDominion** [MiczFlor/RPi-Jukebox-RFID#2101]
When rebooting the Pi from the web app, I noticed that the reboot dialog's title `settings.dialogs.reboot.bye` was a localization placeholder.

(My browser and OS are set to English locale.)

<img width="355" alt="2023-11-08 21-41-14 Arc - Phoniebox@2x" src="https://github.com/MiczFlor/RPi-Jukebox-RFID/assets/59080/abb9d221-60df-48d4-8eca-7b81493d610f">

**Comment by s-martin** [comment]
#2107 fixed this
