### ISSUE TITLE
Documentation leads in 404🐛 | BUG SUMMARY

### ISSUE THREAD

**Issue by ASchmidt84** [MiczFlor/RPi-Jukebox-RFID#2125]
https://rpi-jukebox-rfid.readthedocs.io/en/latest/install.html leads in 404 and is not available.

Is their another way? I promissed my son to setup the new version this weekend.

Thank you.

André

**Comment by s-martin** [comment]
Hi,

future3 docs are now located in the repo at https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/future3/develop/documentation

**Comment by ASchmidt84** [comment]
Perfect. Thank you so much. You saved me.

**Comment by s-martin** [comment]
Fixed the paths also in the README.md in branch develop
