### ISSUE TITLE
🐛 | Network Settings in Bookworm

### ISSUE THREAD

**Issue by AlvinSchiller** [MiczFlor/RPi-Jukebox-RFID#2183]
### What I did

Set a Wifi via the WebUi

### What happened

The new settings are not used

### I expected this to happen

The settings are used

### Further information that might help
With Bookworm the network settings have changed. Now `NetworkManager` is used.
This breaks settings of "old" wpa_supplicant.conf and dhcpcd.conf.

Static IP and Autohotspot are also affected.

### Base image and version
Bookworm lite

### Branch / Release
master 2.5.0

### Installscript
`scripts/installscripts/install-jukebox.sh`

### RaspberryPi version
3 A+

**Comment by s-martin** [comment]
This does effect both V2 and V3, right?

**Comment by AlvinSchiller** [comment]
yep, couldn't test on v3 right now, which features are effected.
But i assume static ip and autohotspot (already known).

**Comment by s-martin** [comment]
Maybe useful references:
- https://forums.raspberrypi.com/viewtopic.php?t=357623
- https://networkmanager.dev/docs/api/latest/

`nmcli` may be the command to go.

**Comment by AlvinSchiller** [comment]
Yep nmcli was working on manual test. Need to implement a switch for the features, depending on OS Version. 
Or maybe there is still comon ground?

**Comment by AlvinSchiller** [comment]
### Temporary workaround
Before running the installation, the network config has to be changed via raspi-config, to use the "old" dhcpcd network settings.

> [!IMPORTANT]
> If the settings are changed, your network will reset and Wifi will not be configured, so you lose ssh access via wireless network.
> So make sure you perform the following steps in a local terminal with a connected monitor and keyboard.

Change network config
* run `sudo raspi-config`
* select `6 - Advanced Options`
* select `AA - Network Config`
* select `dhcpcd`

If you need Wifi, add the information now
* select `1 - System Options`
* select `1 - Wireless LAN`
* enter Wifi information
