### ISSUE TITLE
Network Settings in Bookworm on future3

### ISSUE THREAD

**Issue by AlvinSchiller** [MiczFlor/RPi-Jukebox-RFID#2184]
## Bug

See https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2183

### Further information that might help
With Bookworm the network settings have changed. Now `NetworkManager` is used.
This breaks settings of "old" wpa_supplicant.conf and dhcpcd.conf.

Static IP and Autohotspot are affected. Maybe further features that use network settings.

### Base image and version
Bookworm lite

### RaspberryPi version
3 A+

**Comment by AlvinSchiller** [comment]
### Temporary workaround
Before running the installation, the network config has to be changed via raspi-config, to use the "old" dhcpcd network settings.

> [!IMPORTANT]
> If the settings are changed, your network will reset and Wifi will not be configured, so you lose ssh access via wireless network.
> So make sure you perform the following steps in a local terminal with a connected monitor and keyboard.

Change network config
* run `sudo raspi-config`
* select `6 - Advanced Options`
* select `AA - Network Config`
* select `dhcpcd`

If you need Wifi, add the information now
* select `1 - System Options`
* select `1 - Wireless LAN`
* enter Wifi information

**Comment by s-martin** [comment]
Fixed in 3.5
