### ISSUE TITLE
How to leave MP3s on USB-Stick

### ISSUE THREAD

**Issue by sigmaeo** [MiczFlor/RPi-Jukebox-RFID#22]
Sorry this is not a real issue, only a hint:
You may add this to the readme, how one can use RPi-Jukebox with MP3s on an USB stick.
The USB-stick is automatically mounted to 
/media/usb0
I leave all MP3 there and put only softlinks to the audiofile folder with this command:
```
ln -s /media/usb0/* /home/pi/RPi-Jukebox-RFID/shared/audiofolders/
```
This may help some beginners.

**Comment by MiczFlor** [comment]
@sigmaeo nice one, will do that.

**Comment by MiczFlor** [comment]
@sigmaeo added it here: https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/MANUAL.md#playing-audio-files-from-a-usb-stick
