### ISSUE TITLE
Remove RFID Card Reader Beep

### ISSUE THREAD

**Issue by elalemanyo** [MiczFlor/RPi-Jukebox-RFID#223]
Hi,
Thanks for this great Project! Amazing what you did!
I am testing and I would like to remove the beep from the RFID Card Reader, is there a way? I am using the same you listed in your Shopping List.

Thanks!

**Comment by MiczFlor** [comment]
Hi @elalemanyo 
Thanks for your suggestion (and don't forget to post pics when you finished the box!).
I don't know of a way to make the beep disappear. The only option: use a different reader. See this thread for example:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/11#issuecomment-382337194
And you will see at the same time: they would like the beep to confirm that the card was read :)

**Comment by MalteHST** [comment]
If you open the housing of your card reader, you can easily identify the buzzer making the beep noise. For me this was also a bit annoying so I just de-soldered it from the PCB. Really little effort to do.

**Comment by MiczFlor** [comment]
HI @MalteHST 
can you send me a pic in this thread, so I can add it to the trouble shooting section? People do keep asking for this.

**Comment by MalteHST** [comment]
I've taken a pic out of the issue created from @zxa:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/62

![42057974-35de860e-7b1f-11e8-8fd1-cad7b2f810ed](https://user-images.githubusercontent.com/40899451/45949133-108a5d80-bffb-11e8-85ff-9f843c442d46.png)

Buzzer can be seen in the blue circle, attached/ soldered with to pins from the back of the PCB. You can remove it by desolder these to pins. This has no influence to the reading function. Additionally the reading process of a tag is confirmed  by a green LED for this model. 

Although of course this is not an option if you want to switch sometimes between a beep noise or not.

**Comment by elalemanyo** [comment]
@MalteHST Maybe I would remove the Buzzer, and add it again with two cables one of them with a switch, like this I can remove the sound or add it anytime. I think it should work.

**Comment by no-Legend** [comment]
It is also possible to use some sticky tape on the opening hole of the buzzer.
This will normal reduce the volume a lot.
Give it a try.

**Comment by Caliandroid** [comment]
@no-Legend : Thanks. As the beep is useful but too loud, i'll try the tape-hack.

**Comment by toblinga** [comment]
I putted some drops of candle wax on. This works fine against the loudness
;)
Cheers

Stefan Caliandro <notifications@github.com> schrieb am Do., 27. Sep. 2018,
11:10:

**Comment by MiczFlor** [comment]
Hi everybody, 

this is the funnies hack conversation we had so far :) from tape to candle wax to ripping the thing out alltogether. I added this to the manual:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/MANUAL.md#how-can-i-disable-the-beeping-noixe-of-the-rfid-reader
... and will close the thread for now.

**Comment by sandreas** [comment]
I soldered it out and it worked perfectly... no sound but RFID is still working - yay
