### ISSUE TITLE
feature request: Hotspot Mode per GPIO aktivieren

### ISSUE THREAD

**Issue by no-Legend** [MiczFlor/RPi-Jukebox-RFID#225]
Hallo Zusammen,

ich hatte gerade eine Idee.
Ist es möglich den RaspberryPI per GPIO Tastenkombination in den HotSpot mode zu setzten?

Somit könnte man zum beispiel auch im Urlaub die Box per WLAN steuern,
dazu könnte man auch die Box für einen freund aufsetzt und er kann dann später einfach die BOX ohne Konsolen Kenntnisse in sein WLAN hängen.

Alternativ wenn man per Tastenkombination auf der Box eigene Scripte ausführen könnte.
Damit könnte man solche Feature relative einfach selbst aufsetzten.

Gruß Robert

**Comment by gizmo21** [comment]
I think it's a great idea, I guess with hotspot mode you mean PI as access point:
https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md

This way you could access the Pi to directly control OR setup the local WIFI connect in your hotel or at a friend and this way also get Internet connection to add youtube streams... on the go. I already asked myself if I can configure different wifi-access credentials for different wifi-SSIDs (but still did not search for it).

Perhaps not only GPIO but also RFID command to set "Access Point"-mode would be nice.

**Comment by MiczFlor** [comment]
I think it is an excellent idea, too. And started working on this:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/installscripts/stretch-install-default-HotspotAddOn.sh
This was during the time of the "one line install script" and I dropped it, because it got too complicated to add this to the mix.
My idea was - an that is the script I started with: if the Phoniebox does not find a known Wifi to connect to, it will go into Hotspot Mode.
With a switch, that might be even easier.
The main problem - and the switch idea (GPIO and/or RFID) solves that: not all wifi cards can do hotspot mode. 
So if you want to get a headstart, be my guest :) I join you guys later when reviewing the pull request :)

**Comment by Franzformator** [comment]
I also like the idea of connecting the box with different devices.

Instead of putting the phonipox into a AP a solution could also be to add additional wifis to the wifi list.
See: https://medium.com/@mikestreety/use-a-raspberry-pi-with-multiple-wifi-networks-2eda2d39fdd6

So you can put in for example your mobile hotspot.

**Comment by gizmo21** [comment]
> I also like the idea of connecting the box with different devices.
> 
> Instead of putting the phonipox into a AP a solution could also be to add additional wifis to the wifi list.
> See: https://medium.com/@mikestreety/use-a-raspberry-pi-with-multiple-wifi-networks-2eda2d39fdd6
> 
> So you can put in for example your mobile hotspot.

That's neat and would be the other way round and no hotspot mode on Pi wifi needed as your mobilephone is the "hotspot". Then phoniebox just tests through all perconfiured wifis on start in given order an last one is always your mobile hotspot on the phone.
This way you could also directly use the internet connection via SIM  at least for one or two youtube videos.

**Comment by gizmo21** [comment]
It works, but not as described in the link as it is for older raspberian versions. Here is the config for our version including mixed static/dhcp and priorities of ssids:

sudo nano /etc/dhcpcd.conf:
```
...
interface eth0
static ip_address=192.168.0.222/24
static routers=192.168.0.1
static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
static domain_search=

#wlan Bereich:  Standard -interface wlan0- aber da static und dhcp noetig nach SSID filtern
#interface wlan0

ssid fritzhome
static ip_address=192.168.0.223/24
static routers=192.168.0.1
static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
static domain_search=

ssid androidhotspot
# hier nichts eintragen reicht wohl fuer dhcp

```

Followed by entering the passwords vor the SSIDs and priorising if more than one SSID is present. That way I could get the PI to take the androidhotspot on boot and after shutting down hotspot it automagically connected to fritzhome.  id_string is not needed I think.

sudo nano /etc/wpa_supplicant/wpa_supplicant.conf
```
country=DE
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
        ssid="fritzhome"
        psk="passwordhere"
        id_str="home"
        priority=3
}

network={
        ssid="androidhotspot"
        psk="passwordhere"
        id_str="mobile"
        priority=5
}
```

One thing has to be know using a mobile hotspot (at least on andorid without rooting). The PI needs to be set to DHCP and it seems it always gets an IP in DNS range 192.168.42.1-254 or 192.168.43.1-254  (https://android.stackexchange.com/a/60408). To see which IP ur PI (pun intended) has, see your mobile hotspot device list on android. after that "Mobile SSH" on Andorid or browser interface works as usual.

**Comment by Franzformator** [comment]
Sounds perfect!

I think that you don't get your IP inside some WiFis should not be a problem. Also, that your IP is changing trough DHCP should be ok. 

My suggestion would be to use hostname to address the Phonibox on the network. In the moment this name is "raspberrypi".
Maybe we should change it to "phoniebox" or something else to prevent collisions.

See: https://blog.jongallant.com/2017/11/raspberrypi-change-hostname/

**Comment by MiczFlor** [comment]
Hi @Franzformator @gizmo21 
if this works and two people tried it, could you add this as a document to the docs section - which I would then merge and link from the manual? Then
a) we have some working hack in the docs
b) your contribution will be in the contributors hall of fame :)

**Comment by MiczFlor** [comment]
Should be possible. Parsing config files to extract data is just very annoying at times :) 

Typed with thumbs and good intentions.

**Comment by gizmo21** [comment]
Well perhaps a first simple approach would be to just enter new Hotspots via web-app by just taking the two values and fire&forget them into my addhotspot.sh

A later correction of password or SSID had to be done on cmdline though. 

Perhaps I'll try that. That said, I already thought of a userconfigurable separate /htdocs/userform.php (gitignored) but linked from navbar or settings menu. 
There you could configure a some own form-fields to take arguments for your own .sh scripts you would like to run from the webapp. 
I already did that with my CD-autorip2audiofolder-feature via abcde, but after a git pull I have to remerge that again.
Well I guess the userbase to use this userform.php feature is too small.

**Comment by MiczFlor** [comment]
I think the first step would be to integrate the scripts and create a pull request, so others can test it on the develop branch - including me :)
Also, I am curious to see that custom form fields beast you created. Why not share it and then we can see what to do with it.
If the script set for the hot spot works, we can work on the UI step by step. I think there is a good bunch of Phoniebox users who would know how to navigate their way around the scripts.
All the best, micz

**Comment by gizmo21** [comment]
Added manual update #229 for https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/225#issuecomment-424531924
