### ISSUE TITLE
No secondary audio outputs selectable in setup_configure_audio.sh

### ISSUE THREAD

**Issue by Lippsson** [MiczFlor/RPi-Jukebox-RFID#2256]
Regarding the documentaion, it should be possible to choose a primary and seconday audio output. But when i run the scipt, i only get the questions for primary audio output..

### What I did
I navigate to `cd ~/RPi-Jukebox-RFID/installation/components`
run the script with  `./setup_configure_audio.sh`

### What happened

after running the script it shows my audio outputs: 
*******************************************************************************
Available audio outputs
*******************************************************************************
 0:  alsa_output.platform-bcm2835_audio.analog-stereo
       Description: Built-in Audio Analog Stereo
       Module     : module-alsa-card.c
 1:  alsa_output.platform-soc_sound.stereo-fallback
       Description: Built-in Audio Stereo
       Module     : module-alsa-card.c
 2:  equalizer_for_alsa_output.platform-soc_sound.stereo-fallback
       Description: LADSPA Plugin C* Eq10X2 - Stereo 10-band equaliser on Built-in Audio Stereo
       Module     : module-ladspa-sink.c
       Sink       : alsa_output.platform-soc_sound.stereo-fallback
_____________________________________________________________________

Primary audio output (no bluetooth)? [0..2, default=0] 1

*** Primary audio output = alsa_output.platform-soc_sound.stereo-fallback
Enable an equalizer for the primary output? [y/N] y

*** Equalizer already configured for 'alsa_output.platform-soc_sound.stereo-fallback' with name
    'equalizer_for_alsa_output.platform-soc_sound.stereo-fallback'. Shifting entry point...

*******************************************************************************
Mono Speaker Box
*******************************************************************************

If you building a box with a single speaker, you probably want to
down-mix both stereo channels into mono signals.
Note: It does not matter if you connect you speaker to the left or right channel

Enable mono down mix for the primary output? [y/N] n

Summary:
jukebox_cfg_file        = /home/pi/RPi-Jukebox-RFID/shared/settings/jukebox.yaml
pulse_cfg_file          = /home/pi/.config/pulse/default.pa
treat_pulse_as_readonly = False
primary                 = equalizer_for_alsa_output.platform-soc_sound.stereo-fallback
secondary               = None
full_secondary_list     = False
toggle_on_connect       = False
add_equalizer           = False
add_monomixer           = False
disable PA's autoswitch = True
set_system_default      = True

*** Set system default sink to equalizer_for_alsa_output.platform-soc_sound.stereo-fallback

*** Writing /home/pi/.config/pulse/default.pa

*** Writing /home/pi/RPi-Jukebox-RFID/shared/settings/jukebox.yaml

*******************************************************************************
All done!
*******************************************************************************
Summary:
jukebox_cfg_file        = /home/pi/RPi-Jukebox-RFID/shared/settings/jukebox.yaml
pulse_cfg_file          = /home/pi/.config/pulse/default.pa
treat_pulse_as_readonly = False
primary                 = equalizer_for_alsa_output.platform-soc_sound.stereo-fallback
secondary               = None
full_secondary_list     = False
toggle_on_connect       = False
add_equalizer           = False
add_monomixer           = False
disable PA's autoswitch = True
set_system_default      = True

### I expected this to happen
I´m missing the question:

Secondary audio output (may bluetooth)? [0..2, default=1] 

### Base image and version

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
### Branch / Release

On branch future3/main
Your branch is up to date with 'origin/future3/main'.

### RaspberryPi version
`3 B+`
### RFID Reader
RC522
Barcode Reader (USB)

### Soundcard

MuPiHat

### Other notable hardware

OLED 1.3#

**Comment by AlvinSchiller** [comment]
Hi,

can you try running it with the parameter `-f`. Does it change anything?

**Comment by Lippsson** [comment]
Hi Alvin!
Thanks for your help. The suggested parameter`-f` gave me the option for the secondary output.
