### ISSUE TITLE
🐛 | Audio Interface name suggestions are incorrect (e.g. for OS desktop version)

### ISSUE THREAD

**Issue by AlvinSchiller** [MiczFlor/RPi-Jukebox-RFID#2274]
See https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2267#discussioncomment-8556789

1. The setup has the wrong  interface name as default setting
2. The suggestions are incorrect as they are for the user, but mpd.service runs as root.
The output differs for example if the "desktop" version of Raspberry Pi OS is installed. 

Fix:
`sudo amixer scontrols` has to be used and the first entry should be set as default interface name.

**Comment by s-martin** [comment]
Recommendation for lite emphasized in install description: https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/INSTALL
