### ISSUE TITLE
🐛 | no input possibility in search field 

### ISSUE THREAD

**Issue by Lippsson** [MiczFlor/RPi-Jukebox-RFID#2290]
### Version

3.5.2

### Branch

future3/main

### OS

Raspbian GNU/Linux 11 (bullseye)

### Pi model

3B+

### What happened?

![image](https://github.com/MiczFlor/RPi-Jukebox-RFID/assets/48052340/3681252e-2457-47c4-9c0e-9e6ed273dd62)
I cant add any text into serch field

**Comment by s-martin** [comment]
Could you add some logs after you tried to add some to the search field?

See here https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/main/documentation/builders/troubleshooting.md#the-short-answer

**Comment by Lippsson** [comment]
[errors.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14543316/errors.log)
[app.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14543317/app.log)

Sure.. Let me know if you need more information. Did it work for you?

**Comment by pabera** [comment]
This is on me. I know about the issue and it should be fixed! :-)

**Comment by Lippsson** [comment]
Great news! Can I update a file to make it to work, or do I need a complete reinstall?

**Comment by pabera** [comment]
Fixed

**Comment by pabera** [comment]
> Great news! Can I update a file to make it to work, or do I need a complete reinstall?

Should be possible. Will follow up with a path forward.

**Comment by pabera** [comment]
> Great news! Can I update a file to make it to work, or do I need a complete reinstall?

Here is a path forward -> https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2300/files
