### ISSUE TITLE
No Cover Refresh

### ISSUE THREAD

**Issue by ProfFutura** [MiczFlor/RPi-Jukebox-RFID#230]
I use the phono box with a 3.5 touchscreen. Unfortunately, when reading a new card, the cover display is not renewed.
Can you change that ?

**Comment by MiczFlor** [comment]
Hi @ProfFutura 
this should fix it: #240
please update to the latest master

**Comment by ProfFutura** [comment]
Vielen Dank, aber wie kann ich ein Update machen ? Kenne mich nicht so gut aus. Ich habe das Installationsscript versucht. Allerdings hat er danach meinen RFID Reader nicht mehr erkannt und die Installation ist fehlgeschlagen.

**Comment by MiczFlor** [comment]
Hallo @ProfFutura 
mit dem RFID reader ist gerade was im Argen. Wenn du das Script hast laufen lassen, dann schau mail hier rein, da habe ich unten angegeben, was man tun kann, um wieder auf eine ältere Version zurückzukommen.

**Comment by ProfFutura** [comment]
Hab soeben auf die aktuellste Version upgedatet. Leider immer noch kein Cover refresh. Ist der jetzt wieder verschwunden ?
