### ISSUE TITLE
🐛 | Failed to install 3.5.2 due to pyzmq issue

### ISSUE THREAD

**Issue by pabera** [MiczFlor/RPi-Jukebox-RFID#2344]
> Tried a fresh install of 3.5.2 stable today, but the pyzmq installation still failed. Tried to use different SD cards without success.
> Logs: [INSTALL-1713209396.log](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/14984054/INSTALL-1713209396.log)

_Originally posted by @IgorWalton in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/2271#issuecomment-2057748967_

**Comment by AlvinSchiller** [comment]
pyzmq 26.0.0 was released a few hours ago, and it seems there are incompatibilities with bullseye...

**Comment by AlvinSchiller** [comment]
I've created a bug report: https://github.com/zeromq/pyzmq/issues/1976
