### ISSUE TITLE
WebGUI Upload kein UNterodern

### ISSUE THREAD

**Issue by no-Legend** [MiczFlor/RPi-Jukebox-RFID#237]
Hi,

ich habe mir für den internen und den externen Speicher einen Ordner angelegt.
Nun wollte ich per WebInterface ein File Hochladen und hierfür eigene Ordern erstellen.
Leider scheint die WebGui hier aber keine Ordner anzulegen.
An den Rechten scheint es nicht zu legen.

Die Folder haben die gleichen rechte
drwxrwxr-x  4 pi www-data  4096 Sep 23 11:41 audiofolders
drwxrwxr-x 2 pi   www-data  4096 Sep 29 09:09 INTERNAL
drwxrwxr-x 2 pi   www-data 16384 Jan  1  1970 USB

Liegt es eventuell an der GUI selbst?

**Comment by MiczFlor** [comment]
HI @no-Legend 
das Web UI zeigt nur an was innerhalb des `audiofolders` liegt. War es das?

**Comment by no-Legend** [comment]
Hi @MiczFlor 

Leider nicht.

Bei mir in der webgut steht bei Upload files, e.g. New Folder.
Menn ich jetzt hier einen Ordner auswähle und dann  einen Namen eintippe , dabei ein file uploaden will bekomme ich immer die folgende Meldung, siehe Anhang.
Erlegt also nur im Haupt Ordner Ordner an aber nicht in Unterordner. 
Das ist wenn man mit verschiedenen Speicherquellen arbeiten will subotimal.

![bildschirmfoto 2018-10-07 um 10 33 47](https://user-images.githubusercontent.com/13560035/46580027-c9e62b80-ca1c-11e8-9f99-6bd24dd31469.png)
![bildschirmfoto 2018-10-07 um 10 33 16](https://user-images.githubusercontent.com/13560035/46580030-db2f3800-ca1c-11e8-907f-629606110025.png)

**Comment by MiczFlor** [comment]
Hi @no-Legend 

Welche Version hast du am Laufen? Weil der Abstand zwischen den beiden Form Fields gestaucht ist, denke ich es muss sich um eine ältere Version handeln (älter als 1.1.4).

ich glaube jetzt habe ich es verstanden, was du machen willst. Was ich gerade noch mal gemacht habe und es lief bei mir:

* Folder `testroot` im *root* angelegt (nicht mit dem Upload Form sondern dem darunter) - check
* Files in diesen Folder hochgeladen (mit der Upload Form) - check
* Folder `testchild`  im Filder `testroot` angelegt (nicht mit dem Upload Form sondern dem darunter) - check
* Files in diesen Folder `testroot/testchild` hochgeladen (mit der Upload Form) - check

Das ging alles. Was du machen willst ist:
* in der Upload Form
* neuen Folder anlegen
* Folder auswählen in den der neue Folder angelegt wird
* Files in den neuen Folder laden
... und das geht nicht, kann das sein?
(ich hatte die Upload Form auch so nicht konzipiert, ließe sich aber erweitern)

**Comment by no-Legend** [comment]
Nun hab ich die 1.1.7 drauf.
Hier scheint es mit den unter Ordner zu gehen.

Danke und Gruß Robert

**Comment by MiczFlor** [comment]
The code has moved on. I am closing this, assuming the later code solved it. :) All the best, micz
