### ISSUE TITLE
🐛 | Spotify Audiobook URI's not working

### ISSUE THREAD

**Issue by maarnix** [MiczFlor/RPi-Jukebox-RFID#2395]
### Version

2.7.0

### Branch

master

### OS

Raspbian GNU/Linux 11 (bullseye)

### Pi model

3B

### Hardware

Generic USB reader, USB speakers on 3.5MM audio out

### What happened?

I am able to play spotify tracks and playlists when using a URI that looks like: 
`spotify:track:[...]` 
or 
`spotify:playlist:[...]`

but when using an audiobook URI which have the format 
`spotify:show:[...]` 

these don't work

Log shows:

> phoniebox mopidy[3050]: INFO     [SpotifyBackend-7] mopidy_spotify.lookup Failed to lookup 'spotify:/show/6Jif9CF19KNTcPyIHS6JhK': Could not parse 'spotify:/show/6Jif9CF19KNTcPyIHS6JhK' as a Spotify URI

### More info

Not sure if it's related, but to get Mopidy to connect to Spotify I had to go here [https://mopidy.com/ext/spotify/](url) and then manually update the mopidy.conf file with the client_id and client_secret. The process done during the v2 setup only seemed to get me to the point where I could browse Spotify but not play any music

**Comment by s-martin** [comment]
Related to changed Spotify authentication

fixed in #2435
