### ISSUE TITLE
🐛 | bookworm: check for raspian not working

### ISSUE THREAD

**Issue by mittler-works** [MiczFlor/RPi-Jukebox-RFID#2402]
### Version

3.5.3

### Branch

future3/main

### OS

Raspberry Pi OS Bookworm Lite

### Pi model

Zero 2W

### What happened?

When running the installer script, it fails saying

```
ERROR: '<something>' found more than once in 'unknown'
```

Where `<something>` is not always the same thing.

I tracked it down, the problem is the check for Raspian [here](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/0ab75c1d28955e85c2069503b5a8428a69967d0d/installation/includes/02_helpers.sh#L79).

Newer releases of Raspberry Pi OS (bookworm) do not display `raspian` in `/etc/os-release` no more, but just `debian`. So there is no way to really tell if we are on Raspberry Pi OS.
I have found articles that propose to check the existence of `/etc/apt/sources.list.d/raspi.list` to determine if we are on Raspberry Pi OS. Although this is obviously not perfect either, it might be a better solution than consulting `/etc/os-release` for the future.

**Comment by mittler-works** [comment]
This only seems to affect bookworm 64bit. bookworm 32 bit shows raspian, as usual.

**Comment by s-martin** [comment]
At this time 64bit is not supported (there's also a check for it).

**Comment by mittler-works** [comment]
I know that, but I'm always interested in trying things out. ;-) 
Basically, bookworm/64bit is already running quite decent. It's just little things; but I think it's important to track them, even if the software is _currently_ not supporting it. That might save a bit of work for `future` later. :wink:

**Comment by s-martin** [comment]
> Basically, bookworm/64bit is already running quite decent. It's just little things; but I think it's important to track them, even if the software is _currently_ not supporting it. That might save a bit of work for `future` later. :wink: 

I agree. 

We also happily discuss possible changes for a working 64bit implementation, so if anybody opens a PR with necessary changes interested people could review it.
I know @alesrosina did also make it work (see #2313)

**Comment by alesrosina** [comment]
> > Basically, bookworm/64bit is already running quite decent. It's just little things; but I think it's important to track them, even if the software is _currently_ not supporting it. That might save a bit of work for `future` later. 😉
> 
> I agree.
> 
> We also happily discuss possible changes for a working 64bit implementation, so if anybody opens a PR with necessary changes interested people could review it. I know @alesrosina did also make it work (see #2313)

Yes, basically I just removed all checks in setup script. And then it's running as it should on 64bit.

I probably should take the time to make a PR, but probably not before autumn, since in summer time i prefer to be outside in my free time ;)

**Comment by mittler-works** [comment]
I can prepare a PR to lift the 64 bit restriction. It would only be a change in the `install-jukebox.sh` (removing [_check_os_type](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/main/installation/install-jukebox.sh#L89-L104)) and the thing with the Raspian check. There I would then use an or-condition in terms of "Either the os-release property ID contains raspian or the file /etc/apt/sources.list.d/raspi.list exists and contains corresponding raspian sources".

I've found no other issues with 64 bit. The GPIO Problems with kernel 6.6 upwards mentioned in the other issue are not specific to 64 bit, but also affect 32 bit, right? So that wouldn't be a show stopper for lifting 64 bit restriction, I think.

**Comment by alesrosina** [comment]
> I can prepare a PR to lift the 64 bit restriction. It would only be a change in the `install-jukebox.sh` (removing [_check_os_type](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/main/installation/install-jukebox.sh#L89-L104)) and the thing with the Raspian check. There I would then use an or-condition in terms of "Either the os-release property ID contains raspian or the file /etc/apt/sources.list.d/raspi.list exists and contains corresponding raspian sources".
> 
> I've found no other issues with 64 bit. The GPIO Problems with kernel 6.6 upwards mentioned in the other issue are not specific to 64 bit, but also affect 32 bit, right? So that wouldn't be a show stopper for lifting 64 bit restriction, I think.

Yes, from my experience that's correct :+1:

**Comment by harrydoddnoble** [comment]
@mittler-works did you manage to create a PR for this?

**Comment by mittler-works** [comment]
Sorry, that got lost in the daily grind. :wink: 
I have just created the PR. :wave:

**Comment by harrydoddnoble** [comment]
Thank you!

**Comment by mittler-works** [comment]
With pleasure :)

But one other thing I would like to discuss: the error message you get when you are not on Raspberry Pi OS is not meaningful at all (see OP of this issue).

The problem origins in [getting the boot and cmdline file paths](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/develop/installation/includes/02_helpers.sh#L91-L116). When the raspbian check (maybe it should be Raspberry Pi OS Check today? Thats also the reason why there is not always "raspbian" in `/etc/os-release`) returns `false`, then `_get_boot_file_path` just returns `unknown` instead of stopping the execution with a failure. So the routine continues as usual and if you want to write or do something with the returned path, it fails with curious error messages.

My proposal would be, that the function should write a meaningful error message to stderr and exit with non-zero exit code. I don't know if there is any kind of logger and/or exception handling implemented in the installer scripts. If not, it would be as easy as echoing to stderr and exit.

**Comment by s-martin** [comment]
> My proposal would be, that the function should write a meaningful error message to stderr and exit with non-zero exit code. I don't know if there is any kind of logger and/or exception handling implemented in the installer scripts. If not, it would be as easy as echoing to stderr and exit.

yes, we do.

please check here

https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/f2a1730a8df693350aef14aa6df6f563ffe6f786/installation/install-jukebox.sh#L42-L87

**Comment by s-martin** [comment]
Fixed in #2425
