### ISSUE TITLE
🐛 | Mopidy causes password resets

### ISSUE THREAD

**Issue by heili77** [MiczFlor/RPi-Jukebox-RFID#2423]
### Version

2.7.0

### Branch

Master

### OS

Bullseye 32 lite

### Pi model

4 B+

### What happened?

I use Spotify content.
Spotify resets my password when using Spotify content.

### More info

I installed in a new installed os

**Comment by heili77** [comment]
I installed in a fresh os installation

**Comment by s-martin** [comment]
Probably the same issue as in #2429 

Please follow up there.

**Comment by s-martin** [comment]
Fixed in #2435
