### ISSUE TITLE
Suggestion: Group service names

### ISSUE THREAD

**Issue by marcohorstmann** [MiczFlor/RPi-Jukebox-RFID#249]
Hi guys,

some minutes ago I was looking for a specific service. Would it be better that we use like a specific prefix for all services to look up the services better/faster?

Kind regards
Marco

**Comment by MiczFlor** [comment]
Good thinking. I will work on this for the next "major" release - because this will mean that it's not an easy `git pull` to update to the latest code base - it involves the install script to replace the systemd scripts.
