### ISSUE TITLE
File upload of more than 20 files load only the first 20 files

### ISSUE THREAD

**Issue by tunichgut** [MiczFlor/RPi-Jukebox-RFID#256]
Moin,
der Titel sagt es schon.

Upload über Chrome.
33 Dateien ausgewählt. Upload läuft bis 100%.  Ergebnis: Files were successfully uploaded.
Angekommen sind nur 20 Dateien.

Die restlichen 13 Datein können in einem zweiten Schritt problemlos nachgeladen werden.
Danach sind dann auch alle 33 Dateien im Ordner.

liebe Grüße
rené

**Comment by MiczFlor** [comment]
hi @tunichgut 
that is correct. The limit currently is set to 20 files at a time.

**Comment by kugel-** [comment]
Just came across this issue. The problem is that there is no indication that there is a limit. The GUI suggests all selected files (>20) have been uploaded
