### ISSUE TITLE
New float layout partly blocks play-button sooner in playlist

### ISSUE THREAD

**Issue by gizmo21** [MiczFlor/RPi-Jukebox-RFID#260]
This seems to be a cosmetic only problem on mobile devices, but I really have more trouble then before clicking on play-button with longer named files (and will hit more often with new subfolder feature). It still works but you have to press left outside the range you would usually press.

Still just a small annoyance, so no quickfix needed. Tried with CSS clear:both; but didn't find a good solution so that the break of filename-DIV in new line would only occur on very small viewport.
Could of course also be fixed by adding the a href="?playpos=x" on top to the filename (and perhaps style it a bit with nounderline:link ... ) to get a bigger area to click.

Version 1.0.0 seems to have more margin before overlapping still occurs. **Simulated** using FF in very small window for both 1.0.0 and 1.1.6:

![playbutton](https://user-images.githubusercontent.com/2779732/46910539-8a509f80-cf46-11e8-9b74-3850983acd0f.jpg)

**Comment by princemaxwell** [comment]
Should be solved in actual master branch.

**Comment by SpookyFishes** [comment]
In Version 2.1.8 with Spotify I have no problems on my 5" mobile phone. Pressing the play buttons works fine for me and the text starts on the right site of the button.

When I reduze the browser window to the minimum size everything is fine too

![grafik](https://user-images.githubusercontent.com/25422320/50552182-e09fc580-0c8d-11e9-9949-ba1ce067e38b.png)

**Comment by MiczFlor** [comment]
Hi @gizmo21 @SpookyFishes 
I made a new version using "tables" which seems to work. Please have a look and give feedback.
All the best, micz

**Comment by SpookyFishes** [comment]
I just updated to 1.1.9-rc7 and it looks fine on my mobile phone :-)

![grafik](https://user-images.githubusercontent.com/25422320/52502800-f1741d00-2be3-11e9-8eeb-16a769a37637.png)

**Comment by gizmo21** [comment]
Thx for new version, I still had no time checking as I'm still on 1.0 as it's the fastest and most reliable for me (or the endusers ;) ). Hope to upgrade an DEVcard soon™ .
