### ISSUE TITLE
Sound Knob

### ISSUE THREAD

**Issue by olsins** [MiczFlor/RPi-Jukebox-RFID#272]
Does anyone have experience adding a external sound Knob?
I was thinking about adding something like this https://www.amazon.de/gp/product/B06XHHSVN1/ref=ox_sc_saved_title_2?smid=A2N58YCCQNSUNR&psc=1

But I am not sure wether I can connect it to the GPIO description 

Volume Down
GPIO19 (PIN35) and GND (PIN39)

Volume Up
GPIO16 (PIN36) and GND (PIN34)

In this tutorial: https://tutorials-raspberrypi.de/raspberry-pi-ky040-drehregler-lautstaerkeregler/
the knob is connected like this.

GPIO 5 (Pin 29)	CLK
GPIO 6 (Pin 31)	DT
GPIO 13 (Pin 33)	SW
3.3V (Pin 1)	+
GND (Pin 6)	GND

Does anyone have an idea how to connect the knob in a way to work with the Jukebox?

**Comment by patman13** [comment]
See my solution in issue #267.

**Comment by MiczFlor** [comment]
Hi @olsins 
At the bottom of the README file
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/README.md
Is a link to the dial knob that @patman13 mentioned and a link to the files. Not yet implemented in the master branch. But all available in the thread.

**Comment by olsins** [comment]
Thanks a lot for the fast answers. I will order one and give it a try!
