### ISSUE TITLE
seekforw / seekback swiping cards

### ISSUE THREAD

**Issue by roland17387** [MiczFlor/RPi-Jukebox-RFID#282]
i have an "old" phoniebox and a new one
in the new one, there is the function to seek 15 seconds back/forward by swiping cards.
i updated the old phoniebox using git pull (version was then 1.1.7) but in /home/pi/RPi-Jukebox-RFID/settings/rfid_trigger_play.conf there was still no option to seek with rfid cards.
i added the missing lines manual and seeking with rfid-cards works now also in the old box.

perhaps you want to change the update so that this lines are added automatically?

**Comment by MiczFlor** [comment]
Hi @roland17387 
hm, trying to understand the issue. The seeking is in the trigger script:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/74de1965ef6cca99e36d779ff489c02292f6904b/scripts/rfid_trigger_play.sh#L180
And it is in the sample config file:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/74de1965ef6cca99e36d779ff489c02292f6904b/settings/rfid_trigger_play.conf.sample#L31
