### ISSUE TITLE
AirPlay support using shairport

### ISSUE THREAD

**Issue by Alwiz79** [MiczFlor/RPi-Jukebox-RFID#289]
I updated my installation of phoniebox with AIRPLAY compability!
Just want to share my experience here.
I followed [this](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md#build-and-install) step by step installation guide, on top of the running phoniebox.

Everything is just working fine and I can see no problems...
I can now swipe cards to use phoniebox, and I can also send music from my iPhone to the Rpi.
The two options will not stop each other, which means:
If Phoniebox is running and you send Airplay music to the Rpi it will play both at the same time,  and vice versa.

Anyhow, to me this is a restriction, that I can live with, it just requires a little discipline :-)

**Comment by holly79** [comment]
You can add a command to stop mpd to /etc/shairport-sync.conf. See sessioncontrol in config file

e.g.
run_this_before_play_begins = "/usr/bin/mpc stop"
run_this_after_play_ends = "/usr/bin/mpc play"
