### ISSUE TITLE
m4b upload not possible by webgui

### ISSUE THREAD

**Issue by no-Legend** [MiczFlor/RPi-Jukebox-RFID#291]
Hi,

es scheint nun nicht mehr möglich sein zu sein m4b Dateien hochzuladen.
Bis vor kurzem konnte ich diesen Dateityp noch auswählen und hochladen.

Gruß Robert

**Comment by pgx3d** [comment]
Hallo Robert

Ich konnte "alle Dateien" anstatt Audiodateien auswählen, dann wurden auch m4b angezeigt. Diese konnte ich so auswählen und hochladen.

Gruss
Manuel

**Comment by no-Legend** [comment]
@pgx3d 
Benutzt du Windows?
Ich arbeite auf OSX.

hier mal zwei Bilder.
Eine Datei als m4b nicht auswählbar, da grau.
Sobald mp3 kein Problem.
![bildschirmfoto 2018-10-30 um 11 46 48](https://user-images.githubusercontent.com/13560035/47713093-b607a100-dc39-11e8-85e4-56bfe73fdfe7.png)
![bildschirmfoto 2018-10-30 um 11 46 27](https://user-images.githubusercontent.com/13560035/47713097-b869fb00-dc39-11e8-8784-bc9c445ac063.png)

Gruß Robert

**Comment by pgx3d** [comment]
Nope, Linux

**Comment by MiczFlor** [comment]
Hi @no-Legend 
das ist echt weird. Ich habe keinen Filter beim Upload welche Files unterstützt werden und welche nicht... Hat OSX schon client-seitig Upload Filter eingebaut ? :)

**Comment by no-Legend** [comment]
@MiczFlor 
Ich verstehe es auch nicht,
Hatte bis zum Update auf 1.1.7 das problem nicht.
im Firefox auf OSX gibt es das problem nicht. scheint wohl irgendwie an safari zu liegen.
Es scheint heute ein Update für Safari veröffentlich worden zu sein.

**Comment by no-Legend** [comment]
@MiczFlor 
auch nach dem update mit safari kein m4b upload möglich

**Comment by no-Legend** [comment]
@MiczFlor mit OSX und dem Firefox geht es. Das mit dem Safari versteh ich nicht.
Bis zum update auf 1.1.7 ging es ohne Probleme.
Ganz komisch.

Hab auch einen anderen User Probiert.
Hier ist genau das gleiche Problem.
