### ISSUE TITLE
Shuffle & Resume

### ISSUE THREAD

**Issue by princemaxwell** [MiczFlor/RPi-Jukebox-RFID#293]
@MiczFlor 
I have an issue in the WebUI.
When i press shuffle, shuffle turns ON.
When i then press resume, resume turns ON, but shuffle turns OFF.
When i then press shuffle, shuffle turns ON and resume stays ON, too
When i then press resume, both turn OFF.

I am very curious and i didn't find the reason :-/

**Comment by MiczFlor** [comment]
I need to look into this. Strange.

**Comment by MiczFlor** [comment]
Hi @princemaxwell 
I close this, ok?
