### ISSUE TITLE
python3-gpiozero will not be installed with default script

### ISSUE THREAD

**Issue by marcohorstmann** [MiczFlor/RPi-Jukebox-RFID#294]
Hi,
I installed a second PI with install script und it seems that here is the package "python3-gpiozero" is not installed via script. After manually installing it I was able to use my GPIO Ports.

https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/8ee51788bcff181678df0b9e874bcb33823bfcd4/scripts/installscripts/stretch-install-default.sh#L390

**Comment by MiczFlor** [comment]
Hi @marcohorstmann 
how did you install it? Which repo? pip? apt-get?

**Comment by marcohorstmann** [comment]
Hi @MiczFlor
just apt-get install python3-gpiozero

**Comment by MiczFlor** [comment]
Hi @marcohorstmann 
I added this in the latest release:
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/323
