### ISSUE TITLE
RFID cards Control – Seek ahead and back like in WebApp

### ISSUE THREAD

**Issue by harryliebteuch** [MiczFlor/RPi-Jukebox-RFID#300]
would be great you add a new command for fast-forward, or seek ahead and back (more then 15 seconds) in the RFID Controll Script

**Comment by MiczFlor** [comment]
This is working, I believe. At least it did once and is still in the code :)
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/415826956f09ebe369e3aab3d73e5dd8e6d8a713/settings/rfid_trigger_play.conf.sample#L32
