### ISSUE TITLE
Max98357a Volume control

### ISSUE THREAD

**Issue by foonky** [MiczFlor/RPi-Jukebox-RFID#308]
Hi,

I try to Build a Jukebox with the mentioned Mono amp.
But it is always at 100% Volume.

In a Volumio Forum they Talk about Software Mixer.

Has someone got. ist working

The MAx98357 doesnt support Hardware volume control so you must set Vollumio to: 
Mixertype=software
MixercontrolName=software volume control

**Comment by Ardios** [comment]
@foonky 

try this:

sudo nano /etc/mpd.conf

under audio_output uncomment the mixertype line and change "hardware" to "software"

then save and reboot

**Comment by MiczFlor** [comment]
Hi @foonky,
Assuming your silence means „thanks, working now“, I‘ll close this issue? :)

**Comment by foonky** [comment]
Actually i received a new one yesterday.The old one was broken. It is working Fine now
