### ISSUE TITLE
Can't choose subfolders from symlink to USB stick 

### ISSUE THREAD

**Issue by varac** [MiczFlor/RPi-Jukebox-RFID#314]
I am using an USB stick and have symlinked linked folders on it to `~/RPi-Jukebox-RFID/shared/audiofolders` like this:

```
$ mount | grep Media
/dev/sda1 on /home/pi/Media type ext4 (rw,noatime,data=ordered)

pi@musicbox:~/RPi-Jukebox-RFID/shared/audiofolders $ ls -al
total 24
drwxrwxr-x 5 pi   www-data 4096 Nov  5 21:14 .
drwxrwxr-x 4 pi   www-data 4096 Nov  4 22:49 ..
lrwxrwxrwx 1 pi   pi         30 Nov  4 22:03 Audiobooks -> /home/pi/Media/Audiobooks
drwxr-xr-x 3 pi   pi       4096 Nov  5 21:14 Compilations
-rwxrwxrwx 1 root root       98 Nov  4 10:32 folder.conf
lrwxrwxrwx 1 pi   pi         26 Nov  4 22:02 Music -> /home/pi/Media/Music/
```

In the home screen I can browse all subfolders of i.e. Audiobooks, see this screenshot where it shows correctly 3 subfolders:

![screenshot from 2018-11-05 22-55-05](https://user-images.githubusercontent.com/488213/48030127-5c7b0700-e150-11e8-87b6-88afb9d6bfd5.png)

But I can't choose any subfolder below Audiofiles in `/cardRegisterNew.php`:

![screenshot from 2018-11-05 22-56-36](https://user-images.githubusercontent.com/488213/48030113-4ff6ae80-e150-11e8-9f7f-1ad3e0b501e9.png)

`Compilations` is a real folder beneath `~/RPi-Jukebox-RFID/shared/audiofolders` and I can select subfolders from the card register page though.

`www-data` can read all subdirs so I think this is not a permission problem:

```
root@musicbox:~# sudo -u www-data ls -al /home/pi/Media/Audiobooks/
total 20
drwxrwxr-x  5 pi www-data 4096 Jun 19 15:37 .
drwxrwxr-x  4 pi www-data 4096 Jun 19 12:42 ..
drwxrwxr-x  3 pi www-data 4096 Jun 19 14:54 Janosch
...
```

Any idea how to register a new card to symlink subfolders ?

I'm using the `Version-1.1.5-dynamicRFIDreader` branch.

**Comment by varac** [comment]
Weird - I symlinked the whole `audiofolders` dir to the mountpoint of the usb stick (`/home/pi/Media`) and with this it works.

**Comment by MiczFlor** [comment]
Might be a access rights issue. Following symlinks via http daemon often requires that the parent also has access rights granted for the webserver.

**Comment by varac** [comment]
Ok, closing for now.
