### ISSUE TITLE
Remove placeholder file from audiofolders and shortcuts

### ISSUE THREAD

**Issue by varac** [MiczFlor/RPi-Jukebox-RFID#319]
I removed `audiofolders/` and `shortcuts/` and replaced them with symlinks to a usb drive.
Now they show up as deleted in my git status:

        deleted:    shared/audiofolders/placeholder
        deleted:    shared/shortcuts/placeholder

I guess the `placeholder` files are just there so you can checkin both directories into git. Can we removed them ?

**Comment by MiczFlor** [comment]
HI @varac 
that is correct. They are only there so that the empty folders can be part of the github repo

**Comment by varac** [comment]
My proposal was to remove them (and not check in `audiofolders/` and `shortcuts/` into git), so symlinking doesn't show up as git changes.
And maybe create them dynamically from the install script.
