### ISSUE TITLE
Mopidy: failed to add some tracks

### ISSUE THREAD

**Issue by MTam86** [MiczFlor/RPi-Jukebox-RFID#326]
I have created a new installation today. But unfortunately I get an error message immediately when I try to play something on Spotify.
**Mopidy failed to add some tracks**

Server: Connect
Spotify: Authorized

Thanks and Greetings
Malte

**Comment by tomraithel** [comment]
I have the same problem. I followed these steps:
1. Launch phoniebox webapp
2. Go to "spotify" page
3. Search for song and hit "play"
4. Getting "Mopidy failed to add some tracks"  as a result

**Comment by princemaxwell** [comment]
From here we cannot support the way over the "spotify" button. This button is only to take a look into the web interface and if the server is running fine.
Phoniebox controls spotify and local files on a different way.
