### ISSUE TITLE
Volume Control for Startsound

### ISSUE THREAD

**Issue by marcOSS040** [MiczFlor/RPi-Jukebox-RFID#328]
Hi,

in my configuration I use a hifiberry miniamp as soundcard, wich works fine for playback of audio.

Just the initial startup sound ( /home/pi/RPi-Jukebox-RFID/shared/startupsound.mp3) is very loud and I would like to get that a bit quieter. I tried to set the volume in the alsamixer, but this only works when the box is fully bootet, not for the startsound.

Does anybody know how to set the volume in mpg123/for the startup sound?

Thanks, Marco

**Comment by marcohorstmann** [comment]
We have for this already an issue #250
