### ISSUE TITLE
Ground loop isolator to quiet CPU crackle in speaker

### ISSUE THREAD

**Issue by rebhuhnweg** [MiczFlor/RPi-Jukebox-RFID#341]
Hi,

I have the problem that I hear the CPU activity in the boxes as "quiet" rattling and crackling. Clearly recognizable when CPU activity is. The electrical structure of my box:

1 USB power supply. At the USB cable I soldered the power of the PI as well as the power for the small boxes (those from the shopping list of the project). The RFID reader gets its power from the Pi's USB port. (I had the boxes originally also at the Pi thought then however that I get it away in such a way).

The problem is completely gone when I connect the boxes via a completely separate USB power supply, but that's no solution :(

Do you know the problem, and does anyone have an idea ?

Greeting from northern Germany

Ronnie

**Comment by MiczFlor** [comment]
Hi @rebhuhnweg
not just CPU but also wifi activity on the same ssid in general :) to my knowledge this can only be fixed with a soundcard like the hifiberry listed in the readme file. 
I file it under „21st century vinyl sound“ and lived with it for over a year now. :)
All the best, micz

**Comment by deMerl** [comment]
Hi @rebhuhnweg 
I had the same issue. Noises were so loud you couldn´t use the Box. Solved this issue with a "Ground Loop Isolator" like this one: [Entstörfilter](https://www.amazon.de/gp/product/B01LX0H29W/ref=oh_aui_detailpage_o09_s00?ie=UTF8&psc=1). Noises are gone completely.
Could maybe also solve it with a USB Soundcard but the sound of the PI 3B+ audio jack is okay for me.
Greez, deMerl

**Comment by lonjame** [comment]
The Ground Loop Isolator solved the issue for me

**Comment by HenningWesterkamp** [comment]
If you are using a seperate Amplifier on the same powersource as the Pie this is a usual problem. In my case there was noise in the speaker even if the Audio cable between the pi and the amp was not installed.

Try using seperate powersources for the amp and the pi.

**Comment by marcohorstmann** [comment]
For PAM8403 amp based setups I created pull request #306

**Comment by tobiasnix** [comment]
The Ground Loop Isolator solved the issue for me too

**Comment by MiczFlor** [comment]
I added this to the "special hardware" section on the front page, please have a little check if this is accurate:
https://github.com/MiczFlor/RPi-Jukebox-RFID#special-hardware

**Comment by orangecoding** [comment]
Just fyi, the link to the "Entstörungsfilter" doesn't work anymore.

**Comment by MiczFlor** [comment]
> Just fyi, the link to the "Entstörungsfilter" doesn't work anymore.

Ok, why is that?

**Comment by dekiesel** [comment]
> > Just fyi, the link to the "Entstörungsfilter" doesn't work anymore.
> 
> Ok, why is that?

It seems it got removed from amazon.de

**Comment by Timsche2210** [comment]
can someone share a new Ground Loop Isolator / Entstörfilter Audio.
I have a crackle in the first 2 seconds if I start a track with a RFID tag...
