### ISSUE TITLE
Hifiberry Miniamp + Mopidy/alsasink issue

### ISSUE THREAD

**Issue by swyer222** [MiczFlor/RPi-Jukebox-RFID#353]
Hi all,

anyone else experiencing issues with Hifiberry devices? 

I'm having trouble with the Miniamp. Had this up and running with an earlier build, but stopped working as of recently. Tried setting the device up again with the latest RC, but no luck getting this running properly again. 

Issue: 
Bootup > OK
Boot sound > OK
speaker-test -D hifiberry -c 2 > OK until some time in the scripts, then noise just stops

Can't pinpoint the exact moment in the log, but think it stops sometime when Mopidy start or alsasink is set to aduio output. 

Appreciate any help pinpointing or fixing the issue. 

Thanks

**Comment by cubertt** [comment]
Deaktivate the gpio script.

It was not enough to disable it via webapp, in my case i needed to run:

sudo systemctl disable phoniebox-gpio-buttons

**Comment by swyer222** [comment]
Thanks

**Comment by internetfan420** [comment]
i had the same problem but i still need use the gpio pins because of the expander board i have and want to use buttons
