### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by internetfan420** [MiczFlor/RPi-Jukebox-RFID#360]
How would I go about using SoundCloud streams. Would it be a Mopidy extension?
If so how would I go about it?

Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MiczFlor** [comment]
Hi @internetfan420 
currently Soundcloud is not supported in Phoniebox. There seems to be a package for mopidy:
https://github.com/mopidy/mopidy-soundcloud
If you want, please start fiddling with the code and contribute requests to the `develop` branch.
All the best, micz
