### ISSUE TITLE
Play Button sometimes does not work

### ISSUE THREAD

**Issue by olsins** [MiczFlor/RPi-Jukebox-RFID#362]
I have an issue with the play button. 
Sometimes when pressing it, it does not affect the playing or when I press long - it stops playing and when I release it plays again. I use the following buttons:https://www.amazon.de/gp/product/B06XCSB9N3/ref=ox_sc_saved_title_3?smid=A3QI278WQRYOPR&psc=1

what confuses me - with next and last song it all works fine. 
The core of the problem seems to be, that if I push the button the connection switches slightly between on and of - (the same with a new button). Is there anyway to make a workaround by configure the GPIOs so that the play button only works, if its pressed for lets say 0.2 seconds?

something like:

halt = Button(3, hold_time=0.2)

halt.when_held = def_halt

does not work ...
Has anyone an idea?

**Comment by marcohorstmann** [comment]
Hi, can you post please your used version of gpio-buttons.py? Because this project gives only a sample file and everybody is customizing it, you need to post it to get qualified answered. ;-)
