### ISSUE TITLE
Music Play GPIO put PAM8403 Pin12 down or LED

### ISSUE THREAD

**Issue by FFKite** [MiczFlor/RPi-Jukebox-RFID#366]
Hey,

I would like if Music Play, a GPIO pin is activated so that the PAM8403 (12 pin) starts. if Music stop the GPIO pin is off. Can I somehow add that in gpi-buttons.py? It would also be usable for an LED that lights up at play.

FFkite

**Comment by MiczFlor** [comment]
Hi @FFKite 
thanks for the contribution. Once you figured this out (with the help of the community), please add your knowledge to the manual wiki. For example on this page:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Hardware-Pinout-Overview
Some questions repeat themselves, get closed and lost. It would be great if you contributed.
All the best, micz
