### ISSUE TITLE
RFID Reader funktioniert nicht 

### ISSUE THREAD

**Issue by aeskimo** [MiczFlor/RPi-Jukebox-RFID#368]
Hi,

ich hab die aktuellste Version installiert, aber ich bekomme meinen "KKMOON RFID reader" nicht zum laufen.

Im Terminal wird RFID Nummer angezeigt wenn ich eine Karte über den Reader halte.

Die Datei `latestID.txt` wird aber nicht geschrieben.

Der Reader wird wie folgt gelistet
```
python RegisterDevice.py
Choose the reader from list
0 HID 413d:2107
1 HID 413d:2107
```

mit dem `ls -la /dev/input/by-id/`
taucht er auch auf, als Eingabegerät aber auf.

Bei [Amazon](https://www.amazon.de/gp/product/B011XI2DE8/ref=ox_sc_saved_title_4?smid=A1M95QGHJURNWV&psc=1) heisst es zudem

> Prozess konfigurieren
> 1. Öffnen Sie eine bearbeitbare PC-Software wie Excel, Word oder Notepad usw.
> 
> 2. Stecken Sie den Leser ein und stecken Sie ihn innerhalb einer Sekunde aus.
> 
> 3. Stecken Sie den Leser wieder ein und stecken Sie ihn innerhalb einer Sekunde wieder aus.
> 
> 4. Stecken Sie den Leser ein.
> 
> 5. Jetzt leuchtet die LED des Lesegeräts grün und es ertönt 3 mal ein Piepton. Auf dem PC-Fenster werden dann nacheinander verschiedene Formate angezeigt, insgesamt 28 Formate, und es wird in einer Schleife angezeigt.
> 
> 6. Wenn das erwartete Format angezeigt wird, schließen Sie den Reader aus, die Einstellung ist abgeschlossen und das neue Format funktioniert beim nächsten normalen Plug-In.

wobei es auch auf dem Raspberry funktioniert. Benötigt es ein entsprechendes Format?

**Comment by MiczFlor** [comment]
Hi @aeskimo 
Für den Reader gibt es einen fix von @cgnmause which I haven't committed because I can not test it. Have a look here and possibly @cgnmause could assist you here?
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/327

**Comment by cgnmause** [comment]
Hi,
sorry. I was kind of busy during the weekend. 
@aeskimo: Kannst Du mal bitte versuchen meinen Fix bei Dir einzuspielen. Dann müsste es gehen. Wenn nicht melde Dich bitte nochmal.

@luzbox: Which user do you use for your changes and which file rights are currently set for reader.py?

**Comment by luzbox** [comment]
Hi again
Konnte unterdessen das file editieren, und nachdem ich das Format des reader nochmals neu konfiguriert habe (er hat Erkennungsmodus mit und ohne ENTER, hab ihn am Mac umkonfiguriert) krieg ich jetzt die ID in der Weboberfläche angezeigt - und der Rest klappt auch. Ich hab den "KKmoon IC Kartenlesegerät Berührungslose 14443A Kartenleser". 
Danke @cgnmause !

**Comment by cgnmause** [comment]
Okay...mit welchem User bist Du eingeloggt?
Dann schau mal nach, wem die Datei reader.py gehört:
Dafür gib mal folgendes ein:
```bash
ls -l reader.py
-rw-r--r-- 1 pi pi 1548 Nov 10 14:57 Reader.py
```
Du sagst Du bist Anfänger. Dann also eine Kurze Erklärung. 

Erster Block('-rw-r--r--'): 
Im ersten Block stehen die Dateirechte für den Besitzer, die Gruppe und für alle anderen drin.
- Der erste Bindestrich würde Dir im Falle eines Directories ein 'd' präsentieren. 
- Die nächsten drei Zeichen 'rw-' bedeuten, dass der Besitzer dieser Datei Lese-('r') und Schreibrechte('w') besitzen. 
- die nächsten drei Zeichen ('r--') bedeuten, dass die Gruppe nur Leserechte besitzt.
- die letzen drei Zeichen stehen für die Dateirechte aller anderen Benutzer

Zweiter Block('1'): 
Für uns unwichtig.

Dritter Block('pi'):
Dem Benutzer mit diesem Namen gehört die Datei. Sollte der User, mit dem Du Dich auf das System eingeloggt hast nicht mit diesem Übereinstimmen dann hast Du nicht die entsprechenden Rechte.

Vierter Block('pi'):
Hierbei handelt es sich um die Gruppe. 

Eigentlich können wir hier mit der Erklärung abbrechen. Sollte Dein Loginname nicht mit dem Besitzer der Datei übereinstimmen, dann hast Du keine Schreibrechte auf diese Datei. 
In meinem obigen Beispiel müßtest Du dann erst User 'pi' werden um die Datei Reader.py zu ändern:

```bash
su - pi
````
Ich hoffe Du kommst jetzt weiter. Wenn nicht...frag einfach weiter.

Gruß
Christoph

**Comment by cgnmause** [comment]
@luzbox: Gerade erst Deine letzte Nachricht gesehen. Freud mich, dass es funktioniert. Viel Spass noch weiterhin. 👍

**Comment by d1ck3r** [comment]
Hi @luzbox,

ich  habe das gleiche Problem wie Du:

Choose the reader from list
0 C-Media Electronics Inc.       USB PnP Sound Device
1 CHERRY CHERRY KEYBOARD
2 CHERRY CHERRY KEYBOARD
3 HID 413d:2107
4 HID 413d:2107
5 Logitech USB Optical Mouse
Device Number: 

Wie genau hast Du das gelöst?
Ich habe den Inhalt der Datei Reader.py ausgetauscht, aber ich weiß nicht wie 
ich danach verfahren soll.
Freue mich sehr über Hinweise.

Grüße,

Eduard

**Comment by cgnmause** [comment]
Sehr guter Hinweis @luzbox.
Hast Du dem Piepser den Gar ausgemacht? Ich schwanke noch :-).

Viele Grüße
Christoph

**Comment by luzbox** [comment]
hoi @cgnmause 
Ja, mit dem Schraubenzieher abgehebelt - ich bereue nichts. 
Ist alles in der Kiste drin, läuft, jetzt nur noch bisschen Schönheitspflege.

**Comment by cgnmause** [comment]
Moin @luzbox,
:-D aber Du weißt, dass unter den Gummipuffern kleine Kreuzschlitzschrauben sind?

**Comment by luzbox** [comment]
hei @cgnmause mit dem Gehäuse war ich nett, den Pieper auf dem board hab ich weggehebelt (mit einem mini-Schraubenzieher)

**Comment by cgnmause** [comment]
@luzbox: Dann ist es ja gut.
 

Gesendet: Montag, 17. Dezember 2018 um 18:35 Uhr
Von: luzbox <notifications@github.com>
An: MiczFlor/RPi-Jukebox-RFID <RPi-Jukebox-RFID@noreply.github.com>
Cc: cgnmause <c.mause@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [MiczFlor/RPi-Jukebox-RFID] RFID Reader funktioniert nicht (#368)


hei @cgnmause mit dem Gehäuse war ich nett, den Pieper auf dem board hab ich weggehebelt (mit einem mini-Schraubenzieher)

**Comment by aeskimo** [comment]
> Hi @aeskimo
> Für den Reader gibt es einen fix von @cgnmause which I haven't committed because I can not test it. Have a look here and possibly @cgnmause could assist you here?
> #327

Hi @MiczFlor
Leider bin ich erst jetzt wieder dazu gekommen mit dem Projekt zu widmen.
Frage wie kann ich die alternative "reader.py" über ssh einspielen.
Danke für eure Hilfe.

**Comment by cgnmause** [comment]
@aeskimo: Entweder du kopierst den Inhalt der Datei, loggst Dich auf den Raspberry ein, öffnest einen Editor und fügst das kopierte ein und speicherst das, oder du kopierst das per scp.

**Comment by aeskimo** [comment]
Hab nun die „Reader.py“ https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/6e7ec83c52b1470aa40d6ac1e66c0e472bf1b153/scripts/Reader.py
verwendet. Nun funktioniert es

**Comment by MiczFlor** [comment]
@aeskimo @cgnmause @luzbox 
Ich merge jetzt den Peader.py von @cgnmause mit master. Wenn ihr Zeit findet, würde ich mich über Testen freuen - nicht dass am zweiten Weihnachtsfeiertag die issue threads brennen :)
