### ISSUE TITLE
GPIO Buttons reagieren nicht

### ISSUE THREAD

**Issue by alienfactor** [MiczFlor/RPi-Jukebox-RFID#375]
Moin,

ich hab die Buttons entsprechend der Anleitung angeschlossen (ohne Pullup-Widerstände)
Das gpio-buttons.py Script habe ich 1:1 übernommen und nicht modifiziert.

Die Buttons funktionieren jedoch nur sporadisch/nach mehrfachen tasten. In der UI sehe ich, dass die Buttons ständig wieder deaktiviert werden. Ein manuelles aktivieren bringt aber auch nicht mäßigen und maximal temporären Erfolg.
 
Vielen Dank

**Comment by alienfactor** [comment]
.. fehlerhafte gpio-buttons.py verwendet. Nach Korrektur funktioniert es.

**Comment by MiczFlor** [comment]
>.. fehlerhafte gpio-buttons.py verwendet. Nach Korrektur funktioniert es.

@alienfactor kannst du noch mal ganz kurz hier schreiben was fehlerhaft war? Dann würde ich das a) korrigieren und b) im manual dokumentieren. Für die nächsten sozusagen. Danke und schlaf dich aus (hoffe ich) :)
Beste Grüße, Micz 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alienfactor** [comment]
@MiczFlor Hallo und danke für deine tolle Missionsarbeit hier! :)
Der Fehler ist durch mein eigenes Verschulden aufgetreten. Ich bastelte an der Datei herum um #62 umzusetzen, danach ging nix mehr. Ich habe also mit "Korrektur" nur den Ausgangszustand wiederhergestellt. Sorry für die unklare Formulierung.

Vielleicht darf ich aber dein Projekt-Wissen dennoch kurz in Anspruch nehmen und etwas zu #62 fragen:
Ich habe den Messpunkt (B) nach außen geführt und mit einem Widerstandund mit GPIO6 verbunden. Tut sich leider gar nix. In der Anleitung steht etwas von "the Pin has to be pulled down".. Vermutlich muss ich noch irgendwo gegen GND schalten? Hast du eine Erklärung?

Vielen Dank!
