### ISSUE TITLE
Please do not automatically activate GPIO Buttons - breaks Phat Beat DAC

### ISSUE THREAD

**Issue by ShaXiaomi** [MiczFlor/RPi-Jukebox-RFID#384]
Hello,

I am using the Phat Beat DAC with Phoniebox.
The sample GPIO config which is copied by the installer breaks the Phat Beat DAC.
See Phat Beat GPIO config: https://de.pinout.xyz/pinout/phat_beat

It would be more preferable to make the GPIO stuff optional.

thx
Daniel

**Comment by dtrv** [comment]
Good to know. I plan to use PhatBeat with my next Box. Thanks for reporting ...

**Comment by MiczFlor** [comment]
Hi @ShaXiaomi @dtrv could you add this to the wiki? Im troubleshooting? Or under soundcards?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinclausen2** [comment]
Hi @ShaXiaomi , could you please add the Phat Beat DAC pinout in the [wiki?](https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Hardware-Pinout-Overview#hardware-with-fixed-pin-assignment). This will help the community in the future to prevent conflicting GPIO assignments.

**Comment by ShaXiaomi** [comment]
Hi, I already added something here: https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Troubleshooting-FAQ

But not yet the pin out. Will do it when I am not on mobile.
