### ISSUE TITLE
GPIOs - where have gio-buttons.py and/or gpio.py gone?

### ISSUE THREAD

**Issue by c-m0s** [MiczFlor/RPi-Jukebox-RFID#388]
Hi all,

I like this project very much, thanks a lot @MiczFlor for creating and maintaining it!

I have my first prototype working and am trying to implement the GPIOs now.
Can someone tell me where the scrips implementing the GIO-Buttons has gone? I can’t find them in the repo anymore. I am trying to trail the development over the corresponding issues, but I seem to have lost track now.

Any hint very much appreciated!
(There is not much time for finishing the box...)

Thanks a lot!

**Comment by MiczFlor** [comment]
hi @c-m0s 
thumbs up to the prototype :) the original file with some comments still lives here:
* [misc/sampleconfigs/gpio-buttons.py.sample](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/misc/sampleconfigs/gpio-buttons.py.sample)

There are more files now and they all start with `gpio-` in the name. Please also have a look at the wiki here:
* https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Hardware-Pinout-Overview
* https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Using-GPIO-hardware-buttons
