### ISSUE TITLE
Housing for the radio

### ISSUE THREAD

**Issue by d7071** [MiczFlor/RPi-Jukebox-RFID#389]
not really an issue but maybe some are interested in my current development of the 3D printed housing.
[https://www.thingiverse.com/thing:3290093](url)
My 2 year old daughter uses it daily. The PLA housing even resisted some bad drops!

**Comment by tobiasnix** [comment]
That does look nice. Can you add a real life photo with mounted equipment?

**Comment by MiczFlor** [comment]
Hi @d7071 
Me, too: I would like to see it in real life. Looks neat!

**Comment by dvalob** [comment]
link is broken :(

**Comment by 1704eu** [comment]
Seems to be this one.... https://www.thingiverse.com/thing:3290093

If the link doesn't work search for the ID on thingiverse...
