### ISSUE TITLE
Raspberry Pi Zero too slow for Spotify edition (while using bluetooth speaker)

### ISSUE THREAD

**Issue by ShaXiaomi** [MiczFlor/RPi-Jukebox-RFID#398]
Hi,

i tried to use the Spotify version which is using Mopidy as playback sw on a Raspberry Pi Zero.
I now cancled the project because Mopidy takes long to load and while using a bluetooth speaker the bluetooth stream is choppy.
Does anyone know if it is Mopidy being so damn slow or the bluetooth connection?
I took a look at the CPU usage with top and often ist was higher than 50%.

I suspect Mopidy being to heavy for the Pi Zero, especially while using BT.

Could it be a solution the let the local playback rely on mpd instead of mopidy?
So Mopidy could be used only optional for spotify if really needed.

In my project I had to switch from the Mopidy/spotify version to the standard Phoniebox version. The Spotify version was not really usable because of long times for the set up to be ready after booting and bc of the chopped bt audio stream.

Did anyone encounter these issues also?
Daniel

**Comment by zehbart** [comment]
Hi ShaXiaomi,

have a look at this one:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/287
