### ISSUE TITLE
Suggestion: Add support for different musicplayer software (squeezeplayer + LMS) /OS (picoreplayer)  

### ISSUE THREAD

**Issue by cubertt** [MiczFlor/RPi-Jukebox-RFID#400]
Dear Ladies and Gentlemen,

First: Thanks at all and especially @MiczFlor for this nice peace of software, which my kids and me love to use!

I want to make a suggestion:

Switch the player software to squeezeplayer and logitechmediaserver.

Only makes sense for a non "classic" Version of Phoniebox  because of the long booting time needed for the logitech media server (comparable to the booting time of Phonibox Spotify Version)

Why:

1. Support of different streaming services like spotify, web radio (just search inside the server for the radio channel, no search for correct stream address), youtube, podcasts, and many more (Tidal, Spotify (including Spotify Connect), Deezer, Qobuz, UPnP, Chromecast and Airplay speakers/players. You can stream from an iPhone using Shairtunes. It s even possible to integrate a cd-rom for playing or ripping.

2. Multi-room possibility

3. Very good control apps

And perhaps the most interesting point:

4. There exists an OS only for Squeezeplayer : [picoreplayer ](https://picoreplayer.org)(for raspis) which runs completely in Ram--> no more corrupted sd cards because of hard shutdowns (just cutting power cord).

   --> Problems like different soundcards, Mono or stereo, wifi, buttons, rotary commanders, displays, 
         bluetooth and even the shutdown problem are solved or at least discussed because there exists a 
         very good community.

ok, because the os is perfectly adapted to only running the player and the server, it is perhaps not that easy to adapt the phonibox scripts (webapp?)  and all its dependencies...

I know, that would be some work but perhaps worth the effort? I am using squeezeplayer lite and picoreplayer systems since many years, and i would love if the musicboxes of my kids would integrate into that ecosystem.

Greetings and have nice holidays!
cubertt

**Comment by MiczFlor** [comment]
Hi @cubertt 
thanks for the suggestion, I have to take a look at the software you recommend. A few months back we replaced VLS with MPD and even though it was the same OS, it turned out to be an ongoing issue. Nothing is as easy as it seems. I will give it a shot when I find the time.
All the best, micz

**Comment by imbaimbaimba** [comment]
Maybe this could be compatible in some way? http://ejurgensen.github.io/forked-daapd/

I built my phoniebox, hoping I could use it without speakers attached to it. But haven't been able to find a way to have the music it plays be routed to my wireless speaker. My speaker supports airplay, airplay 2.0 and chromecast audio, so I am really hoping to find a way.

Think it can be done @MiczFlor ?
