### ISSUE TITLE
Decrease master volume for HifiBerry MiniAmp

### ISSUE THREAD

**Issue by RoBra81** [MiczFlor/RPi-Jukebox-RFID#402]
Hello,

I just built my phoniebox with HifiBerry MiniAmp, lighted buttons on GPIO and rotary control and everything works great. The only "problem" I have is that volume control works but even volume 5% is still quite loud and I'd like to decrease it - is there any possibility to do this?

Thanks
Ronny

**Comment by MiczFlor** [comment]
Hi @RoBra81 
welcome to the community. I remember there was a post about this somewhere, but I can not find it. What I think I remember is the following:
* in the webapp you can set the maximum volume. you might also want to change the steps with which the volume can be changed and make the steps smaller
* if I remember correctly, chaning the master volume with `alsamixer` is the way to limit the master volume for the HifiBerry card.

If you have this figured out, please add to the wiki here: 
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/MANUAL#hifiberry-dac-soundcard-details

All the best and nice ho ho holidays, micz
