### ISSUE TITLE
Shopping List – Audi/Speaker

### ISSUE THREAD

**Issue by fabnoe** [MiczFlor/RPi-Jukebox-RFID#403]
I was wondering how to install the HiFiBerry DAC+ Soundcard with cinch adapters.
The listed speakers are usb compatible. The Ground Loop Isolator uses 3.5mm.

Maybe the shopping list is out of date?

**Comment by MiczFlor** [comment]
Hi @fabnoe 
you are right, not all hardware works and / or needs one another. These are items which come up in the discussions and people report that it worked for them - in their specific project. I added this as a note to the readme file on github.
Some contributors started to add their GPIO pin experience here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Hardware-Pinout-Overview
If you have some contributions, please add them to the wiki!
All the best, micz
