### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by Klickmichel** [MiczFlor/RPi-Jukebox-RFID#412]
Hi,
when I run the RegisterDevice script, I get this error:

```
Traceback (most recent call last):
  File "RegisterDevice.py", line 4, in <module>
    from Reader import get_devices
  File "/home/pi/RPi-Jukebox-RFID/scripts/Reader.py", line 32
    def __init__(self):
    ^
IndentationError: unexpected indent
```

How can I fix it? Could you help me please.

**Comment by MiczFlor** [comment]
Hi @Klickmichel 
good catch. There was a mismatch of "tab" indents and "4 spaces" indents. My bad for committing without testing this. Needed to be a quick fix - and I made it worse.
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/414
