### ISSUE TITLE
Webgui Volume selected value and shown value in dropdown field are not equal for odd values

### ISSUE THREAD

**Issue by SpookyFishes** [MiczFlor/RPi-Jukebox-RFID#413]
Phoniebox SW
Version: 1.1.8
Edition: Plus edition (feat. Spotify integration)

When I select a volume on the homescreen in the webgui there is in my oppinion a wrong behavior for odd values.

If I select an odd value e.g. 5% and press set the value in the dropdown value ist set to 10%. The value in the circle is set to 5%
![grafik](https://user-images.githubusercontent.com/25422320/50529634-b2d44880-0af6-11e9-8c99-c44affabbae3.png)

Select Dropdown 0% - Shown Dropdown 0% - Shown Value Circle 0%
**Select Dropdown 5% - Shown Dropdown 10% - Shown Value Circle 5%**
Select Dropdown 10% - Shown Dropdown 10% - Shown Value Circle 10%
**Select Dropdown 15% - Shown Dropdown 20% - Shown Value Circle 15%**
Select Dropdown 20% - Shown Dropdown 20% - Shown Value Circle 20%
....

**Comment by MiczFlor** [comment]
Hi @SpookyFishes 
true. The steps had been made smaller by someone and I committed these changes - without changing the "rounding" from 10 to 5, i.e. recognizing the smaller steps when reading the actual value. Should work now:
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/414
