### ISSUE TITLE
Bug: Webgui - Mobile Phone - Timestamp out of view for playing song and playlist

### ISSUE THREAD

**Issue by SpookyFishes** [MiczFlor/RPi-Jukebox-RFID#417]
Hello,

on my mobile phone with 5" display the timestamp is out of the view for the actual playing title and for the playlist.

![screenshot_2018-12-28-22-27-28](https://user-images.githubusercontent.com/25422320/50542031-9bf32c00-0bb2-11e9-80ef-0796e7893024.png)

When there are folders with long names it looks like this:
![grafik](https://user-images.githubusercontent.com/25422320/50542042-b200ec80-0bb2-11e9-8851-cac2768d6c71.png)
Is it possible to cut the string at the end of the box and show the rest of the string in the next line?

Phoniebox SW
Version: 1.1.8
Edition: Plus edition (feat. Spotify integration)

**Comment by gizmo21** [comment]
Plz check this too:

https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/260

**Comment by MiczFlor** [comment]
Should work now, Please check. Thanks for the feedback!

**Comment by SpookyFishes** [comment]
The time which was out of range is fixed in 1.1.9-rc7 (I posted a pic here https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/260)

The problem with long names is still there

Thanks for spending time in fixing these issues.
