### ISSUE TITLE
Add --yes apt install commands

### ISSUE THREAD

**Issue by lied** [MiczFlor/RPi-Jukebox-RFID#418]
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/7e12d45adfa566d80761af4adf3c87c5ecd21aa7/scripts/installscripts/stretch-install-spotify.sh#L459

This could be more "automated" when adding `--yes` to the command, as this automatically accepts the apt packages to be installed. (also relevant for the other install scripts as well)

**Comment by MiczFlor** [comment]
Hi @lied 
this suggestion flatters me, because you seem to trust the install process :) I will keep this open and hope the day will come where I happily add this.

**Comment by lied** [comment]
@MiczFlor hm, I don't get it, what bad could happen? Either it fails anyway after manually accepting the apt changes or it fails automatically :)

**Comment by bbung** [comment]
+1 or add a --unattended option to the script so the user can choose to trust or not

**Comment by MiczFlor** [comment]
I added this to the code.
