### ISSUE TITLE
RFID Reader does not work with USB Hub - only with direct connection

### ISSUE THREAD

**Issue by zehbart** [MiczFlor/RPi-Jukebox-RFID#420]
Hi everybody,

I have an issue with my **Neuftech RFID Reader**. As along as I connect it directly to my **Raspberry Zero W**, it works fine. With _dmesg -w_ I get the following messages:

_[ +2.699726] Indeed it is in host mode hprt0 = 00041901
[ +0.209997] usb 1-1: new low-speed USB device number 3 using dwc_otg
[ +0.003420] Indeed it is in host mode hprt0 = 00041901
[ +0.321444] usb 1-1: New USB device found, idVendor=16c0, idProduct=27db
[ +0.000019] usb 1-1: New USB device strings: Mfr=1, Product=0, SerialNumber=0
[ +0.000008] usb 1-1: Manufacturer: HXGCoLtd
[ +0.019086] input: HXGCoLtd as /devices/platform/soc/20980000.usb/usb1/1-1/1-1 :1.0/0003:16C0:27DB.0002/input/input1
[ +0.069712] hid-generic 0003:16C0:27DB.0002: input,hiddev96,hidraw0: USB HID v 1.10 Keyboard [HXGCoLtd] on usb-20980000.usb-1/input0_

As soon as I connect the RFID Reader via a USB Hub, the reader is not found any more. I am using a OTG Hub with an own power supply. When I connect the hub, I get the following messages:

_[ 71.003141] Indeed it is in host mode hprt0 = 00021501
[ 71.313063] usb 1-1: new full-speed USB device number 2 using dwc_otg
[ 71.313314] Indeed it is in host mode hprt0 = 00021501
[ 71.664273] usb 1-1: New USB device found, idVendor=0a05, idProduct=7211
[ 71.664293] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[ 71.664300] usb 1-1: Product: USB2.0 HUB
[ 71.668420] hub 1-1:1.0: USB hub found
[ 71.668692] hub 1-1:1.0: 4 ports detected_

After connecting the RFID Reader to the hub, _dmesg -w_ shows me the following lines:

_[ 260.982048] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[ 261.553594] usb 1-1.2: new low-speed USB device number 4 using dwc_otg
[ 262.093564] usb 1-1.2: new low-speed USB device number 5 using dwc_otg
[ 262.533774] usb 1-1-port2: attempt power cycle
[ 263.193655] usb 1-1.2: new low-speed USB device number 6 using dwc_otg
[ 263.733575] usb 1-1.2: new low-speed USB device number 7 using dwc_otg
[ 270.877818] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[ 271.369792] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[ 271.803678] usb 1-1.2: new low-speed USB device number 8 using dwc_otg
[ 272.343717] usb 1-1.2: new low-speed USB device number 9 using dwc_otg
[ 272.783887] usb 1-1-port2: attempt power cycle
[ 273.443673] usb 1-1.2: new low-speed USB device number 10 using dwc_otg
[ 273.983686] usb 1-1.2: new low-speed USB device number 11 using dwc_otg_

These messages keep on running, with increasing device numbers. 

Does anyone have an idea??

thanks
christian

**Comment by RogoTe** [comment]
This is problem with power supply. Not necessarily the supply of your USB hub, could also be the electronics in the hub. Everytime the raspi tries to start the reader over the hub the reader electronics does not get enough power for some miliseconds (or whatever) and the voltage drops below some minimum, so the reader restarts.

Try replacing the power supply or/and the USB hub.
