### ISSUE TITLE
suggestion for future: play videofiles on hdmi or send a command to play it on external devices

### ISSUE THREAD

**Issue by xCite1986** [MiczFlor/RPi-Jukebox-RFID#426]
Hey Micz,

first i have to say thank your for your great project, you are inspiring many people to make their children (or even themselfes) happier with a little bit of hardware and your great ootb-software :-)

This morning I stood in front of the mirror brushing my teeth and said a little incomprehensible to my wife that we have actually rebuilt a toniebox with a bit more possibilities and a function would be pretty awesome if a figure would play a videofile. as example figures like this set was great to play the associated movie:
https://www.amazon.de/Disney-Sammelfiguren-Set-Animators-Collection-20-Figuren/dp/B0778NWNKX

The basic of discussion has now come up where she said that no one would take such a box in the bed to watch a movie and I came up with the idea to send the command to an other device (I primary think of my amazon-devices such as fire tv , fire tab, etc ...) would be beneficial - but what does the community think about it? maybe there are a few perspectives for the box-builders to integrate a monitor into a box ...

sorry for my bad english - google helps a lot - and happy "discusting" ;-)

lg alex

**Comment by MiczFlor** [comment]
Hi @xCite1986 
there is another thread already working on this: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/257
I will close your thread. Teeth brushing is always the best time for new ideas!
