### ISSUE TITLE
Change Countdown to stop playback instead of shutdown 

### ISSUE THREAD

**Issue by Joebinator** [MiczFlor/RPi-Jukebox-RFID#429]
Hi there!

Is there anyhow a solution where i can stop playback instead of shutting down the entire phoniebox?

My daughter likes to listen to music while sleeping time and i she also likes do hear music when she wakes up. But if the box is turned off she sometimes don't get it to restart the box entire.

**Comment by MiczFlor** [comment]
Good idea. I will put this into my todo list. All the best, micz 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Klickmichel** [comment]
I think it ist possible to config a RFID trigger to stop playback after 5, 15, 30 or 60 minutes.
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/settings/rfid_trigger_play.conf.sample

**Comment by Joebinator** [comment]
hey, sorry for the late response.

the rfid trigger solution works fine so far for me :)
