### ISSUE TITLE
Spotfy edition --> iris is not working /installation of pylast  failed

### ISSUE THREAD

**Issue by cubertt** [MiczFlor/RPi-Jukebox-RFID#434]
I tried to install the spotify edition on a raspberry zero w with the script (image:  2018-10-09-raspbian-stretch) and iris is not working, i think because of this error:

`pylast requires Python '>=3.5' but the running Python is 2.7.13`

cant find a solution, any hints?

**Comment by cubertt** [comment]
This seems to be an issue with iris, so i looked in the github issue page of iris and found:

pip install 'pylast<3.0'

i have than managed to install iris via git clone ... and manually running setup.py (and updating some suggested things, because the error still occurred.. ) than finally it installed fine...

**Comment by MiczFlor** [comment]
Hi @cubertt 
thanks for sharing your knowledge. Can you be a bit more specific in what made it work - if others find this here? I know, once it works, it works and it is difficult to retrace the steps. But you might remember a few more hints :)
Thanks, micz

**Comment by cubertt** [comment]
I tried it again, but 

`$ pip install 'pylast<3.0'`

does not help.

Could install Iris via python3 runs without errors

then installed phonibox script --> iris is not working (phyton2 vs python3?)

So, no i cant give more information, i have a working version but dont know why 

Can someone confirm the error?

**Comment by Berdsen** [comment]
I had the same error and the problem and solution is described in pull request #436
