### ISSUE TITLE
Alltomp3

### ISSUE THREAD

**Issue by aeskimo** [MiczFlor/RPi-Jukebox-RFID#441]
Hi
Ist es möglich, statt den YouTube Importeure direkt das Tool „alltomp3“ zu integrieren.
https://github.com/alltomp3/alltomp3-app

**Comment by MiczFlor** [comment]
Hi @aeskimo 
this is a nice piece of software - but I don't think I will spend time embracing third party software like this. In my experience this creates a lot of extra work, coordinating, following up changes in the third party software - and there often is a limited number of users doing this anyway, if it is not mainstream software.
