### ISSUE TITLE
Neuftech RFID-Reader - how to deactivate beeper?

### ISSUE THREAD

**Issue by derOger** [MiczFlor/RPi-Jukebox-RFID#448]
Hello,
since this is one of the recommended ones maybe someone had this issue (?). Can I mute the Neuftech RFID Reader? Now the reader beeps loudly when it is turned on and when I scan a card. Can I deactivate this beep? I have found some Java code for that but no other option.
Thank you alot.

**Comment by tobiasnix** [comment]
Its not possible to deactivate. But you can easily remove the hardware component. See also #223

**Comment by derOger** [comment]
I thought about opening the case and removing the beeper. Also to maybe save some space in the case later on ...
But the most waste of space are the cables I think.

**Comment by MiczFlor** [comment]
I close this, I think it's solved. Silence in the forum == beeper ripped off the board :)
