### ISSUE TITLE
Rotary encoder for forward/backward seek?

### ISSUE THREAD

**Issue by iwishitwassummer** [MiczFlor/RPi-Jukebox-RFID#450]
Hi all,

did anyone tried to do use a rotary encoder for seeking?
My kid is using the box foremost to listen to audiobooks and wants to seek to the favorite parts of the audiobook. In combination with @splitti OLED it might be be possible to visualize the "progress".
Any advice is welcome, I'm a newbie to GPIO.
TX

**Comment by iwishitwassummer** [comment]
Hi @bofelix 
it should be possible to use the [HTTM button](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/5#issuecomment-455779732) for this, what do you think?
The time between the high and lows of the button should be identifiable which could be used to seek a track, right?

**Comment by iwishitwassummer** [comment]
Hi,
Ich meine vorspulen (nicht den Track wechseln). Wenn der Button im hold Mode ist, könnte man doch die Zeit zwischen den 2 Signalen messen und daraus den „Vorsprung“ in einem Track nutzen, richtig? Klar, ich muss  noch Code schreiben und ich weiß nicht ob eine Berechnung schnell genug geht.
Danke dir simisch

**Comment by bofelix** [comment]
Hallo 

Deutsch ist einfacher.
Ich bin leider kein Python Profi.
Aber es gibt die Möglichkeit Aktionen zu definieren für gehaltene Knöpfe. So ist es beim Shutdown. Da steht im Code shut when held. Du kannst dann auch bestimmen wann ein Knopf als gehalten erkannt wird. So habe ich mir den Playknopf umprogrammiert zum Herunterfahren nach 2 Sekunden.
Ob der MPD aber spulen als Kommando kennt weiß ich nicht.

Gruß Stefan 

Am 21. Januar 2019 06:39:33 MEZ schrieb iwishitwassummer <notifications@github.com>:
>Hi,>
>Ich meine vorspulen (nicht den Track wechseln). Wenn der Button im hold
>Mode ist, könnte man doch die Zeit zwischen den 2 Signalen messen und
>daraus den „Vorsprung“ in einem Track nutzen, richtig? Klar, ich muss 
>noch Code schreiben und ich weiß nicht ob eine Berechnung schnell genug
>geht.>
>Danke dir simisch>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/450#issuecomment-455954084

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by iwishitwassummer** [comment]
Danke Stefan. Dann konntest du für Lautstärke und Skip konntest du den vorhanden Code nutzen? 
Vorspulen geht, ist schon im Standardpaket drin. Im Moment mach ich das per Karte. Aber das ist sehr nervend und dauert. Ist auf 15s eingestellt und man muss immer die Karte auf den Reader halten für jeder weitere Sequenz. Selbst bei Erhöhung der Vorspulzeit wird das in einem Hörbuch nervend, und dann noch dieser Reader Beep :0

**Comment by bofelix** [comment]
Hallo.

Ja das Pythonscript gpio-buttons.py hat sofort funktioniert mit "pullup false".

Gruß Stefan 

Am 21. Januar 2019 21:59:29 MEZ schrieb iwishitwassummer <notifications@github.com>:
>Danke Stefan. Dann konntest du für Lautstärke und Skip konntest du den
>vorhanden Code nutzen? >
>Vorspulen geht, ist schon im Standardpaket drin. Im Moment mach ich das
>per Karte. Aber das ist sehr nervend und dauert. Ist auf 15s
>eingestellt und man muss immer die Karte auf den Reader halten für
>jeder weitere Sequenz. Selbst bei Erhöhung der Vorspulzeit wird das in
>einem Hörbuch nervend, und dann noch dieser Reader Beep :0>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/450#issuecomment-456197377

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by iwishitwassummer** [comment]
Super danke dir. Buttons sind bestellt, ich wage den Versuch.

**Comment by bofelix** [comment]
Hallo.

Latch ist halten....

Ich habe bei allen Schaltern die Lötbrücke gesetzt.

Gruß 
Stefan 

Am 24. Januar 2019 12:29:54 MEZ schrieb iwishitwassummer <notifications@github.com>:
>@bofelix Habe die Taster bekommen, für Play/Pause mal angeschlossen.
>Die gute Nachricht, es geht. Der Taster is im Latch Modus. Laut
>Datenblatt: >
>>
>> Hierbei gibt der Output-pin ein Signal aus und schaltet die
>Hintergrundbeleuchtung an und hält diese, bis der Touch-Schalter erneut
>berührt wird.>
>>
>Ich dachte in diesem Modus berührt man für Pause, Licht geht an und
>bleibt, dann nochmal ein Touch für Play (oder Unpause). Pullup false
>order true ergibt keinen Unterschied. Hast du den Button für Play in
>den Hold Modus geschaltet?>
>Danke>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/450#issuecomment-457164799

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by iwishitwassummer** [comment]
@bofelix Alles klar danke dir
