### ISSUE TITLE
capacitive touch sensor ttp223

### ISSUE THREAD

**Issue by habersatt** [MiczFlor/RPi-Jukebox-RFID#456]
Hello!
Instead of push buttons, I have installed capacitive touch sensors type ttp223. Everything works great except for volume up and down and mute.
My question: How do I adjust the gpio-button.py so I can adjust the volume. Maybe someone has already gained experience. 
Thanks in advance.
Clemens

**Comment by comdoxx** [comment]
Hi habersatt,

If everything is wired correctly (VCC, GND and GPIO) and you didn't bridge either A or B or the ttp223's board, it should behave just as a normal button, and adjust volume in both ways: Single touch and holding. Make sure to connect the correct GPIO you take from the `gpio-button.py` to the sensor. Don't mix up pin number and GPIO number.

If that's done and you still experience trouble, feel free to post (the excerpt of) your gpio-button.py and maybe a photo of your connection.

**Comment by comdoxx** [comment]
Hi Clemens,

Thanks for the detailed answer. I'm pretty sure, the touch sensor behaves
like a switch. Did you try to touch it on and then off after a second or
so? Does it stop then to increase or decrease volume?

Am Sa., 26. Jan. 2019, 12:24 hat habersatt <notifications@github.com>
geschrieben:

**Comment by habersatt** [comment]
Hi burberius,
that works! Thanks a lot!!!!
LG
Clemens

**Comment by MiczFlor** [comment]
Hi @habersatt 
I close this thread and started a page in the wiki:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Capacitive-touch-sensors
Possibly you want to add more info to this page?
Thanks @comdoxx and @burberius for leading the way!
All the best, micz
