### ISSUE TITLE
Feature: Covers beside albums in Web UI

### ISSUE THREAD

**Issue by Feuer-sturm** [MiczFlor/RPi-Jukebox-RFID#462]
Hello,
at the moment I am testing 1.1.9-rc6 with Spotify edition.
I activated "Settings" -> "Do you want to show covers beside the albums and playlists on the main page?" -> "Show cover"

When the software is playing an album the cover will be displayed at the top
![grafik](https://user-images.githubusercontent.com/25422320/51807661-43cf4880-228a-11e9-8f39-cfd51ad5ab7b.png)

In the lists of albums the covers are missing.
![grafik](https://user-images.githubusercontent.com/25422320/51807652-11bde680-228a-11e9-94ca-def56949416f.png)

In version 1.1.8 the cover of the album was shown in the red area. Was this feature removed with the new version or is it a bug?

I added the music and the cover.jpg via WebUI file dialog "Upload files"

**Comment by MiczFlor** [comment]
Hi @SpookyFishes 
true, I hid them and didn't change the translation string :) they take an awful lot of space. Do you think they would be good to have? (keep mobile view in mind :)

**Comment by s-martin** [comment]
Not planned at the moment for V2.
