### ISSUE TITLE
Switch from speaker to headphone when plugging in the headphone

### ISSUE THREAD

**Issue by matthias2468** [MiczFlor/RPi-Jukebox-RFID#470]
Hello,
with a standard cd player usually there is a jack for headphone and when they are plugged in the speakers are muted and the cd is played on the headphones.
How can I achieve this here?
I tried it with an HDMI adapter which has a headphone connector, but there's no sound coming out there.
Thank you and best regards
Matthias

**Comment by Yordan1976** [comment]
I ordered these: https://s.click.aliexpress.com/e/bNorGo3J
They switch to other pins when headphones are connected.

**Comment by matthias2468** [comment]
Hello Yordan,
thanks, I will try this (once they arrive, so probably in 28-60 days... :( ).
Matthias
