### ISSUE TITLE
Web-UI Stop Playout Timer Value not shown in circle

### ISSUE THREAD

**Issue by SpookyFishes** [MiczFlor/RPi-Jukebox-RFID#479]
I am using phoniebo software 1.1.9-rc7 Spotify edition
 
When I select a value for the "stop playout timer" an press "Set" no value is shown in the circle.
It doesn't care if I select 2 min oder 240 min

![grafik](https://user-images.githubusercontent.com/25422320/52504660-6b5ad500-2be9-11e9-96d4-cf1fbb56a9f7.png)

**Comment by Yordan1976** [comment]
There are more issues with the shutdown settings:
- If you set the sleep timer, both the sleep timer and the stop playout timer circles will be set.
- Both select dropdowns show "OFF" after setting the one or the other.
- If you set the idle timer and play just for a few seconds, it doesn't reset to no idle.

**Comment by MiczFlor** [comment]
I committed the changes to the latest `develop` branch. ... and will close this for now.
