### ISSUE TITLE
auto start services w/ cron tab

### ISSUE THREAD

**Issue by d7071** [MiczFlor/RPi-Jukebox-RFID#48]
Hi Mic

I upgraded my Jukebox with a Hifeberry. 
Now I wanted to add buttons. But everytime I register the GPIO script for startup no music won't be able to be played.

**Comment by hailogugo** [comment]
Do the sound work without Button Script?
Do you add hifiberry in vlc as your Standard soundcard?

**Comment by d7071** [comment]
yes - sounds works without button script
yes - added hifiberry in vlc
