### ISSUE TITLE
Feature: Add System command to rfid card via Web UI

### ISSUE THREAD

**Issue by pkolmann** [MiczFlor/RPi-Jukebox-RFID#481]
We would like to power off the raspi via a special 'good night card'. Currently we cannot bind any system commands to a card. Would that be possible to achieve?

Thanks
Philipp

**Comment by Yordan1976** [comment]
Did you tried it like it is described in the manual? What did not work?

**Comment by pkolmann** [comment]
Thanks, that's what I've m looking for.

**Comment by pkolmann** [comment]
What would be a great addon would be to be able to add those commands also via web interface to cards.

**Comment by s-martin** [comment]
Also possible in future3 version
https://rpi-jukebox-rfid.readthedocs.io/en/latest/userguide/carddatabase.html#card-database
