### ISSUE TITLE
Wrong Podcast RSS in Subfolders

### ISSUE THREAD

**Issue by Yordan1976** [MiczFlor/RPi-Jukebox-RFID#482]
The 'Podcast RSS' buttons that belong to subfolders in any folder contain the files of the last subfolder in that folder. Look at the status bar:
![screenshot 046 phoniebox - mozilla firefox](https://user-images.githubusercontent.com/35901879/52595105-5c745c80-2e4d-11e9-967a-71728f07f1f3.png)

It seems to be ok for music the folders direct in 'phoniebox_audiofile'

**Comment by s-martin** [comment]
Closing. Feel free to reopen this issue, if the problem still occurs.
