### ISSUE TITLE
How can I activate StopafterX by default?

### ISSUE THREAD

**Issue by Worren** [MiczFlor/RPi-Jukebox-RFID#493]
How can I activate StopafterX by default after startup without using a rfid card? 
I would like to automatically stop playing after X minutes.

Thanks!

**Comment by m-rl-n** [comment]
Hi @Worren 
you can register a service in systemd, that runs payout_control.sh at startup.
**But** this will start the timer regardless of wether you start playing audio or not.

Here is how to do this:

- Create a new service: `sudo nano /etc/systemd/system/phoniebox-stoptimer.service`
- Paste this into nano, change the value after `-v=` to the amount of minutes the timer should run and save:
```
[Unit]
Description=Phoniebox Startup Stop Timer
After=network.target iptables.service firewalld.service phoniebox-startup-sound.service

[Service]
User=pi
Group=pi
Type=oneshot
RemainAfterExit=true
WorkingDirectory=/home/pi/RPi-Jukebox-RFID
ExecStart=/usr/bin/sudo /home/pi/RPi-Jukebox-RFID/scripts//playout_controls.sh -c=playerstopafter -v=5

[Install]
WantedBy=multi-user.target
```
- Enable the service: `sudo systemctl enable phoniebox-stoptimer.service`
- If you want to disable it sometime: `sudo systemctl disable phoniebox-stoptimer.service`

**Comment by Worren** [comment]
Works great. Thank you very much!
