### ISSUE TITLE
Playback of folder not working as expected

### ISSUE THREAD

**Issue by georgbachmann** [MiczFlor/RPi-Jukebox-RFID#495]
Hello,
I have my folders setup the following way:

AudioBookTitle/EpisodeTitle/Files01-xx.mp3
So f.e.

    Pumuckl/Das neue Badezimmer/01.mp3
    Pumuckl/Das neue Badezimmer/02.mp3
    Pumuckl/Das neue Badezimmer/03.mp3
    ...

So in this folder are a total of 30 files now. Each is 2 minutes long, so I can use the gpio buttons to jump back and forth (btw... would it be possible to just jump x minutes in one file as well? would be nicer instead of having to split all the mp3s)

So the problem is now, that on the main-page is shows that there are 30 files in there. But when I hit the play-button next to the folder, it will start at a random position and also only have about 18 minutes  of playback instead of the 58min it should have...

I simply don't really understand what's going on there... I looked into the `playlists` folder and there is a playlist that should match with all the 30 files listed...?!?

Am I doing something wrong???? And why is it working in some other folders with the same structure, but not in that one? I tried deleting the folder and re-uploading... still the same problem :(

**Comment by MiczFlor** [comment]
Hi @georgbachmann 
looks like nobody chipped in some wisdom into your problem. Not even me :)
Do you know what happened and possibly solved it yourself? If so, please post it here and close the thread.
All the best, micz
