### ISSUE TITLE
Installation DAC 5102 Chip

### ISSUE THREAD

**Issue by hailogugo** [MiczFlor/RPi-Jukebox-RFID#497]
Hi,
I waste a lot of time in the last days but it will not work.
The Sound is working as follow:
- By Startup
- with VLC
- If I installing Volumio with Generetic DAC or Hifiberry DAC

What also work is to do the Softwarecontrol from ALSA by the Webpage and of the Desktop.

Before I buy this DAC I read this information of the wiki:
External Non USB Audio DAC ES9023
[https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/External-Non-USB-Audio-DAC-ES9023](url)
I add the Software like the link below.

And I found this that is my wiring
[https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/15#issuecomment-389517956](url)

I do already a request in the german Forum for Raspberry but I got not enough help. :)
[https://forum-raspberrypi.de/forum/thread/42168-phoniebox-dac-installieren-und-anschlie%C3%9Fen/?postID=370014#post370014](url)

Helperskript

pi@juke:~ $ sudo /home/pi/RPi-Jukebox-RFID/scripts/helperscripts/Analytics_AfterInstallScript.sh
************************************
*** PHONIEBOX INFO
*** version: 1.1.9-rc7
*** edition: classic
*** Audio_iFace_Name: Master
*** Audio_Folders_Path: /home/pi/RPi-Jukebox-RFID/shared/audiofolders
*** Audio_Volume_Change_Step: 3
*** Max_Volume_Limit: 100
*** Idle_Time_Before_Shutdown: 0
*** Second_Swipe: RESTART
*** Playlists_Folders_Path: /home/pi/RPi-Jukebox-RFID/playlists
*** ShowCover: ON
************************************
*** CONF FILES DEFAULT
*** /etc/samba/smb.conf
-rw-r--r-- 1 root root 9,5K Feb 18 13:41 /etc/samba/smb.conf
   path=/home/pi/RPi-Jukebox-RFID/shared
   path=/home/pi/RPi-Jukebox-RFID/shared/audiofolders
*** /etc/lighttpd/lighttpd.conf
-rw-r--r-- 1 root root 1,1K Feb 18 13:41 /etc/lighttpd/lighttpd.conf
*** /etc/lighttpd/conf-available/15-fastcgi-php.conf
-rw-r--r-- 1 root root 398 Feb 18 13:41 /etc/lighttpd/conf-available/15-fastcgi-php.conf
*** /etc/php/7.0/fpm/php.ini
-rw-r--r-- 1 root root 70K Feb 18 13:41 /etc/php/7.0/fpm/php.ini
*** /etc/sudoers
-r--r----- 1 root root 784 Feb 18 13:41 /etc/sudoers
*** /etc/systemd/system/phoniebox*
-rw-r--r-- 1 root root 296 Feb 18 13:41 /etc/systemd/system/phoniebox-rfid-reader.service
-rw-r--r-- 1 root root 340 Feb 18 13:41 /etc/systemd/system/phoniebox-startup-sound.service
-rw-r--r-- 1 root root 289 Feb 18 13:41 /etc/systemd/system/phoniebox-gpio-buttons.service
-rw-r--r-- 1 root root 291 Feb 18 13:41 /etc/systemd/system/phoniebox-idle-watchdog.service
*** /etc/mpd.conf
-rw-r----- 1 mpd audio 15K Feb 19 17:01 /etc/mpd.conf
music_directory         "/home/pi/RPi-Jukebox-RFID/shared/audiofolders"
# music_directory are changed.
# symbolic links outside of the configured music_directory.
# symbolic links inside of the configured music_directory.
#       mixer_control   "Master"                # optional
#       mixer_control   "Master"                # optional
        mixer_control   "Master"        # optional
*** /etc/dhcpcd.conf
-rw-rw-r-- 1 root netdev 1,7K Sep 10 10:31 /etc/dhcpcd.conf
#static ip_address=192.168.0.10/24
#static ip_address=192.168.1.23/24
#static routers=192.168.0.1
#static routers=192.168.1.1
option domain_name_servers, domain_name, domain_search, host_name
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
#static domain_name_servers=192.168.1.1
*** /etc/wpa_supplicant/wpa_supplicant.conf
-rw-r--r-- 1 root root 83 Feb 18 13:28 /etc/wpa_supplicant/wpa_supplicant.conf
country=DE
************************************
*** +Spotify Edition
*** /etc/locale.gen
-rw-r--r-- 1 root root 8,9K Feb 18 13:28 /etc/locale.gen
*** /etc/locale.gen
-rw-r--r-- 1 root root 8,9K Feb 18 13:28 /etc/locale.gen
*** /etc/mopidy/mopidy.conf
ls: Zugriff auf '/etc/mopidy/mopidy.conf' nicht möglich: Datei oder Verzeichnis nicht gefunden
cat: /etc/mopidy/mopidy.conf: Datei oder Verzeichnis nicht gefunden
*** ~/.config/mopidy/mopidy.conf
ls: Zugriff auf '/root/.config/mopidy/mopidy.conf' nicht möglich: Datei oder Verzeichnis nicht gefunden
cat: /root/.config/mopidy/mopidy.conf: Datei oder Verzeichnis nicht gefunden
`

My thinking that anything will be wrong in the mpd.conf.

This look like this:

`
###############################################################################
# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple 
# audio outputs at the same time, through multiple audio_output settings 
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.
#
# An example of an ALSA output:
#
audio_output {  
    type        "alsa"
    name        "My ALSA Device"
    mixer_control    "Master"    # optional
}  
audio_output {  
        enabled         "yes"
        type            "alsa"
        name            "HiFiBerry DAC"
        device          "sndrpihifiberry"
        auto_resample   "no"
        auto_channels   "no"
        auto_format     "no"
        dop             "no"
}  
#audio_output {
#    type        "alsa"
#    name        "My ALSA Device"
#    device        "hw:0,0"    # optional
#    mixer_type      "hardware"      # optional
#    mixer_device    "default"    # optional
#    mixer_control    "Master"        # optional
#    mixer_index    "0"        # optional
#}
#
# An example of an OSS output:
#
#audio_output {
#    type        "oss"
#    name        "My OSS Device"
#    device        "/dev/dsp"    # optional
#    mixer_type      "hardware"      # optional
#    mixer_device    "/dev/mixer"    # optional
#    mixer_control    "Master"        # optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
#audio_output {
#    type        "shout"
#    encoding    "ogg"            # optional
#    name        "My Shout Stream"
#    host        "localhost"
#    port        "8000"
#    mount        "/mpd.ogg"
#    password    "hackme"
#    quality        "5.0"
#    bitrate        "128"
#    format        "44100:16:1"
#    protocol    "icecast2"        # optional
#    user        "source"        # optional
#    description    "My Stream Description"    # optional
#    url             "http://example.com"    # optional
#    genre        "jazz"            # optional
#    public        "no"            # optional
#    timeout        "2"            # optional
#    mixer_type      "software"              # optional
#}
#
# An example of a recorder output:
#
#audio_output {
#       type            "recorder"
#       name            "My recorder"
#       encoder         "vorbis"                # optional, vorbis or lame
#       path            "/var/lib/mpd/recorder/mpd.ogg"
##      quality         "5.0"                   # do not define if bitrate is defined
#       bitrate         "128"                   # do not define if quality is defined
#       format          "44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#    type        "httpd"
#    name        "My HTTP Stream"
#    encoder        "vorbis"        # optional, vorbis or lame
#    port        "8000"
#    bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
#    quality        "5.0"            # do not define if bitrate is defined
#    bitrate        "128"            # do not define if quality is defined
#    format        "44100:16:1"
#    max_clients     "0"                     # optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
# Please see README.Debian if you want mpd to play through the pulseaudio
# daemon started as part of your graphical desktop session!
#
#audio_output {
#    type        "pulse"
#    name        "My Pulse Output"
#    server        "remote_server"        # optional
#    sink        "remote_server_sink"    # optional
#}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#    type        "winmm"
#    name        "My WinMM output"
#    device        "Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#        or
#    device        "0"        # optional
#    mixer_type    "hardware"    # optional
#}
#
# An example of an openal output.
#
#audio_output {
#    type        "openal"
#    name        "My OpenAL output"
#    device        "Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#}
#
## Example "pipe" output:
#
#audio_output {
#    type        "pipe"
#    name        "my pipe"
#    command        "aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#    command        "AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#    command        "nc example.org 8765"
#    format        "44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#    type        "null"
#    name        "My Null Output"
#    mixer_type      "none"                  # optional
#}
#
# If MPD has been compiled with libsamplerate support, this setting specifies 
# the sample rate converter to use.  Possible values can be found in the 
# mpd.conf man page or the libsamplerate documentation. By default, this is
# setting is disabled.
#
#samplerate_converter        "Fastest Sinc Interpolator"
#
###############################################################################
`

Or other Test

`
audio_output {  
    type        "alsa"
    name        "My ALSA Device"
    mixer_control    "Master"    # optional
}  
audio_output {  
        enabled         "yes"
        type            "alsa"
        name            "HiFiBerry DAC"
        device          "sndrpihifiberry"
        mixer_type      "software"
        auto_resample   "no"
        auto_channels   "no"
        auto_format     "no"
        dop             "no"
}  

`

Can somebody help me?
If you need something please let me know.

**Comment by pseeger** [comment]
Try top disable Thema gpio buttons

**Comment by hailogugo** [comment]
Hi tested it but I cannot here anything.

**Comment by hailogugo** [comment]
@martinclausen2
I see you wiki data about DACs. but it do not work for me. I do not know what is wrong.

Please look up in this thread. I tested a lot of different things but I do not find what I am do wrong.

https://forum-raspberrypi.de/forum/thread/42168-phoniebox-dac-installieren-und-anschlie%C3%9Fen/?postID=371532#post371532

Please help me.

**Comment by hailogugo** [comment]
Hi, 
I think I do off the gpio buttons service by using the off button on webpage. This will not stop the service. So my mistake.
If If I disable the service like it will add as a service in the installscript the dac works well.

My problem was that I also do a tested before with a LED in my button skript and this was not deactive from my side because I do not use the LED.
So now it works well and thanks for all your help.
