### ISSUE TITLE
Play on chromecast or google home

### ISSUE THREAD

**Issue by atwc** [MiczFlor/RPi-Jukebox-RFID#512]
Is it possible to launch spotify on other device from Phoniebox, like on the spotify app, to play on chromecast(audio) or google home?

**Comment by MiczFlor** [comment]
This does not answer your question but might provide a new train of thought:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Bluetooth

**Comment by atwc** [comment]
It could be an option, but be compatible with chromecast or google assistant would allow to have only one Phoniebox for multiple speaker.
With a selector button we could choose to play on the wanted room on a chromecastAudio, a google home or other connected speaker (sonos).

**Comment by MiczFlor** [comment]
HI @atwc 
trying to merge threads, I will close this and please jump into this discussion.
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/499
All the best, micz
