### ISSUE TITLE
RFID Reader ist inaktiv während ein Song spielt

### ISSUE THREAD

**Issue by Nakiface** [MiczFlor/RPi-Jukebox-RFID#515]
Alles Funktioniert Super. Aber wenn ein Song läuft reagiert der RFID-Reader nicht. Nach dem Song kann ich einen anderen Chip auflegen das Gerät piept und der nächste Song geht los. Nur wärend der Song läuft passiert nichts wenn man einen anderen oder den gleichen Chip drauflegt. Als wäre der Reader deaktiviert. Kann das an meinem Supergünstigen 4€ RFID Reader aus China liegen?

**Comment by Nakiface** [comment]
mit dem empfohlenem RFID-Reader ging alles einwandfrei.

**Comment by MiczFlor** [comment]
Hi @Nakiface 
damit hast du mir viele Kopfschmerzen gespart :)
