### ISSUE TITLE
Upgrade Phoniebox +Spotify 1.1.8 to 1.1.9 !?

### ISSUE THREAD

**Issue by sonicdee** [MiczFlor/RPi-Jukebox-RFID#521]
How to Upgrade Phoniebox +Spotify 1.1.8 to 1.1.9, 
new install or just git update like in old versions?

cd /home/pi/RPi-Jukebox-RFID
git checkout master
git fetch origin
git reset --hard origin/master
git pull

**Comment by andisger** [comment]
did anyone update from 1.1.8 to 1.1.9 already? any issues?
thanks

**Comment by sonicdee** [comment]
no one knows ?
