### ISSUE TITLE
Lieder starten nicht

### ISSUE THREAD

**Issue by Eisselpudel** [MiczFlor/RPi-Jukebox-RFID#526]
Hallo,
ich habe nach einigen Wochen mein Raspberry wieder rausgeholt und will die Jukebox endlich zum laufen bringen.
Die Installation klappte eigentlich Problemlos. Ich musste die Rechte anschließend einmal ändern, um Ordner erstellen und Dateien hochladen zu können. Gestern habe ich gemerkt, dass ich den MPD Server noch installieren muss. Jetzt kann ich auch die Lautstärke einstellen (obwohl ich nichts höre). RFID Karten werden erkannt und beim VLC-Player kann ich auf der normalen Oberfläche die Lieder abspielen. Nur mit der Jukebox nicht.
Bei Youtube bekam ich den Tipp, die Datenbank nochmal zu scannen. Den Knopf habe ich nicht, oder finde ich nicht.
Anbei zwei Bildschirmfotos von von der Info und dem Reiter "Folders und Files".
Ich meine, hier mal gelesen zu haben, dass man mit einem Befehl noch Systeminfos posten soll. Den finde ich nur nicht wieder.
Wäre super, wenn mir jemand weiterhelfen könnte.
<img width="1037" alt="phoniebox_2" src="https://user-images.githubusercontent.com/49683913/56212037-861e4f80-6059-11e9-8352-5b0f99df3bfd.png">
<img width="581" alt="phoniebox_1" src="https://user-images.githubusercontent.com/49683913/56212058-8fa7b780-6059-11e9-8fb9-a230ebc3a857.png">

**Comment by MatthiasCzech** [comment]
Hi, das klingt, als ob du die Phoniebox manuell installiert hast. (btw. Version 1.1.9 ist schon draußen).
Beim installieren mit dem One-Line-Script, wird man nach dem Audioausgabe-Gerät gefragt. Das sollte, wenn man nicht gerade eine USB-Soundkarte oder Hifiberry nutzt "PCM" sein.
Und das wurde dann im Verzeichnis settings in die Datei "Audio_iFace_Name" geschrieben.
prüfe die Datei mal, und falls nicht vorhanden, hoffe ich, es reicht sie einfach zu erstellen und PCM gefolgt von einem Zeilenumbruch reinzuschreiben.
Ich kenne den Changelog jetzt nicht, aber generell würde ich empfehlen mit dem One-Line-Script auf die Version 1.1.9 zu wechseln. (Neu aufsetzen)
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/INSTALL-stretch#oneLineInstall

**Comment by Eisselpudel** [comment]
Hey Matthias,
du hattest Recht, war eine manuelle Installation. Hatte zwischendurch auch schon auf 1.1.9 geupdatet.
Habe das jetzt mit dem OLS installiert, musste ein bisschen am RFID-Reader rumspielen und es klappt. Voll gut. Danke für die Tipps!!!!
