### ISSUE TITLE
[Spotify] Slashes in names aren't saved

### ISSUE THREAD

**Issue by TeGuy** [MiczFlor/RPi-Jukebox-RFID#538]
I put an RFID-card in every "Benjamin Blümchen"-cassette I own. I scanned every cassette and wrote foldernames like "Kassetten/BB33" in the field "Name for the audio folder that will contain the stream URL." to create subfolders.

The register mechanism does not print out any error - but after scanning all cassettes  (and searching for all episodes on spotify) I realized that none of them were saved - without any errors.... ;-(

Please print out errors if the folder/playlist file was not correctly saved. If in doubt, let the system check the files...

**Comment by MiczFlor** [comment]
Will look into this.
