### ISSUE TITLE
Connection to Synology / NAS / Diskstation / DLNA

### ISSUE THREAD

**Issue by mrberton** [MiczFlor/RPi-Jukebox-RFID#555]
Hello all,
I'm currently trying to find a way to get the mp3 files from my diskstation instead of a local copy on the SD card.
I've tried various options (DLNA, Apache with directory and file listing, ...).
None of them is working up until now.
Did anybody tried something similar and if yes, how?
Is there any support for DLNA?

Thanks in advance 
Christoph

**Comment by RogoTe** [comment]
I think the most straight forward way to connect the Phoniebox and your NAS would be mounting a NAS share on the raspberry to `/home/pi/RPi-Jukebox-RFID/shared/audiofolders`.
