### ISSUE TITLE
WebInterface is displaying wrong play time / overall length

### ISSUE THREAD

**Issue by Berdsen** [MiczFlor/RPi-Jukebox-RFID#566]
**Description**
When having long playlists above an hour, the webinterface starts displaying the time with an hour already added. This seems to be a problem with daylight saving times and the php function date.

**Technical description**
Anywhere where the date function is used in the php code like `.date("H:i:s", date).` the raspberries(?) current settings will be used to determine the daylight saving time and probably add an hour, if it is currently active.

**Affected files:**
- htdocs/ajax.loadTime.php
- htdocs/ajax.loadOverallTime.php
- htdocs/ajax.loadPlaylist.php

I'll fill up a pull request to use gmdate instead of date for the desired parts.

![Problem](https://user-images.githubusercontent.com/2563949/63258207-dd3c6700-c27b-11e9-9a90-2311321383d4.png)

![Solution](https://user-images.githubusercontent.com/2563949/63258232-e7f6fc00-c27b-11e9-85b8-f5f4c359d823.png)

**Comment by MiczFlor** [comment]
Hi @Berdsen 
nice catch!

**Comment by MiczFlor** [comment]
Hi @Berdsen 
I added your files to the develop branch, could you please take a look and confirm they are working?
All the best, micz

**Comment by Berdsen** [comment]
Hi @MiczFlor
I'll check it this week and leave a comment here, when I'm done.
All the best

**Comment by Berdsen** [comment]
Hi @MiczFlor,

took a little longer to test. I switched to the latest develop branch on my phoniebox and checked, that it will work perfect :)
This issue can be closed now or when it will be merged to master.
