### ISSUE TITLE
Web App slow/not working >> Buster?

### ISSUE THREAD

**Issue by hiduei** [MiczFlor/RPi-Jukebox-RFID#568]
Thank you for providing the buster one line installation script. I just installed Phoniebox following your instructions and having the hardware suggested here:
https://www.iphone-ticker.de/wochenend-projekt-kontaktlose-musikbox-fuer-kinder-123063/

I had no error messages during the installation. However, accessing the Web-App is quite slow
- no full website via Wifi (only text)
- limited functions via ethernet (better when supplied via mains and not the powerbench)

The Website won't show the number of scanned RFIDs.
The music won't play
...

SSH and connection via explorer works fine

Thanks for your help
Michael

**Comment by MiczFlor** [comment]
Hi @hiduei 
it's very difficult to pin down the problem. There seem to be a few things not working.
Did you install the Phoniebox using the buster one line install script? Or did you do it manually?
