### ISSUE TITLE
Volume control not linear

### ISSUE THREAD

**Issue by Prutsium** [MiczFlor/RPi-Jukebox-RFID#571]
Might be related to this but The Audiomixer and PCM volume control are not linear.
Means 60% on audio mixer is 0% on the PCM.

This results in very small headroom for volume control (only 20% is the range from 0 - 100)

Any experience on this?
Additional info: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/543#issuecomment-499941819
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/543#issuecomment-524537181

_Originally posted by @Prutsium in https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/543#issuecomment-499851656_

**Comment by MiczFlor** [comment]
I have experience with this :) the linear output also does not relate the human ear very well... but I have no suggestion how to remedy this.
