### ISSUE TITLE
sound not working after phoniebox install

### ISSUE THREAD

**Issue by Howl1n** [MiczFlor/RPi-Jukebox-RFID#577]
Hi there,

I have the very same issue like @saschaschefenacker: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/544#issuecomment-509026113

In the beginning I followed this How To Guide: http://splittscheid.de/selfmade-phoniebox/#5_1

I use RPi 3, Hifiberry Miniamp and different sound boxes. When following exactly this guide, I get a soughing sound when using the test sound: https://forum-raspberrypi.de/forum/thread/42908-kein-sound-mit-hifiberry-dac/?postID=379381#post379381

Then I installed the non spotify phoniebox version. Since then the sound does not work anymore. However, aplay -l still delivers the hifiberrydac soundcard.

**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: sndrpihifiberry [snd_rpi_hifiberry_dac], Gerät 0: HifiBerry DAC HiFi pcm5102a-hifi-0 []
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0 

The Audio Settings iFace Name file is empty and it does not let me edit the file. 

asound.conf:
`pcm.hifiberry {
    type softvol
    slave.pcm "plughw:0"
    control.name "Master"
    control.card 0
}
pcm.!default {
    type             plug
    slave.pcm       "hifiberry"
}`

config.txt contains only the dtoverlay=hifiberry-dac

Anyone who can help out here? It seems like Phoniebox setup is changing something in the sound setup or am I overseeing something in the asound.conf?

speaker-test -D hifiberry -c 2 and speaker-test -c 2 does not deliver any sounds, neither does the phoniebox gui. 

I just figured out that the startup sound is working, but nothing else. Same issue like here https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/261 Does anybody know which GPIO Buttons to change or how to find that out?

EDIT:
When uncommenting all GPIO's the test sounds work, but not playing music via phoniebox web gui.

**Comment by MiczFlor** [comment]
Hi @Howl1n 
please have a look here, see if this helps:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Troubleshooting-FAQ#hifiberry-dac-soundcard-details
Another issue, sometimes reported, relates to the GPIO buttons, there could be a conflict that the soundcard uses pins which are also used by the gpio buttons script. Try disabling the gpio script in the web UI under settings and see if that makes a difference?

**Comment by saschaschefenacker** [comment]
Yes @MiczFlor I tried that as well - without success :(

**Comment by Howl1n** [comment]
Disabling it in the webgui did not help, but changing it in the config did just solve it:

sudo nano /home/pi/RPi-Jukebox-RFID/scripts/gpio-buttons.py

and

#shut = Button(3, hold_time=2)
#vol0 = Button(13,pull_up=True)
#volU = Button(16,pull_up=True,hold_time=0.3,hold_repeat=True)
#volD = Button(19,pull_up=True,hold_time=0.3,hold_repeat=True)
#next = Button(26,pull_up=True)
#prev = Button(20,pull_up=True)
#halt = Button(21,pull_up=True)
#reco = Button(6, pull_up=True) # Choose GPIO to fit your hardware
#play = Button(12,pull_up=True) # Choose GPIO to fit your hardware

I am figuring out in the following days how to get this in line with using the buttons and let you know as soon as I get any further. Maybe the standard GPIO referal can be changed?

**Comment by Howl1n** [comment]
I need to revise my previous post. The solution is already mentioned in the gpio-buttons-py. It says:

# This script will block any I2S DAC e.g. from Hifiberry, Justboom, ES9023, PCM5102A
# due to the assignment of GPIO 19 and 21 to a buttons

Consequently I changed GPIO's 19 and 21 to 2 and 4 --> everything works! When using these buttons you just need to use the right pins... 

The changed /home/pi/RPi-Jukebox-RFID/scripts/gpio-buttons.py to whom it might help:

def def_volD():
    check_call("./scripts/playout_controls.sh -c=volumedown", shell=True)

def def_vol0():
    check_call("./scripts/playout_controls.sh -c=mute", shell=True)

def def_next():
    check_call("./scripts/playout_controls.sh -c=playernext", shell=True)

def def_prev():
    check_call("./scripts/playout_controls.sh -c=playerprev", shell=True)

def def_halt():
    check_call("./scripts/playout_controls.sh -c=playerpause", shell=True)

def def_recordstart():
    check_call("./scripts/playout_controls.sh -c=recordstart", shell=True)

def def_recordstop():
    check_call("./scripts/playout_controls.sh -c=recordstop", shell=True)

def def_recordplaylatest():
    check_call("./scripts/playout_controls.sh -c=recordplaylatest", shell=True)

shut = Button(3, hold_time=2)
vol0 = Button(13,pull_up=True)
volU = Button(16,pull_up=True,hold_time=0.3,hold_repeat=True)
**volD = Button(2,pull_up=True,hold_time=0.3,hold_repeat=True)**
next = Button(26,pull_up=True)
prev = Button(20,pull_up=True)
**halt = Button(4,pull_up=True)**
#reco = Button(6, pull_up=True) # Choose GPIO to fit your hardware
#play = Button(12,pull_up=True) # Choose GPIO to fit your hardware

shut.when_held = def_shutdown
vol0.when_pressed = def_vol0
volU.when_pressed = def_volU
#When the Volume Up button was held for more than 0.3 seconds every 0.3 seconds he will call a ra$
volU.when_held = def_volU
volD.when_pressed = def_volD
#When the Volume Down button was held for more than 0.3 seconds every 0.3 seconds he will lower t$
volD.when_held = def_volD
next.when_pressed = def_next
prev.when_pressed = def_prev
halt.when_pressed = def_halt
#reco.when_pressed = def_recordstart
#reco.when_released = def_recordstop
#play.when_pressed = def_recordplaylatest

pause()

Thanks for this great project @MiczFlor You made a lot of kids really happy, hopefully mine too very soon :)
