### ISSUE TITLE
No Sound ,No Volume 

### ISSUE THREAD

**Issue by Marmi86** [MiczFlor/RPi-Jukebox-RFID#595]
Hello,
I've installed phoniebox with spotify Support,but the Box Play no Music with the linked tags and i can’t change the Volume .
I testing spotify local music YouTube
I  created the playlists folder   with 777 authorization,no success
The RFID Reader works,I see  the rfid Code in the webgui and can link the Music with the tags
USB Sound works with Spotify Iris and Startup Sound 

My Hardware
Raspian Stretch lite
Raspberry Pi 2
USB Sound Card 
RC522 RFID Reader 
newest one click installer for Raspian Stretch

**Comment by MiczFlor** [comment]
Hi @Marmi86 
did you mix the stretch OS with the buster install script?
Currently, both options are available. If you use the stretch OS, you need to run this install script:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/INSTALL-stretch#raspbian-stretch

**Comment by MiczFlor** [comment]
There was no answer, silence for a month, I am closing this thread.
