### ISSUE TITLE
One script not working for spotify edition #buster & stretch

### ISSUE THREAD

**Issue by Noobelisk** [MiczFlor/RPi-Jukebox-RFID#601]
Hi, 
First things first: Wonderful Project! 
I installed Phoniebox on Raspian Stretch (which was working fine) and crashed it after playing around with some settings.  so I tried to restart from scratch with Buster. 
Unfortunatly the one line script is not working for Spotify edition any more: Installation is running fine, but there is no possibility to reach Iris any more in the webinterface - insted webinterface says "classic". 
I tried with Stretch (and according one line script) again and had the same issue. 
Script asks about credential for spotify, but in the web application it says "Phoniebox Classic". 

Can you please verify this issue and - in the best case - correct it?

**Comment by MiczFlor** [comment]
Ah, good catch. Let me check.

**Comment by MiczFlor** [comment]
Hi @Noobelisk 
could you do me a favour and manually edit the file 
~~~
RPi-Jukebox-RFID/settings/global.conf
~~~
Please change the EDITION line to:
~~~
EDITION="plusSpotify"
~~~

**Comment by MiczFlor** [comment]
And @Noobelisk while you are at it, could you tell me what this returns?
~~~
cat RPi-Jukebox-RFID/settings/edition
~~~

**Comment by Noobelisk** [comment]
Hi MiczFlor,
thx for your fast reply: 
Without tweaking the global.conf: 
`cat /home/pi/RPi-Jukebox-RFID/settings/edition`
plusSpotify

EDITION in global.conf was "classic" - after changing to  
`EDITION="plusSpotify"`
**everything works!** (Iris reachable and doing fine)

Thanks!!
currently running in STRETCH. Issue closed.
