### ISSUE TITLE
Schedule for shutdown

### ISSUE THREAD

**Issue by oneshow01** [MiczFlor/RPi-Jukebox-RFID#608]
Is there a way to setup schedule for shutdown? 
I'd like the box to shut down itself in the evening (or at certain times).

At the moment it is connected to a TP-Link Smart Plug which turns the box off and on. This is only power on/off without shutting down. I would like to avoid that.

I think this would be a nice feature... similar to the [Smart Plug Schedule](https://www.tp-link.com/us/support/faq/947/)

![2_1557713538453r](https://user-images.githubusercontent.com/56823158/67194816-1f0e9880-f3f8-11e9-9962-723d57fe8d04.png)

Thank you

**Comment by dnmtch** [comment]
you could use this from the command line:

`sudo shutdown -h 03:30`
(or google cron job shutdown)

or use hardware:
https://www.lifehacker.co.uk/2015/11/20/how-to-boot-and-shut-down-your-raspberry-pi-safely-and-more-effectively
http://www.uugear.com/product/witty-pi-3-realtime-clock-and-power-management-for-raspberry-pi/

**Comment by MiczFlor** [comment]
Hi @oneshow01 
nice feature request. I will see if I find time to do that. The shutdown options available at the moment are only
* stop player after x minutes
* shutdown after x minutes
* shutdown after x minutes of idle time
@dnmtch pointed you to the right searches. Thanks for that.

**Comment by andreasbrett** [comment]
If you already have a smart home solution you might also choose to use the mqtt module and shut down your phoniebox from your smart home server.

https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Smart-Home-remote-control-with-MQTT

**Comment by UndIch** [comment]
So is there any progress in this request? Especially the one “shutdown down after idle time” to safe battery? Something like “after 15 min without any song played shutdown?”

**Comment by andreasbrett** [comment]
> So is there any progress in this request? Especially the one “shutdown down after idle time” to safe battery? Something like “after 15 min without any song played shutdown?”

That is exactly what the idle shutdown is doing. Set the idle timer to 15 min and you got what you asked for.

**Comment by UndIch** [comment]
Stupid me. After having some
Installation problems (see other thread) and using some old versions for a while I didn’t realize this cool and helpful new feature! Sorry for this...

**Comment by s-martin** [comment]
Already implemented in V2.

Implementation for V3 will be tracked in #1970 (scheduled for[v3.6](https://github.com/MiczFlor/RPi-Jukebox-RFID/milestone/10))
