### ISSUE TITLE
no cover displayed (2.0 rc4)

### ISSUE THREAD

**Issue by Hoschi523** [MiczFlor/RPi-Jukebox-RFID#610]
I've got the problem that there is no cover displayed. I've checked the rights, the owner/group and also the spelling of the file (cover.jpg). It all seems correct. 
No different between local files or streams from spotify.

What I'm doing wrong?

Thanks 
Hoschi

**Comment by mawo66** [comment]
I have the same problem.

**Comment by ctietze** [comment]
_**ZyanKLee**_ already provided a fix and created a pull request regarding this issue. See 
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/620

BR Clemens
