### ISSUE TITLE
No spotify in buster

### ISSUE THREAD

**Issue by r00tr4v3n** [MiczFlor/RPi-Jukebox-RFID#613]
After installing the buster version and providing the Spotify credentials there is no Spotify menu in the webinterface.

************************************
*** PHONIEBOX INFO
*** version: 2.0 rc4
*** **edition: classic**
*** Audio_iFace_Name: PCM
*** Audio_Folders_Path: /home/pi/RPi-Jukebox-RFID/shared/audiofolders
*** Audio_Volume_Change_Step: 3
*** Max_Volume_Limit: 100
*** Idle_Time_Before_Shutdown: 0
*** Second_Swipe: RESTART
*** Playlists_Folders_Path: /home/pi/RPi-Jukebox-RFID/playlists
*** ShowCover: ON
************************************
*** CONF FILES DEFAULT
 
*** /etc/samba/smb.conf
-rw-r--r-- 1 root root 8.2K Oct 23 13:49 /etc/samba/smb.conf
   path=/home/pi/RPi-Jukebox-RFID/shared
   path=/home/pi/RPi-Jukebox-RFID/shared/audiofolders
*** /etc/lighttpd/lighttpd.conf
-rw-r--r-- 1 root root 2.1K Oct 23 13:49 /etc/lighttpd/lighttpd.conf
*** /etc/lighttpd/conf-available/15-fastcgi-php.conf
-rw-r--r-- 1 root root 575 Oct 23 13:49 /etc/lighttpd/conf-available/15-fastcgi-php.conf
*** /etc/php/7.0/fpm/php.ini
ls: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
*** /etc/sudoers
-r--r----- 1 root root 784 Oct 23 13:49 /etc/sudoers
*** /etc/systemd/system/phoniebox*
-rw-r--r-- 1 root root 296 Oct 23 13:49 /etc/systemd/system/phoniebox-rfid-reader.service
-rw-r--r-- 1 root root 340 Oct 23 13:49 /etc/systemd/system/phoniebox-startup-sound.service
-rw-r--r-- 1 root root 289 Oct 23 13:49 /etc/systemd/system/phoniebox-gpio-buttons.service
-rw-r--r-- 1 root root 291 Oct 23 13:49 /etc/systemd/system/phoniebox-idle-watchdog.service
*** /etc/mpd.conf
-rw-r----- 1 mpd audio 14K Oct 23 13:50 /etc/mpd.conf
music_directory		"/home/pi/RPi-Jukebox-RFID/shared/audiofolders"
# music_directory are changed.
# symbolic links outside of the configured music_directory.
# symbolic links inside of the configured music_directory.
	mixer_control	"PCM"		# optional
#	mixer_control	"PCM"		# optional
*** /etc/dhcpcd.conf
-rw-rw-r-- 1 root netdev 1.8K Jan 24  2019 /etc/dhcpcd.conf
#static ip_address=192.168.0.10/24
#static ip_address=192.168.1.23/24
#static routers=192.168.0.1
#static routers=192.168.1.1
option domain_name_servers, domain_name, domain_search, host_name
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
#static domain_name_servers=192.168.1.1
*** /etc/wpa_supplicant/wpa_supplicant.conf
-rw------- 1 root root 167 Oct 23 12:22 /etc/wpa_supplicant/wpa_supplicant.conf
country=DE
************************************
*** +Spotify Edition
 
*** /etc/locale.gen
-rw-r--r-- 1 root root 8.9K Oct 23 13:50 /etc/locale.gen
*** /etc/locale.gen
-rw-r--r-- 1 root root 8.9K Oct 23 13:50 /etc/locale.gen
*** /etc/mopidy/mopidy.conf
-rw-r----- 1 mopidy root 1.1K Oct 23 13:50 /etc/mopidy/mopidy.conf
username = %username%
*** ~/.config/mopidy/mopidy.conf
-rw-r--r-- 1 root root 3.3K Oct 23 13:50 /home/pi/.config/mopidy/mopidy.conf
#username =

**Comment by MiczFlor** [comment]
Hi @r00tr4v3n 
true. my mistake. Please type the following lines in the terminal:
~~~
echo "plusSpotify" > /home/pi/RPi-Jukebox-RFID/settings/edition
rm /home/pi/RPi-Jukebox-RFID/settings/global.conf
~~~
I am working on a fix of the install script. thanks
