### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by varac** [MiczFlor/RPi-Jukebox-RFID#629]
Please release a new version, [1.1.9](https://github.com/MiczFlor/RPi-Jukebox-RFID/releases/tag/v1.1.9) is already more than half a year old. Thanks !

**Comment by MiczFlor** [comment]
Hi @varac 
what you say is very true. At some point I just went with the git way and did just upgrade the code base without releasing new versions for download. Version 2.0 is underway and I will do as you suggest. Once it's stable and released, I will make a "proper" release with a download.
Thanks and all the best, micz

**Comment by varac** [comment]
Great, thanks !
