### ISSUE TITLE
Update 1.1.9 to 2.0 - will I break all my settings?

### ISSUE THREAD

**Issue by matthias2468** [MiczFlor/RPi-Jukebox-RFID#630]
Hello,
I have a lovely phoniebox running for a while now. Now there is the 2.0 and I am worried that if I just start the one line installation all my settings will be gone afterwards. Is that so or  is there no reason to worry?
I am okay with entering the wifi code once more but I don't want to mess with the buttons and all that again - it's been a while and since I am not at all a linux guy this is pretty far off my daily routines...
Thanks for your feedback!
Matthias

**Comment by MiczFlor** [comment]
HI @matthias2468 
for the time being: why change a running system? :) ? we are currently rewriting a few things in the web app. Possibly wait until the release 2 is not "rc" (= release candidate) anymore.
