### ISSUE TITLE
Is there a changelog for version 2? Should I upgrade from version 1?

### ISSUE THREAD

**Issue by Hamsert** [MiczFlor/RPi-Jukebox-RFID#638]
Pretty much topic. What are the changes from version 1 to version 2 and should I upgrade? If so, will it be better of to make a new installation, or is there a way to upgrade the current system?

**Comment by MiczFlor** [comment]
Hi @Hamsert 
Version 2 is still in development - and a "release candidate". For the time being, hold back :) I will announce the stable release in the README and on twitter.

The two major improvements for version 2 will be an [ajax interface in the web app](https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/623), making it more fun to use (needs testing still) and the [remote control integration with smart homes](https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Smart-Home-remote-control-with-MQTT). See the [long list of commits here](https://github.com/MiczFlor/RPi-Jukebox-RFID/commits/master).

The install script "should" detect your existing installation and ask you to use the existing audio archive, RFID connections, config and so on. It works for me, but it might not for everyone. I will work on a bit of text in the wiki explaining how to do this.

I plan to merge the latest rc to master soon. Then I need some testing. If you have a second SD card, feel free to join in :)
