### ISSUE TITLE
Support of EAN Scanner

### ISSUE THREAD

**Issue by Luegengladiator** [MiczFlor/RPi-Jukebox-RFID#65]
EAN Codes are much simpler to create and are almost everywhere (CD, Tape, aso.)

**Comment by Luegengladiator** [comment]
Created a Project in Fork.
Pull Request when done

**Comment by MiczFlor** [comment]
* Would this require an optical reader / camera? 
* Would this allow to use the existing codes on products?

**Comment by Luegengladiator** [comment]
Yes this is the Idea behind that. 
Use the existing EAN-Codes and yes a camera/ean-scanner is needed.

**Comment by Luegengladiator** [comment]
Worked out of the box.
Register EAN Scanner with the RegisterDevice.py
There are 2 Prerequisites:
1) The Scanner has to send Carriage Return after reading
2) The Scanner has to work as USB-Keyboard as STDIN
most of the Barcodescanner can be configured. Please see the device Handbook.

**Comment by Luegengladiator** [comment]
@MiczFlor 
finished this one.
All my RFID-Cards now get additional EAN Codes on the back. So I can run 2 Jukeboxes with different input devices with only one definition. (cloning the Raspberry SD)
