### ISSUE TITLE
SONOS Integration

### ISSUE THREAD

**Issue by oneshow01** [MiczFlor/RPi-Jukebox-RFID#650]
Hi,
Has anyone already managed to integrate the Phoniebox into the Sonos system/ audio output --> Sonos speakers?

Similar to this project, unfortunately I don't have the knowledge to connect with it.
https://github.com/chrispcampbell/qrocodile

Thanks

**Comment by sassen** [comment]
@oneshow01 have a look to this https://github.com/maddox/magic-cards
I have it up and running on a Rpi Zero W and integrated with Sonos.

**Comment by oneshow01** [comment]
Hello, sounds interesting. Thanks to you!
But I would prefer to solve this with my existing Phoniebox, I love this box....

**Comment by sassen** [comment]
I see, lets see if anyone here knows how to integrate Sonos with Phoniebox. I would be interested, I miss the GPIO integration in my current setup.

**Comment by UndIch** [comment]
I think it was discussed in #499 - you might want to check on that.

**Comment by s-martin** [comment]
Closing as duplicate.
