### ISSUE TITLE
Missing Feature Delete Directory

### ISSUE THREAD

**Issue by Hans-Haefner** [MiczFlor/RPi-Jukebox-RFID#651]
I miss a way to delete an entire directory or I just overlook what?

**Comment by ctietze** [comment]
Hi @Hans-Haefner ,
as far as I know deleting folders is only possible via SSH or via SAMBA. Within the webapp you can only delete single tracks.

BR Clemens

**Comment by Hans-Haefner** [comment]
Would be nice if something would be installed, there are aspirations to it?

**Comment by MiczFlor** [comment]
Yep, would be nice, won't be this christmas, though ;)

**Comment by Ardios** [comment]
Hey all,

at first, sorry for my broken english.

@Hans-Haefner 
I added a file manager maybe it will help you, here is the link:

[https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/510](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/510)

**Comment by Erechtheus** [comment]
@Ardios It might make sense to add your file manager as a pull request?  

BTW: Duplicate of #380

**Comment by s-martin** [comment]
Closing as it’s a duplicate of #380
