### ISSUE TITLE
This is probably supposed to be a comment?

### ISSUE THREAD

**Issue by dertobes** [MiczFlor/RPi-Jukebox-RFID#655]
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/6915db203ad8aa36d665001fde0ab96845cc852b/scripts/installscripts/buster-install-default.sh#L496

getting this warning during install:
`./buster-install-default.sh: line 496: move: command not found`

**Comment by Hans-Haefner** [comment]
Did you do that before? "sudo chmod +x buster-install-default.sh" ?

**Comment by toto79** [comment]
There is nothing to do, exept to spend a '#' at the beginning of line 496. 
Its only a comment, there is nothing to move :)

**Comment by dertobes** [comment]
Sorry I'm not super fluent in Git. I was hoping there would be a simple way to submit code change suggestions without creating a fork etc so I figured a simple "issue" would do the trick.

**Comment by MiczFlor** [comment]
Yes, this was meant to be a comment :) thanks for catching a confusing but :)
