### ISSUE TITLE
Use APT as installer

### ISSUE THREAD

**Issue by Luegengladiator** [MiczFlor/RPi-Jukebox-RFID#66]
Simplify the Installation process with requirements and default Installer Pakages for RPi

**Comment by Luegengladiator** [comment]
Created Project in Fork.
Pull Request when done

**Comment by MiczFlor** [comment]
I wouldn't mind if this exists, but I am not sure what that would entail for future development. Also, there are so many "manual" steps (Wifi, RFID reader type, samba config, ssh password) that I am not sure what the apt-get would look like. But, hey, go ahead, I love to learn something new.

**Comment by Luegengladiator** [comment]
I think configuration is a more or less manual part. We can ask a few things during installation like "which player" or "do you use EAN or RFID" or something like that.
But there are many prerequisites to run without problems. So I think it's nice to install the Phonie with apt-get install RPi-Jukebox-RFID and all the requirements (samba, tmux, at, ssh, ...) are installed automatically....

**Comment by MiczFlor** [comment]
Welcome @Luegengladiator as our packet manager :+1: :)

**Comment by Luegengladiator** [comment]
I think i'll need time on that. 
Usually I'm building RPMs and I have to figure out how to build an apt-package

**Comment by Luegengladiator** [comment]
Only nice to have
