### ISSUE TITLE
Installation funzt nicht

### ISSUE THREAD

**Issue by mimi-ac** [MiczFlor/RPi-Jukebox-RFID#661]
Hallo zusammen,

ich habe heute meine Raspberry 
* mit Raspbian Buster Lite installiert
* SSH eingerichtet
* Wlan eingerichtet und dann
* versucht Phoniebox zu installieren.

Nachfolgend das Ergebnis:

`#####################################################
#
# START INSTALLATION
#
# Good news: you completed the input.
# Let the install begin.
#
# Get yourself a cup of something. The install takes
# between 15 minutes to half an hour, depending on
# your Raspberry Pi and Internet connectivity.
#
# You will be prompted later to complete the installation.

Do you want to start the installation? [Y/n] Y
Error for wireless request "Set Power Management" (8B2C) :
    SET failed on device wlan0 ; Operation not permitted.
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian buster InRelease [25.2 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0                                                                                                                                                              MB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf Packages [260 kB]
Fetched 13.3 MB in 41s (324 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'linux-headers-4.9.0-6-all' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-rpi' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-all-armhf' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-rpi2' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-common' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-common-rt' for regex 'linux-headers-4.9'
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package php7.0-common is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

W: --force-yes is deprecated, use one of the options starting with --allow inste                                                                                                                                                             ad.
E: Package 'php7.0-common' has no installation candidate
E: Unable to locate package php7.0-cgi
E: Couldn't find any package by glob 'php7.0-cgi'
E: Couldn't find any package by regex 'php7.0-cgi'
E: Unable to locate package php7.0-fpm
E: Couldn't find any package by glob 'php7.0-fpm'
E: Couldn't find any package by regex 'php7.0-fpm'
./stretch-install-default.sh: line 394: git: command not found
./stretch-install-default.sh: line 396: cd: RPi-Jukebox-RFID: No such file or di                                                                                                                                                             rectory
./stretch-install-default.sh: line 397: git: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
Error for wireless request "Set Power Management" (8B2C) :
    SET failed on device wlan0 ; Operation not permitted.
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/smb.conf.stretch-d                                                                                                                                                             efault2.sample': No such file or directory
chown: cannot access '/etc/samba/smb.conf': No such file or directory
chmod: cannot access '/etc/samba/smb.conf': No such file or directory
sed: can't read /etc/samba/smb.conf: No such file or directory
sudo: smbpasswd: command not found
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/lighttpd.conf.stre                                                                                                                                                             tch-default.sample': No such file or directory
chown: cannot access '/etc/lighttpd/lighttpd.conf': No such file or directory
chmod: cannot access '/etc/lighttpd/lighttpd.conf': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/15-fastcgi-php.con                                                                                                                                                             f.stretch-default.sample': No such file or directory
chown: cannot access '/etc/lighttpd/conf-available/15-fastcgi-php.conf': No such                                                                                                                                                              file or directory
chmod: cannot access '/etc/lighttpd/conf-available/15-fastcgi-php.conf': No such                                                                                                                                                              file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/php.ini.stretch-de                                                                                                                                                             fault.sample': No such file or directory
chown: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
chmod: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/sudoers.stretch-de                                                                                                                                                             fault.sample': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/settings/rfid_trigger_play.conf.sampl                                                                                                                                                             e': No such file or directory
./stretch-install-default.sh: line 454: /home/pi/RPi-Jukebox-RFID/settings/Audio                                                                                                                                                             _iFace_Name: No such file or directory
./stretch-install-default.sh: line 455: /home/pi/RPi-Jukebox-RFID/settings/Audio                                                                                                                                                             _Folders_Path: No such file or directory
./stretch-install-default.sh: line 456: /home/pi/RPi-Jukebox-RFID/settings/Audio                                                                                                                                                             _Volume_Change_Step: No such file or directory
./stretch-install-default.sh: line 457: /home/pi/RPi-Jukebox-RFID/settings/Max_V                                                                                                                                                             olume_Limit: No such file or directory
./stretch-install-default.sh: line 458: /home/pi/RPi-Jukebox-RFID/settings/Idle_                                                                                                                                                             Time_Before_Shutdown: No such file or directory
./stretch-install-default.sh: line 459: /home/pi/RPi-Jukebox-RFID/settings/Secon                                                                                                                                                             d_Swipe: No such file or directory
./stretch-install-default.sh: line 460: /home/pi/RPi-Jukebox-RFID/settings/Playl                                                                                                                                                             ists_Folders_Path: No such file or directory
./stretch-install-default.sh: line 461: /home/pi/RPi-Jukebox-RFID/settings/ShowC                                                                                                                                                             over: No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/htdocs/config.php.sample': No such fi                                                                                                                                                             le or directory
sudo: lighttpd-enable-mod: command not found
sudo: lighttpd-enable-mod: command not found
Failed to restart lighttpd.service: Unit lighttpd.service not found.
Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/gpio-buttons.py.sa                                                                                                                                                             mple': No such file or directory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/gpio-buttons.py': No suc                                                                                                                                                             h file or directory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.sh': No such file or d                                                                                                                                                             irectory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.sh': No such file or d                                                                                                                                                             irectory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.py': No such file or d                                                                                                                                                             irectory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.py': No such file or d                                                                                                                                                             irectory
### Deleting older versions of service daemons. This might throw errors, ignore                                                                                                                                                              them
Failed to disable unit: Unit file idle-watchdog.service does not exist.
Failed to disable unit: Unit file rfid-reader.service does not exist.
Failed to disable unit: Unit file startup-sound.service does not exist.
Failed to disable unit: Unit file gpio-buttons.service does not exist.
rm: cannot remove '/etc/systemd/system/rfid-reader.service': No such file or dir                                                                                                                                                             ectory
rm: cannot remove '/etc/systemd/system/startup-sound.service': No such file or d                                                                                                                                                             irectory
rm: cannot remove '/etc/systemd/system/gpio-buttons.service': No such file or di                                                                                                                                                             rectory
rm: cannot remove '/etc/systemd/system/idle-watchdog.service': No such file or d                                                                                                                                                             irectory
### Done with erasing old daemons. Stop ignoring errors!
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/phoniebox-rfid-rea                                                                                                                                                             der.service.stretch-default.sample': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/phoniebox-startup-                                                                                                                                                             sound.service.stretch-default.sample': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/phoniebox-gpio-but                                                                                                                                                             tons.service.stretch-default.sample': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/phoniebox-idle-wat                                                                                                                                                             chdog.service.sample': No such file or directory
chown: cannot access '/etc/systemd/system/phoniebox-rfid-reader.service': No suc                                                                                                                                                             h file or directory
chown: cannot access '/etc/systemd/system/phoniebox-startup-sound.service': No s                                                                                                                                                             uch file or directory
chown: cannot access '/etc/systemd/system/phoniebox-gpio-buttons.service': No su                                                                                                                                                             ch file or directory
chown: cannot access '/etc/systemd/system/phoniebox-idle-watchdog.service': No s                                                                                                                                                             uch file or directory
chmod: cannot access '/etc/systemd/system/phoniebox-rfid-reader.service': No suc                                                                                                                                                             h file or directory
chmod: cannot access '/etc/systemd/system/phoniebox-startup-sound.service': No s                                                                                                                                                             uch file or directory
chmod: cannot access '/etc/systemd/system/phoniebox-gpio-buttons.service': No su                                                                                                                                                             ch file or directory
chmod: cannot access '/etc/systemd/system/phoniebox-idle-watchdog.service': No s                                                                                                                                                             uch file or directory
Failed to enable unit: Unit file phoniebox-idle-watchdog.service does not exist.
Failed to enable unit: Unit file phoniebox-rfid-reader.service does not exist.
Failed to enable unit: Unit file phoniebox-startup-sound.service does not exist.
Failed to enable unit: Unit file phoniebox-gpio-buttons.service does not exist.
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/startupsound.mp3.s                                                                                                                                                             ample': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/shutdownsound.mp3.                                                                                                                                                             sample': No such file or directory
cp: cannot stat '/home/pi/RPi-Jukebox-RFID/misc/sampleconfigs/mpd.conf.sample':                                                                                                                                                              No such file or directory
sed: can't read /etc/mpd.conf: No such file or directory
sed: can't read /etc/mpd.conf: No such file or directory
./stretch-install-default.sh: line 529: /home/pi/RPi-Jukebox-RFID/settings/editi                                                                                                                                                             on: No such file or directory
chown: invalid user: ‘mpd:audio’
chmod: cannot access '/etc/mpd.conf': No such file or directory
./stretch-install-default.sh: line 533: mpc: command not found
Warning: The unit file, source configuration file or drop-ins of dhcpcd.service                                                                                                                                                              changed on disk. Run 'systemctl daemon-reload' to reload units.
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd                                                                                                                                                             /systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable dhcpcd
mkdir: cannot create directory ‘/home/pi/RPi-Jukebox-RFID/playlists’: No such fi                                                                                                                                                             le or directory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/playlists': No such file or dire                                                                                                                                                             ctory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/playlists': No such file or dire                                                                                                                                                             ctory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/shared': No such file or directo                                                                                                                                                             ry
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/shared': No such file or directo                                                                                                                                                             ry
chown: cannot access '/home/pi/RPi-Jukebox-RFID/htdocs': No such file or directo                                                                                                                                                             ry
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/htdocs': No such file or directo                                                                                                                                                             ry
chown: cannot access '/home/pi/RPi-Jukebox-RFID/settings': No such file or direc                                                                                                                                                             tory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/settings': No such file or direc                                                                                                                                                             tory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/shared/audiofolders': No such fi                                                                                                                                                             le or directory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/shared/audiofolders': No such fi                                                                                                                                                             le or directory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.sh': No such file or d                                                                                                                                                             irectory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.sh': No such file or d                                                                                                                                                             irectory
chown: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.py': No such file or d                                                                                                                                                             irectory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/*.py': No such file or d                                                                                                                                                             irectory
amixer: Cannot find the given element from control default

#
# INSTALLATION FINISHED
#
#####################################################

If you are using an USB RFID reader, connect it to your RPi.
(In case your RFID reader required soldering, consult the manual.)
Have you connected your USB Reader? [Y/n] Y
./stretch-install-default.sh: line 693: cd: /home/pi/RPi-Jukebox-RFID/scripts/:                                                                                                                                                              No such file or directory
python2: can't open file 'RegisterDevice.py': [Errno 2] No such file or director                                                                                                                                                             y
chown: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/deviceName.txt': No such                                                                                                                                                              file or directory
chmod: cannot access '/home/pi/RPi-Jukebox-RFID/scripts/deviceName.txt': No such                                                                                                                                                              file or directory

DONE. Let the sounds begin.
Find more information and documentation on the github account:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/
`

Was mache ich falsch?

Grüße und Danke

Christian

**Comment by kabakakao** [comment]
Für mich sieht es so aus, als hättest du das Script für Debian Stretch benutzt und nicht das für Buster.
In deinem Logauszug wird nämlich versucht php-fpm7.0 zu installieren. Bei Buster wird aber php-fpm7.3 mitgeliefert.
Probiere mal folgenden Aufruf:
`cd; rm buster-install-*; wget https://raw.githubusercontent.com/MiczFlor/RPi-Jukebox-RFID/master/scripts/installscripts/buster-install-default.sh; chmod +x buster-install-default.sh; ./buster-install-default.sh`

**Comment by mimi-ac** [comment]
Super, das hat erst mal funktioniert. Danke

**Comment by kabakakao** [comment]
Sehr gut. Schließt du dann das Issue? Es wird hier sonst sehr unübersichtlich.
