### ISSUE TITLE
Multiple RFID reader possible?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [MiczFlor/RPi-Jukebox-RFID#665]
Hi guys,
is it possible to use multiple RFID-reader for this awesome project?

I plan to use two RFID readers:
- first one acts as "playlist" select (so you need to press play button)
- second one as default (play what's behind the ID)

If it is not yet done, I will dig into the source code...

**Comment by s-martin** [comment]
Closing as duplicate, see #760 for further development
