### ISSUE TITLE
Pause/Stop playback if card is removed

### ISSUE THREAD

**Issue by joshwapohlmann** [MiczFlor/RPi-Jukebox-RFID#684]
I found that it can be more intuitive to a child, to place the card and let it rest on the box as long as it wishes to listen to the story/song. The expectation is, that the playback stops when the card is removed.

Therefore I would like to have the option to enable this behavior (maybe selectable in the web apps settings page).

**Comment by joshwapohlmann** [comment]
related #572

**Comment by joshwapohlmann** [comment]
I'd love working on this, solving #683 first would help :)

**Comment by Erechtheus** [comment]
I would also like to participate on this issue. Similar to @joshwapohlmann I am not sure how to contribute. As far as I understood the problem is that Reader.py is only called when a RFID-chip is present. So implementing this issue probably requires some kind of watchdog, which regularly  (every second or so) checks if a RFID-card is no longer present and than pauses?

**Comment by joshwapohlmann** [comment]
@Erechtheus I'm working on #683 right now and link to the result so we both might get to a mutual understanding what and how to do. :)

**Comment by ozone89** [comment]
just leaving my two cents, the [Phidgets 1024 RFID](https://www.phidgets.com/?&prodid=23) reader supports reporting of card presence in their APIs:
```
getTagPresent()

```

This property is true if a compatibile RFID tag is being read by the reader.

- TagPresent will remain true until the tag is out of range and can no longer be read.

```
void onTagLost(self, tag, protocol)
```
Occurs when an RFID tag that was being read is removed from the read range.

**Comment by UndIch** [comment]
Thats a great function - but comes with a huge price tag... 60 $ for a RFID reader is quite a lot to ask for...

**Comment by ozone89** [comment]
> Thats a great function - but comes with a huge price tag... 60 $ for a RFID reader is quite a lot to ask for...

true, but maybe it's just a software feature in libphidget that could be implemented?

**Comment by dermexx** [comment]
a cheap solution for that problem is to use a reed switch that you place close to the rfid reader...
only downside is, that you have to add a magnet to every tag you want to use.

**Comment by s-martin** [comment]
Is already implemented.

For V3 see e.g. here https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/main/documentation/developers/rfid/basics.md#place_not_swipe-true--false
