### ISSUE TITLE
Feature request: normalize volume of audiofiles

### ISSUE THREAD

**Issue by kabakakao** [MiczFlor/RPi-Jukebox-RFID#685]
It would be nice to "normalize" die imported Audiofiles.
https://packages.debian.org/buster/normalize-audio
So you normally don't have to change the volume.

eg:
`find /home/pi/RPi-Jukebox-RFID/shared/audiofolders/ -name *.mp3 -print0 | xargs -0 normalize`

**Comment by MiczFlor** [comment]
Hi @kabakakao 
I agree, and am normalizing and transcoding files on my laptop before placing them on the Phoniebox. But I am not sure that the Phoniebox is the place to do this. Do you? It takes a lot of capacity

**Comment by kabakakao** [comment]
I agree that it would take high performance, but i think it is a good place to do that. I think a Button Or Option in the Web Interface would be good. So everyone can decide on his own.

**Comment by belinea4071** [comment]
I changed the setting in "/etc/mpd.conf",
**from**: volume_normalization            **"no"**
**to**: volume_normalization            **"yes"**.

_This setting enables on-the-fly normalization volume adjustment. This will
result in the volume of all playing audio to be adjusted so the output has
equal "loudness". This setting is disabled by default._

This did the trick for me.
