### ISSUE TITLE
fatal error during install of one-linescript -- "fatal error: libspotify/api.h: No such file or directory  #include "libspotify/api.h"

### ISSUE THREAD

**Issue by felixlindemann** [MiczFlor/RPi-Jukebox-RFID#689]
this error
`build/temp.linux-armv7l-3.7/spotify._spotify.c:492:10: fatal error: libspotify/api.h: No such file or directory  #include "libspotify/api.h"           ^~~~~~~~~~~~~~~~~~ compilation terminated.`
 

Was solved by installing libspotify-dev before executing one-line script.

`sudo apt-get install libspotify-dev`

--> Please consider adding this to the online-Script

**Comment by MiczFlor** [comment]
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/696
