### ISSUE TITLE
next ist eine python Standardfunktion

### ISSUE THREAD

**Issue by splitti** [MiczFlor/RPi-Jukebox-RFID#694]
In der gpio-buttons.py wird die Variable next verwendet. Diese Variable ist eine allgemein gültige [python-Funktionalität](https://www.w3schools.com/python/ref_func_next.asp). Bitte anpassen, z.B. nach button_next...
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/103ef65a78cc86c29ea984e5f5ed7a9f392a35d7/misc/sampleconfigs/gpio-buttons.py.sample#L56
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/103ef65a78cc86c29ea984e5f5ed7a9f392a35d7/misc/sampleconfigs/gpio-buttons.py.sample#L70

**Comment by s-martin** [comment]
I think that’s already fixed.

**Comment by s-martin** [comment]
Fixed in https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/2694597c11fae61054dac7ed2eb311880396512e
