### ISSUE TITLE
Web app: control buttons too small

### ISSUE THREAD

**Issue by zxa** [MiczFlor/RPi-Jukebox-RFID#70]
On my Android device it's hard to hit the right button for the player control because they are pretty small (and i'm in the believe to not have abnormal fat fingers ;-).

Is this different on Apple devices?

As i'm working on the Web App at the moment (adding a settings page) i could fix this.

**Comment by zxa** [comment]
Hi @MiczFlor,

i'll have look at that. This is how btn-lg looks like for me:
![page1](https://user-images.githubusercontent.com/188196/42275876-fd8cffc0-7f91-11e8-8e04-7f72d317cb61.png)

But before i will upload the new settings page for comments and public testing. It's optimized it for my device and it would be interesting how the Apple likes it:

![page2](https://user-images.githubusercontent.com/188196/42275878-002d0806-7f92-11e8-8ef9-4427a6b83bcd.png)

**Comment by MiczFlor** [comment]
Hi @zxa 
looks great. Can you move this to a separate settings page, like 
~~~
http://localhost/cardRegisterNew.php
~~~
?

The timed shutdown would be great to have at the top of the index page, alongside the player and volume change.

Other than that I think the front page is for playing and the settings would only be required 0.5% of the time you pull out your phone, no?

**Comment by zxa** [comment]
Hi@MiczFlor,

it's already a separate page. I have time clean up the code a bit an then i'll upload it. 

And then we need someone who writes a graphical web app configuration tool, as for example i've never used the sleep timer and need more the volume limiter and button disabler ;-)

**Comment by zxa** [comment]
Hi @MiczFlor, 

it's all here now:

https://github.com/zxa/RPi-Jukebox-RFID/tree/web-app-settings-page

Should i do a pull request or do you take it from there for testing?

**Comment by MiczFlor** [comment]
Please create a pull request. Thanks
