### ISSUE TITLE
Phonibox Installation klappt nicht

### ISSUE THREAD

**Issue by Ghostsl84** [MiczFlor/RPi-Jukebox-RFID#718]
Guten Abend,

ich versuche seit mehreren Stunden eine 2 Phoniebox aufzusetzen doch leider vergebens.
Ich nutzte einen Rapsberry Pi 3b+ mit Rasbian Buster desktop (habe es auch schon mit der Lite versucht).
Egal welchen link ich nutze zum Installieren der Phonibox (Buster, Stretch) ich bekomme es nicht zum laufen.
Der Raspberry ist an einem Kabel angeschlossen also kein Wlan.
Ich komme also nicht auf die Weboberfläche und "nameserver" hatte ich auch schon probiert und dies klappte leider auch nicht.
Ich nutze auch kein Spotify
Ich führe auch mal meine Installationsverlauf auf und hoffe das Ihr mir weiterhelfen könnt.

START INSTALLATION
#
# Good news: you completed the input.
# Let the install begin.
#
# Get yourself a cup of something. The install takes
# between 15 minutes to half an hour, depending on
# your Raspberry Pi and Internet connectivity.
#
# You will be prompted later to complete the installation.

Do you want to start the installation? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster InRelease [25.1 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf Packages [261 kB]
Fetched 13.3 MB in 8s (1,583 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'linux-headers-4.9.0-6-all' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-rpi' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-all-armhf' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-rpi2' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-common' for regex 'linux-headers-4.9'
Note, selecting 'linux-headers-4.9.0-6-common-rt' for regex 'linux-headers-4.9'
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package php7.0-common is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Package 'php7.0-common' has no installation candidate
E: Unable to locate package php7.0-cgi
E: Couldn't find any package by glob 'php7.0-cgi'
E: Couldn't find any package by regex 'php7.0-cgi'
E: Unable to locate package php7.0-fpm
E: Couldn't find any package by glob 'php7.0-fpm'
E: Couldn't find any package by regex 'php7.0-fpm'
Cloning into 'RPi-Jukebox-RFID'...
remote: Enumerating objects: 5600, done.
remote: Total 5600 (delta 0), reused 0 (delta 0), pack-reused 5600
Receiving objects: 100% (5600/5600), 16.48 MiB | 8.19 MiB/s, done.
Resolving deltas: 100% (3715/3715), done.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting evdev==0.7.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/67/15/eac376f3e1fc1960a54439c21459b2582e68340001aff83b4ace9e5bd110/evdev-0.7.0.tar.gz
Collecting spi-py from git+git://github.com/lthiery/SPI-Py.git#egg=spi-py (from -r requirements.txt (line 8))
  Cloning git://github.com/lthiery/SPI-Py.git to /tmp/pip-install-6ubahp/spi-py
Collecting youtube_dl (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/ec/4c/4aa3a86dc43623b9d5a4b0df2915908413703adc1899965c4b2e00bb8a4d/youtube_dl-2020.1.1-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 158kB/s
Requirement already satisfied: pyserial in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (3.4)
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (0.7.0)
Collecting pi-rc522 (from -r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/84/f2/e3d02257949e9caa9bff26044e0185e743ff45d3e0e099a93880e10bf718/pi-rc522-2.2.1.tar.gz
Requirement already satisfied: spidev in /usr/lib/python2.7/dist-packages (from pi-rc522->-r requirements.txt (line 13)) (3.3)
Building wheels for collected packages: evdev, spi-py, pi-rc522
  Running setup.py bdist_wheel for evdev ... done
  Stored in directory: /root/.cache/pip/wheels/a3/41/1e/95f092bf01636d415841ed521d0f15d07eb2e2e6e9f10110ff
  Running setup.py bdist_wheel for spi-py ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-mlWu18/wheels/10/00/be/9cf7629653643bb77d91c0dd14f094551768ef8e6906c63566
  Running setup.py bdist_wheel for pi-rc522 ... done
  Stored in directory: /root/.cache/pip/wheels/fa/10/f3/6d689aff6ef0b47c2b0461f80157f0f77781ac680e6b6705b9
Successfully built evdev spi-py pi-rc522
Installing collected packages: evdev, spi-py, youtube-dl, pi-rc522
Successfully installed evdev-0.7.0 pi-rc522-2.2.1 spi-py-1.0 youtube-dl-2020.1.1
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: evdev==0.7.0 in /usr/local/lib/python2.7/dist-packages (0.7.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: youtube_dl in /usr/local/lib/python2.7/dist-packages (2020.1.1)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: spi-py from git+git://github.com/lthiery/SPI-Py.git#egg=spi-py in /usr/local/lib/python2.7/dist-packages (1.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyserial in /usr/lib/python2.7/dist-packages (3.4)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: spidev in /usr/lib/python2.7/dist-packages (3.3)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (0.7.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pi-rc522 in /usr/local/lib/python2.7/dist-packages (2.2.1)
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from pi-rc522) (0.7.0)
Requirement already satisfied: spidev in /usr/lib/python2.7/dist-packages (from pi-rc522) (3.3)
cp: cannot create regular file '/etc/samba/smb.conf': No such file or directory
chown: cannot access '/etc/samba/smb.conf': No such file or directory
chmod: cannot access '/etc/samba/smb.conf': No such file or directory
sed: can't read /etc/samba/smb.conf: No such file or directory
sudo: smbpasswd: command not found
cp: cannot create regular file '/etc/php/7.0/fpm/php.ini': No such file or directory
chown: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
chmod: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
sudo: lighttpd-enable-mod: command not found
sudo: lighttpd-enable-mod: command not found
Failed to restart lighttpd.service: Unit lighttpd.service not found.
Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.
### Deleting older versions of service daemons. This might throw errors, ignore them
Failed to disable unit: Unit file idle-watchdog.service does not exist.
Failed to disable unit: Unit file rfid-reader.service does not exist.
Failed to disable unit: Unit file startup-sound.service does not exist.
Failed to disable unit: Unit file gpio-buttons.service does not exist.
rm: cannot remove '/etc/systemd/system/rfid-reader.service': No such file or directory
rm: cannot remove '/etc/systemd/system/startup-sound.service': No such file or directory
rm: cannot remove '/etc/systemd/system/gpio-buttons.service': No such file or directory
rm: cannot remove '/etc/systemd/system/idle-watchdog.service': No such file or directory
### Done with erasing old daemons. Stop ignoring errors!
Created symlink /etc/systemd/system/multi-user.target.wants/phoniebox-idle-watchdog.service → /etc/systemd/system/phoniebox-idle-watchdog.service.
Created symlink /etc/systemd/system/multi-user.target.wants/phoniebox-rfid-reader.service → /etc/systemd/system/phoniebox-rfid-reader.service.
Created symlink /etc/systemd/system/multi-user.target.wants/phoniebox-startup-sound.service → /etc/systemd/system/phoniebox-startup-sound.service.
Created symlink /etc/systemd/system/multi-user.target.wants/phoniebox-gpio-buttons.service → /etc/systemd/system/phoniebox-gpio-buttons.service.
chown: invalid user: ‘mpd:audio’
./stretch-install-default.sh: line 533: mpc: command not found
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable dhcpcd
numid=1,iface=MIXER,name='PCM Playback Volume'
  ; type=INTEGER,access=rw---R--,values=1,min=-10239,max=400,step=0
  : values=400
  | dBscale-min=-102.39dB,step=0.01dB,mute=1

#
# INSTALLATION FINISHED
#
#####################################################

If you are using an USB RFID reader, connect it to your RPi.
(In case your RFID reader required soldering, consult the manual.)
Have you connected your USB Reader? [Y/n] y
Choose the reader from list
0 HXGCoLtd Keyboard
Device Number: 0

DONE. Let the sounds begin.
Find more information and documentation on the github account:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/

*** PHONIEBOX INFO
*** version: 2.0 rc7
*** edition: classic
*** Audio_iFace_Name: PCM
*** Audio_Folders_Path: /home/pi/RPi-Jukebox-RFID/shared/audiofolders
*** Audio_Volume_Change_Step: 3
*** Max_Volume_Limit: 100
*** Idle_Time_Before_Shutdown: 0
*** Second_Swipe: RESTART
*** Playlists_Folders_Path: /home/pi/RPi-Jukebox-RFID/playlists
*** ShowCover: ON
************************************
*** CONF FILES DEFAULT

*** /etc/samba/smb.conf
ls: cannot access '/etc/samba/smb.conf': No such file or directory
cat: /etc/samba/smb.conf: No such file or directory
*** /etc/lighttpd/lighttpd.conf
-rw-r--r-- 1 root root 1.1K Jan 12 21:48 /etc/lighttpd/lighttpd.conf
*** /etc/lighttpd/conf-available/15-fastcgi-php.conf
-rw-r--r-- 1 root root 398 Jan 12 21:48 /etc/lighttpd/conf-available/15-fastcgi-php.conf
*** /etc/php/7.0/fpm/php.ini
ls: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
*** /etc/sudoers
-r--r----- 1 root root 784 Jan 12 21:48 /etc/sudoers
*** /etc/systemd/system/phoniebox*
-rw-r--r-- 1 root root 296 Jan 12 21:48 /etc/systemd/system/phoniebox-rfid-reader.service
-rw-r--r-- 1 root root 285 Jan 12 21:48 /etc/systemd/system/phoniebox-startup-sound.service
-rw-r--r-- 1 root root 289 Jan 12 21:48 /etc/systemd/system/phoniebox-gpio-buttons.service
-rw-r--r-- 1 root root 291 Jan 12 21:48 /etc/systemd/system/phoniebox-idle-watchdog.service
*** /etc/mpd.conf
-rw-r----- 1 root root 14K Jan 12 21:48 /etc/mpd.conf
music_directory         "/home/pi/RPi-Jukebox-RFID/shared/audiofolders"
# music_directory are changed.
# symbolic links outside of the configured music_directory.
# symbolic links inside of the configured music_directory.
        mixer_control   "PCM"           # optional
#       mixer_control   "PCM"           # optional
*** /etc/dhcpcd.conf
-rw-rw-r-- 1 root netdev 1.8K Jan 24  2019 /etc/dhcpcd.conf
#static ip_address=192.168.0.10/24
#static ip_address=192.168.1.23/24
#static routers=192.168.0.1
#static routers=192.168.1.1
option domain_name_servers, domain_name, domain_search, host_name
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
#static domain_name_servers=192.168.1.1
*** /etc/wpa_supplicant/wpa_supplicant.conf
-rw------- 1 root root 72 Sep 26 01:12 /etc/wpa_supplicant/wpa_supplicant.conf
************************************
*** +Spotify Edition

*** /etc/locale.gen
-rw-r--r-- 1 root root 9.2K Sep 26 01:09 /etc/locale.gen
*** /etc/locale.gen
-rw-r--r-- 1 root root 9.2K Sep 26 01:09 /etc/locale.gen
*** /etc/mopidy/mopidy.conf
ls: cannot access '/etc/mopidy/mopidy.conf': No such file or directory
cat: /etc/mopidy/mopidy.conf: No such file or directory
*** ~/.config/mopidy/mopidy.conf
ls: cannot access '/home/pi/.config/mopidy/mopidy.conf': No such file or directory
cat: /home/pi/.config/mopidy/mopidy.conf: No such file or directory

vielen Dank
Ghostsl

**Comment by Ghostsl84** [comment]
Guten Abend,

ich habe es doch geschaft, mit einer alten Rasbian Stretch von dieser Seite die Phoniebox zum laufen zu bekommen.
Ich kann auch Karten registrieren und Musik hochladen, jedoch wird keine Karte abgespielt.
Kann mir da jemand weiterhelfen?

Vielen Dank
Ghostsl

**Comment by FloMrFrei** [comment]
Hi Ghostsl84

bei mir hat es letztlich mit einem Rapsi2 und Raspian Buster geklappt (Phoniebox-Spotify). Lösungen sind hier:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/700 
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/688 

In aller kürze:
1.) libspotify-dev installieren (sonst scheitert die Installation - egal ob Spotify oder nicht - wenn ich das Auto-Install-Script richtig verstehe)
```
wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list
sudo apt update
sudo apt-get install libspotify-dev
```

2.) One-Line-Installer (Buster)

3.) Mopidy downgrade
```
sudo apt-get install mopidy=2.3.1-1
sudo python2.7 -m pip install Mopidy==2.3.*
sudo pip install 'tornado==5.0'
```

Viel Erfolg!

**Comment by MiczFlor** [comment]
Hi @FloMrFrei 
kannst du eine Pull request mit deinen Änderungen zum Install script für Buster machen? Ich bin gerade "on the road" und habe keine Testumgebung (ein VirtualBox VM für Raspbian wäre cool...).

@Ghostsl84 
Ich hatte das manchmal: wenn man mit Kabel verbunden ist, läuft apt-get nicht. Ich habe das nicht weiter verfolgt. WiFi ging immer. Ich hatte das Gefühl das ist ein Raspbian Problem.
Bei deiner Stretch Installation: geht di Web app?

**Comment by Ghostsl84** [comment]
Guten Abend,

sorry das es so lange gedauert hat, war viel unterwegs.
Ja die Web App funktioniert, ich kann auch Daten Hochladen und die Karte einem Album zuweisen, aber sobald ich die Karte über den RFID Scanner ziehe pipst es, aber der Player startet nicht.
Ich kann das Album auch nicht über die Web App manuell starten.
Früher musste man die Bibliotheke aktualisieren, aber diesen Button finde ich nicht.

Gruß
Ghostsl

**Comment by splitti** [comment]
Bei dir gibt es Python Probleme. Der neue Installer muss einmal von Micz freigegeben werden, dann wird alles funktionieren.
Ich vermute du hast dir Classic Version? Dort gibt es keinen Folder Scan.

**Comment by Ghostsl84** [comment]
Guten Morgen,

genau das Fehlt.
Aber mit der Buster Installation wie SIe von FloMrFrei beschrieben wurde klappt alles super.
Mal noch eine frage, auch bei dieser Installation bekomme ich meinen Bluetooth Lautsprecher nicht in die gänge.
Der Lautsprecher wurde wie immer gepairt, connect und trust alles klappt wunderbar also die Verbindung zwischen Raspberry und meinem Lautsprecher.
Aber er spielt mir auch auf dieser Box keinen Sound.
Habe auch alles mit Bluealsa probiert ohne erfolg, es kommt kein Ton aus dem Lautsprecher.

habe diese Aleitung befolgt und damals schon alles probiert aber ohne erfolg:

https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/284

wenn ich diesen Befehl nutze:
aplay -D btspeaker /usr/share/sounds/alsa/Front_Center.wav

erhalte ich folgenden Fehler:
ALSA lib conf.c:1891:(_snd_config_load_with_include) :25:1:Unexpected }
ALSA lib conf.c:3650:(config_file_open) /etc/asound.conf may be old or corrupted: consider to remove or fix it
ALSA lib conf.c:3572:(snd_config_hooks_call) function snd_config_hook_load returned error: Invalid argument
ALSA lib conf.c:4026:(snd_config_update_r) hooks failed, removing configuration
aplay: main:828: audio open error: Invalid argument

vielleicht habt ihr eine Lösung dafür.

Vielen Dank
Ghostsl

**Comment by MiczFlor** [comment]
Hi @Ghostsl84 
probier noch mal einen neuen Install. @splitti hat sich die letzte Nacht um die Ohren geschlagen, um das hinzubekommen. Bei ihm läuft's. Ich habe es committed, aber noch nicht getestet.

**Comment by Ghostsl84** [comment]
Hi,

vielen Dank, hab es ausporbiert und läuft.
Aber jetzt hat man bei Verbinden eins Bluetooth Lautsprechers folgendes:

[bluetooth]# pair F4:4E:FD:AB:0C:35
Attempting to pair with F4:4E:FD:AB:0C:35
[CHG] Device F4:4E:FD:AB:0C:35 Connected: yes
Request confirmation
[agent] Confirm passkey 271642 (yes/no): yes
[CHG] Device F4:4E:FD:AB:0C:35 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device F4:4E:FD:AB:0C:35 UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device F4:4E:FD:AB:0C:35 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device F4:4E:FD:AB:0C:35 UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device F4:4E:FD:AB:0C:35 ServicesResolved: yes
[CHG] Device F4:4E:FD:AB:0C:35 Paired: yes
Pairing successful
[CHG] Device F4:4E:FD:AB:0C:35 ServicesResolved: no
[CHG] Device F4:4E:FD:AB:0C:35 Connected: no
[bluetooth]# trust F4:4E:FD:AB:0C:35
[CHG] Device F4:4E:FD:AB:0C:35 Trusted: yes
Changing F4:4E:FD:AB:0C:35 trust succeeded
[bluetooth]# connect F4:4E:FD:AB:0C:35
Attempting to connect to F4:4E:FD:AB:0C:35
Failed to connect: org.bluez.Error.Failed
[bluetooth]# connect F4:4E:FD:AB:0C:35
Attempting to connect to F4:4E:FD:AB:0C:35
Failed to connect: org.bluez.Error.Failed

über Kabel klappt aber alles wunderbar


Muss ich jetzt etwas umstellen?
Und wie Kann man eine Titel weiterkarte erstellen

Sorry fragen über fragen, aber ich verstehe das nicht so richtig.

Vielen Dank

**Comment by ZyanKLee** [comment]
hallo @Ghostsl84 in deinem ersten Beitrag wegen den Bluetooth-Lautsprechern hast du die Ausgabe von aplay zitiert. Darin erscheint folgende Meldung: '/etc/asound.conf may be old or corrupted: consider to remove or fix it'
Was steht denn in dieser Datei?

**Comment by Ghostsl84** [comment]
HI

in der Datei steht folgendes:


pcm.btspeaker {

type plug

slave.pcm {

    type bluealsa

    interface "hci0"

    device "F4:4E:FD:AB:0C:35"

    profile "a2dp"

    delay -20000

}

hint {

    show on

    description "SoundCore mini"

}

}

**Comment by MiczFlor** [comment]
Hi @Ghostsl84 
kannst du ein neues Ticket aufmachen und das hier schließen? Am besten mit `Bluetooth` im Titel, damit sich vielleicht andere mit einklinken können, die damit Erfahrung haben.
Danke, micz

**Comment by Ghostsl84** [comment]
Mache ich 

Danke für die Hilfe
