### ISSUE TITLE
Web App not running?

### ISSUE THREAD

**Issue by Erechtheus** [MiczFlor/RPi-Jukebox-RFID#734]
Hey folks! I successfully installed this project (no error messages). However, I am unable to access the web-app through my browser. Neither directly on the raspberry-pi nor on my laptop in the same network. Am I missing any step in the set-up? Any idea how to check if the web-service is running? Or to run the web-service manually?

**Comment by splitti** [comment]
`sudo service lighttpd status`

**Comment by Erechtheus** [comment]
Thanks! This command returns:
`sudo service lighttpd status`
`Unit lighttpd.service could not be found.`

Any idea on how to proceed? Can I manually start the web-service somehow? The logs folder is empty and all other services seem to be running

**Comment by splitti** [comment]
That ist the Problem, try a reinstall...

**Comment by stefantruehl** [comment]
hi there, I had the same issue yesterday when I was installing master branch on my brand new RPi4 + latest buster image; webserver didn't start and I hat no time to investigate. today I tried the one line installer for the dev-branch and it worked. I still seem to have one issue the rfid-reader not sending the red code to the application but at least the webserver is now configured correctly and running. I will investigate further. 
Hope this helps

**Comment by maxpousre** [comment]
I have had problems loading the webapp as well in the past 24 hours. Although the lighttpd.service is active and running. Any other services that I could check?

**Comment by MiczFlor** [comment]
@maxpousre 
does it work on the Pi itself, if you open a browser and type `localhost`?

**Comment by maxpousre** [comment]
I am running headless on a raspberry pi zero. Do you recommend installing a desktop to verify?

**Comment by splitti** [comment]
Try
`wgt URL`

**Comment by maxpousre** [comment]
500 response when connecting to the the phoniebox ip address
`HTTP request sent, awaiting response... 500 Internal Server Error
2020-01-19 18:18:36 ERROR 500: Internal Server Error.`

**Comment by splitti** [comment]
First: Installation with or without Spotify?

**Comment by maxpousre** [comment]
without

**Comment by splitti** [comment]
Damn, i have an Idea why. Need more SD cards for Testing. Micz, i will make tomorrow evening a new Pull Request.

**Comment by Erechtheus** [comment]
Okay, I just reinstalled the software and it runs now. The only thing I changed was installing the following packages:
`sudo apt-get install at lighttpd`
but actually I don't believe that this solved the issue :)
