### ISSUE TITLE
Repo Config Change Request

### ISSUE THREAD

**Issue by ZyanKLee** [MiczFlor/RPi-Jukebox-RFID#740]
Hey @MiczFlor , hey contributors,

I would like to ask you, Micz, to change the default branch from "master" to "develop".

> The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.

`master` branch in context of this project seems to me to be (at least to me) more of a "stable" or "v1" kind of branch which only gets minimal maintenance.

**Comment by MiczFlor** [comment]
Good point. And: done :)
