### ISSUE TITLE
Python version mismatch between RegisterDevice.py and Reader.py

### ISSUE THREAD

**Issue by Erechtheus** [MiczFlor/RPi-Jukebox-RFID#743]
Hey folks! I installed yesterday a new copy of the project on my raspberry and when I execute [RegisterDevice.py](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/RegisterDevice.py) I get an error in [Reader.py](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/Reader.py). The problem seems to be that RegisterDevice enforces python3 but Reader.py is only python2 compatible. Same holds for the alternative [experimental Reader](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/scripts/Reader.py.experimental). I am new to the project so I am not sure how to fix this in the repo. On my copy I simply changed the version back to python2....

**Comment by s-martin** [comment]
This is currently being fixed and tested in develop branch. Should be merged to master soon.
