### ISSUE TITLE
Question for my understanding: mopidy vs mpd

### ISSUE THREAD

**Issue by ZyanKLee** [MiczFlor/RPi-Jukebox-RFID#745]
I'm just at the task of cleaning up the mopidy3 install script and stumbled upon the following questions as I'm not that deep into the whole mpd-matter:

mpd and mopidy (with mopidy-mpd) are both effectively mp daemons, right?
They both support the same protocol and clients for controlling?
mopidy has just been chosen because it implements spotify, but mpd does not?

is there a reason not to switch completely to mopidy3 even when spotify is not going to be installed?

**Comment by MiczFlor** [comment]
Hi @ZyanKLee 
good point. And I don't have the answer. For local files with the `mpd` solution, new files will automatically  be indexed. To this day, I don't have a Spotify integration myself, so I am not sure how `mopidy` does it.
In the Spotify FAQ, this might give you a pointer to potential issues?
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Spotify-FAQ
MP3 (local music) handling has completely changed for the +Spotify Edition. The tracks need to be indexed by Mopidy & Mopidy-Spotify (this is the part of Phoniebox, which gives you spotify support) and the created M3U files do have another structure than normal M3U files.
You have to scan you library once (if you hadn't yet) and everytime you upload new local tracks to your Phoniebox.
You can scan local files under "Folders & Files" (Top Navigation).
For the future we try to integrate an automation for that.
