### ISSUE TITLE
services not in use

### ISSUE THREAD

**Issue by domu83** [MiczFlor/RPi-Jukebox-RFID#752]
Hi,

in order to strip down my phoniebox and try to get it up faster I would like to remove unneeded parts of the installation/disable services to prevent from running.
Is there any suggestion, which services can be disabled without having any interruption to the Phoniebox?

thanks
Dominik

**Comment by s-martin** [comment]
@splitti made a blog post:
http://splittscheid.de/faqs-zu-meiner-phoniebox/#bootspeedup

**Comment by domu83** [comment]
top!! Thanks a lot @s-martin !! Maybe worth to put this into wiki?
