### ISSUE TITLE
:bug: [Webstreams not working]

### ISSUE THREAD

**Issue by Alwiz79** [MiczFlor/RPi-Jukebox-RFID#766]
After updating my Stretch installation to Buster and one-line-installing the latest phoniebox my before working webstreams are not working anymore.

When I ssh to the box and enter 
`mpg123 -@ http://stream.spreeradio.de/spree-80er/mp3-128/kontakt/play.m3u`
everything is working fine.

But it won't play using the web frontend or swipe cards.
Any idea?

**Comment by s-martin** [comment]
Maybe realated to #767

**Comment by s-martin** [comment]
@Alwiz79 did you check, if this is also fixed now?

**Comment by cedivan0718** [comment]
When im on the spotify website via phoniebox tab and try to manually add songs on to the queue instead of scan it says “mopidy:failed to add some tracks” don’t know if this could be what is wrong but yeah still only shows album cover when swiping the rfid

**Comment by kuesimon** [comment]
I'm a little bit unsure if my comment is really fittig to this bug as it'spotify related...

I installed both - buster non-spotify and buster+spotify on my box. As mentioned in #765 the non-spotify is working now after typing in sudo mpd.

For the spotify version there is still only the thumbnail of the playlist and no sound - even with the current master install script.

**Comment by s-martin** [comment]
Unfortunately Spotify version is broken right now as there are some package version issue.

**Comment by Alwiz79** [comment]
I just found out that linking the actual stream adress (ending with *.mp3) which is stored within the m3u rather then the m3u is working.
So for me, this issue is closed now.
