### ISSUE TITLE
:question: Rotary Knob turning direction

### ISSUE THREAD

**Issue by deheingit** [MiczFlor/RPi-Jukebox-RFID#776]
Hi all,

i installed the same rotatory knob as described here to adjust the volume
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Audio-RotaryKnobVolume

It works fine (THANKS) - but just one question. It is possible to change the direction as for me it's more intuitive to turn the volume by turning the now clockwise. Currently up is CCW ;)

Thanks you

**Comment by MiczFlor** [comment]
Have a look here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/267#issuecomment-469053025

**Comment by deheingit** [comment]
Perfect, thanks a lot!
