### ISSUE TITLE
Add info how to get logs from failing services

### ISSUE THREAD

**Issue by s-martin** [MiczFlor/RPi-Jukebox-RFID#780]
We should add some hints how users can obtain logging info, if a service does not work.

I.e. we should provide some details how to use `journalctl`, so more info about failing services can be provided in the bug reports.

Maybe we should  add the info to the bug report template.

Example #779.

**Comment by Groovylein** [comment]
We do have a script that collects information:
`/home/pi/RPi-Jukebox-RFID/scripts/helperscripts/Analytics_AfterInstallScript.sh`

Does it make sense to enhance this with some `journalctl` commands?

**Comment by s-martin** [comment]
Won’t fix
