### ISSUE TITLE
GPIO RFID READER

### ISSUE THREAD

**Issue by leinadk** [MiczFlor/RPi-Jukebox-RFID#794]
Since Im using raspberry pi 1 for this project (limited usb) and have to use 1 of the USB for wifi and second for external music card. Is there an option to use a GPIO RFID CARD READER?

Can You pls advise what to configure?

**Comment by s-martin** [comment]
I'm not sure, if a RPi 1 would work with Phoniebox.

Nevertheless there are howtos for GPIO readers in the wiki, e.g.

https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Wiring_for_RC522_card_reader
or
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/RFID-Reader-Special

**Comment by s-martin** [comment]
I’m closing this now, feel free to reopen, if the problem persists
