### ISSUE TITLE
Assign the .local Domain to Your Raspberry Pi

### ISSUE THREAD

**Issue by elalemanyo** [MiczFlor/RPi-Jukebox-RFID#8]
Hi,
I think that assigning the .local Domain to RPi-Jukebox would be something interesting to make easier to use it.
This is how I normally do it -> [Assign the .local Domain to Your Raspberry Pi](https://www.howtogeek.com/167190/how-and-why-to-assign-the-.local-domain-to-your-raspberry-pi/)

Great Project!

Thanks!

**Comment by MiczFlor** [comment]
@elalemanyo 

Nice idea. In practice, because you are mostly using the same machine when connecting to the web interface or samba, a bookmark does the trick :)

Alternatively, I would prefer to use the hosts file:
https://en.wikipedia.org/wiki/Hosts_(file)#File_content
