### ISSUE TITLE
Kein Neustart der Playlist bei aufliegendem RFID-Chip

### ISSUE THREAD

**Issue by davidfri** [MiczFlor/RPi-Jukebox-RFID#800]
## Feature Description
Kein Neustart der Playlist bei aufliegendem RFID-Chip
### What functionality would you like to see in your phoniebox?

Bei unserer Phoniebox werden die Chips aufgelegt. Aus einem mir noch nicht nachvollziehbaren Grund wird die ID nach "same_id_delay" erneut verarbeitet. Spricht etwas dagegen diesen Teil zu entfernen, sodass nur bei einem Chip-Wechsel die ID ausgewertet wird?

### How do you envision the feature to work from a users perspective?

Der Chip (oder die Figur) kann auf der Box stehen bleiben. ;)

### Further information that might help

[remove_same_id_delay.patch.zip](https://github.com/MiczFlor/RPi-Jukebox-RFID/files/4232308/remove_same_id_delay.patch.zip)

**Comment by MondMann2019** [comment]
Gibt’s dafür nicht den Punkt „nur Systembefehle mehrfach ausführen“ in den Einstellungen unter „  Erneute Aktivierung“?

**Comment by davidfri** [comment]
Mist.... Sorry, den Punkt habe ich echt nicht gesehen. Tut genau, was es soll ;)
