### ISSUE TITLE
🚀 | allow selection of hardware during install

### ISSUE THREAD

**Issue by ZyanKLee** [MiczFlor/RPi-Jukebox-RFID#837]
### What functionality would you like to see in your phoniebox?

As a parent I would like to select during installation which hardware (RFID reader, usb soundcard, buttons, rotary encoders, etc) I got and the installer should take care of only installing the necessary dependencies.

### How do you envision the feature to work from a users perspective?

I would like to select from some lists, which hardware I have (perhaps some can be even pre-selected when we discover them from lsusb for example). Dependencies should be separated into a `requirements.txt` file for each hardware. After the selection has been done and confirmed the installer would run the needed pip-install commands.

**Comment by s-martin** [comment]
I have a local branch where I started some installer using npyscreen.

I try to push something tonight.

**Comment by ZyanKLee** [comment]
no need to rush this
I would envision it at v3 earliest.

**Comment by s-martin** [comment]
This has been implemented at least for readers in 2.1, so I close this now.
