### ISSUE TITLE
🚀 | Skip the manual interaction during installation

### ISSUE THREAD

**Issue by Groovylein** [MiczFlor/RPi-Jukebox-RFID#858]
### What functionality would you like to see in your phoniebox?

As a phoniebox developer, I need a possibility to skip the manual interaction during installation, so that I can speed up my development and/or enable automated tests

### How do you envision the feature to work from a users perspective?

This feature will enable faster manual development of fixing bugs and new features. In the next step, this could help to enable automated installation tests for the projects

**Comment by ZyanKLee** [comment]
From my perspective this is directly related to #827
