### ISSUE TITLE
🚀 | Remove hardcoded folders and stuff for "pi"

### ISSUE THREAD

**Issue by Piehti** [MiczFlor/RPi-Jukebox-RFID#866]
### What functionality would you like to see in your phoniebox?

I'd like to get rid of the user PI. Unfortunatly, the oneclick-installer has the user(directories) of "PI" hardcoded at several parts of the script. If you change the user before installing, the installation will propably fail.

**Comment by ZyanKLee** [comment]
this is on the back of my mind for some weeks now, too.
I don't see this as a task for v2, though.
@MiczFlor @s-martin if you think otherwise just put it into the appropriate milestone and project

**Comment by s-martin** [comment]
I agree that’s something for 3.0

**Comment by jo-me** [comment]
Will this allow the script to work on other OS than raspbian?

I'm thinking about using DietPi as base (smaller and less actiity on SD card) but it has a different user and probably other packages installed.

**Comment by s-martin** [comment]
Phoniebox depends on packages like RPi.GPIO and others, so if these packages are available, it **could** work.

However, I'm not aware that anybody has run Phoniebox on another platform, so it definitely would be pioneer work.
