### ISSUE TITLE
Lastest "+Spotify" develop playback is too fast and shows last track info

### ISSUE THREAD

**Issue by BerniPi** [MiczFlor/RPi-Jukebox-RFID#877]
I tested with a Raspberrypi 3B with onboard sound (PCM). I installed Phoniebox with the Onelineinstall-Script (develop) with Spotify:
Local Playback is faster and higher than original.
The Songinfo in the Webinterface isn't updated to the newest song (one song behind).

**Comment by s-martin** [comment]
See #799

**Comment by BerniPi** [comment]
Thank you! But there is nothing mentioned about faster playback. It's not a bit faster. It's much faster, it's higher pitched.

**Comment by BerniPi** [comment]
For the time beeing, i don't have the "speed"-Problem anymore.
I close this issue.
