### ISSUE TITLE
🐛 | getVolume returns 0 at random

### ISSUE THREAD

**Issue by bionicTOADY** [MiczFlor/RPi-Jukebox-RFID#881]
When i increase or decrease the volume via webinterface OR gpio-wired button the getVolume fails and sets the return value somehow to 0.

debugging modded:
![2020-03-31 09_25_44-Phoniebox](https://user-images.githubusercontent.com/62931571/78004864-05746400-733b-11ea-8a3e-c0e79a8edbd4.png)

log:
![2020-03-31 10_12_28-Phoniebox](https://user-images.githubusercontent.com/62931571/78004256-25efee80-733a-11ea-925f-272b9e172e33.png)

The problem lies between the return value of 70something and 0.

Since I am not very skilled at python, shell-scripts etc. I hope I'll get some help here.

Software and Hardware:
Phoniebox-Version: 2.0 rc7
Raspi 4 2gb
Soundcard: Behringer U-Control UCA202 USB Audio Interface 2-in/2-out
no Spotify

Soundcontrol works from webapp and physical button the same way including the random bug.

Thanks for suggestions and help.

**Comment by bionicTOADY** [comment]
Hi there,
i reinastalled my box since my child's birthday is some days down the road...
I evaluated, that the error occures after I got the startupsound to work with the instructiond found here:
https://forum-raspberrypi.de/forum/thread/45333-phoniebox-kein-startup-sound-nach-update/

Now I can have a startup sound OR a working volume control =(. I have not found a solution which got both to work. I hope someone may help me.

**Comment by MiczFlor** [comment]
If you change the sound in the web app, does the volume change at all?
It might be the case that you have not added the soundcard to the conf file?
Please have a look here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Troubleshooting-FAQ#audio-is-not-working
under the second subheader: **b) Audio worked, then you changed the sound card and it stopped working**
This is for the bare bones Phoniebox classic without spotify. 
If you use the *+Spotify* edition, you might need to change the mopidy conf

**Comment by bionicTOADY** [comment]
The volume changes just as I want. The steps are the preset steps from the settings and everything works just finde apart from setting the volumelevel to 0. This happens randomly by changing the volumelevel. The source of the change is indifferent (web app or physical button).

**Comment by bionicTOADY** [comment]
Since the debugmessage:

`    getvolume)
        # read volume in percent
 if [ "${DEBUG_playout_controls_sh}" == "TRUE" ]; then echo "getVolumeMyDebug" >> $PATHDATA/../logs/debug.log; fi
`

does not return a printout when getVolume fails I think the method is not called correctly when this problem occures.
Quite difficult for me to see why this happens. Any sugestion?

**Comment by bionicTOADY** [comment]
```
            # $VOLFILE does NOT exist == audio on
            # read volume in percent
if [ "${DEBUG_playout_controls_sh}" == "TRUE" ]; then echo "volfile does not exist" >> $PATHDATA/../logs/debug.log; fi
            VOLPERCENT=$(echo -e status\\nclose | nc -w 1  localhost 6600 | grep -o -P '(?<=volume: ).*')
```

this line causes the trouble. But i have no clue how to fix it....

**Comment by s-martin** [comment]
@fredg02, people with bash skills needed here :)

**Comment by s-martin** [comment]
@bionicTOADY do you still have this issue?

**Comment by s-martin** [comment]
Can you check, if the issue still persists with current 2.4 version?

**Comment by s-martin** [comment]
Closing for now. Feel free to reopen this issue, if the problem persists
