### ISSUE TITLE
UI redesign settings page

### ISSUE THREAD

**Issue by MiczFlor** [MiczFlor/RPi-Jukebox-RFID#89]
I committed a couple of changes to the settings page with this commit:
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/19a1ffb3e81dee1bb132b7187c2a7253f8e94361
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/4f3e6536e3a5a8f9234ad3974d94b24227e62786
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/306f56521044be78704280d32421751362200c5b
for the new branch `pr80-mpd-as-audio-player`.

I wasn't too happy with the horizontal bars to show values and time, because they scaled poorly on mobile devices. Expecially the smaller values for *volume change step*  was squashed in the corner of a small blue bar :) 

They have now been replaced with circles which work well as a clock faces. 

It would be nice if somebody could check if they work correctly.

![settings-clock-face-redesign](https://user-images.githubusercontent.com/1876216/43014495-99752284-8c4c-11e8-97da-43339fb90565.png)

![settings-clock-face-phone](https://user-images.githubusercontent.com/1876216/43014566-e0bbf000-8c4c-11e8-9d1b-51f55e232744.png)

**Comment by zxa** [comment]
Works good for me, a great improvement for the web app! Looks also good on my Android device.

I've seen that you removed the possibility to set 0% as the max volume and 0% as volume step. These may be useless on the first sight, but may be useless under some circumstances. The latter offers the opportunity to keep the volume constant for button users for example to prevent unintentional muting and thus a call for the service person if kids are playing with the funny buttons (is used that ones).
The max 0% may be used to prevent unauthorized usage (let's call it like that) of the box. Maybe a new feature? "Mute the box between x pm and y am".
