### ISSUE TITLE
MFRC-522 RFID-Kit RC522

### ISSUE THREAD

**Issue by elalemanyo** [MiczFlor/RPi-Jukebox-RFID#9]
Hi,
Would be possible to use [MFRC-522 RFID-Kit RC522](https://www.ebay.de/itm/122468235090)?

Thanks!

**Comment by MiczFlor** [comment]
Hi @elalemanyo , I haven't worked with this one yet. My gut feeling tells me "no". I checked the documentation here:
https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf
and didn't find what I was looking for, which is: the USB RFID readers usually are set up in a way that they act "like a keyboard". The Chip ID is pushed to the RPi as if you were typing it in a keyboard and pressed "enter". This input is what the python daemon is waiting for and then it pipes the result into the bash script.
