### ISSUE TITLE
🐛 | RC522 Wiring Info for MISO and SCK mixed up

### ISSUE THREAD

**Issue by jo-me** [MiczFlor/RPi-Jukebox-RFID#905]
### What I did

I wired up a RC522 according to the wiki entry:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Hardware-Pinout-Overview#hardware-with-fixed-pin-assignment

### What happened

Result: the reader did not read any tags.

After triple checking the cables I found that the table in the wiki entry is wrong.

SCK and MISO are mixed up:

![image](https://user-images.githubusercontent.com/10351272/79478001-2ad7c200-800b-11ea-9dda-8665c0e70cc0.png)

After wiring it according to the pinout picture it works.

### I expected this to happen

Corrected documentation

### Further information that might help

Issue was mentioned here already: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/535

**Comment by s-martin** [comment]
I updated the wiki, please check and if it’s ok you can close the issue.

**Comment by jo-me** [comment]
Thanks!
