### ISSUE TITLE
🐛 | Skip Samba configuration dialog during installation by default?

### ISSUE THREAD

**Issue by fredg02** [MiczFlor/RPi-Jukebox-RFID#920]
### What I did
I used the install script (buster-install-default.sh) and wanted to run a non-interactive installation (see also issue #858).
### What happened
The following screen pops up during the installation:
![image](https://user-images.githubusercontent.com/605957/80144399-b672c500-85ae-11ea-9ef3-5fe773a495e5.png)
### I expected this to happen
After the initial set of questions during the installation, no further interaction should be required.
If the installation runs in automatic mode (upcoming PR), no interaction should be required at all.
### Further information that might help
debconf-set-selections can be used to skip this configuration dialog.
* `echo "samba-common samba-common/dhcp boolean false" | sudo debconf-set-selections` => same as if you would select "No" in the dialog. 
* `echo "samba-common samba-common/dhcp boolean true" | sudo debconf-set-selections` => same as if you would select "Yes" in the dialog. 

Here are my questions:
* Should this dialog be skipped by default for any type of installation (interactive and non-interactive)?
* Should this dialog only be skipped during a non-interactive installation?
* What should be the default answer? Yes or No?
(I don't think this dialog is even relevant for most users, but I might be wrong.)
### Base image and version
2020-02-13-raspbian-buster-lite.img
### Branch / Release
develop
### Installscript
scripts/installscripts/buster-install-default.sh
### RaspberryPi version, etc
does not matter

**Comment by s-martin** [comment]
From my point of view we could default this to "No" directly in the script, I personally don't see the use case for WINS.

We then should document this behavior somewhere.

**Comment by s-martin** [comment]
But I would like to check with @MiczFlor, if I'm missing a use case for WINS here.

**Comment by MiczFlor** [comment]
It's been added. Thanks for the hint:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/18de7c9be16a840afac4fc980a05cc550c5bb10f/scripts/installscripts/buster-install-default.sh#L1090
