### ISSUE TITLE
🐛 | Shutdownsound = Startupsound?

### ISSUE THREAD

**Issue by JuliH29** [MiczFlor/RPi-Jukebox-RFID#936]
Hi!

If I remember correctly the [shutdown sound](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/misc/sampleconfigs/shutdownsound.mp3.sample) used to be different from the [startup sound](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/misc/sampleconfigs/startupsound.mp3.sample). 
Now they seem to be the same file in all different branches. Is that intended?

Thanks,
Julius

**Comment by MiczFlor** [comment]
Hi @JuliH29 
Not sure if that ever was the case. In the master branch you can see the old shutdown sound:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/misc/sampleconfigs/shutdownsound.mp3.sample
And if you see the date there: it's from 2018 - and hasn't changed since.
