### ISSUE TITLE
🐛 | deavtivating repeat does not work

### ISSUE THREAD

**Issue by oswaldo-be** [MiczFlor/RPi-Jukebox-RFID#938]
### What I did

I tried to deactivate the "repeat" function which is always active, when I started to play anything.

### What happened

The button changes to "repeat-off", but when I reload the page it aint deactivated.

### I expected this to happen

I had hoped it stayed deactivated!

### Further information that might help

when I switch into terminal and do "mpc repeat 0". I can see it is deactivated and stayes this way!

### Base image and version

2.0 rc7
EditionClassic edition (barebones)

### RaspberryPi version

 `3 B+`

### RFID Reader

 `16c0:27db HXGCoLtd Keyboard`

not relevant...
### Soundcard

hifiberryMiniAmp

Can be found in the output of `sudo lsusb -v` when it is connected via USB.

### Other notable hardware

pimoroni on-off-shim

Or maybe I set something wrong?
In that way can anybody help me please?
Thank you very much in advance!

**Comment by oswaldo-be** [comment]
hmm now that I deactivated it one time per mpc repeat 0 I can activate and deactivate it in the GUI again and it works...

**Comment by Piehti** [comment]
So this issue is closed?
I would have suggested to check the rights on the *.conf *.scripts as to restart the mpd service by chattering down a: sudo service mpd restart. Non persistent problems seem to vanish a lot by mpd restart.

**Comment by oswaldo-be** [comment]
It can be closed. Thank you

Piehti <notifications@github.com> schrieb am So., 10. Mai 2020, 18:48:
