### ISSUE TITLE
🐛 | web app player: repeat playlist / track / off not working properly

### ISSUE THREAD

**Issue by MiczFlor** [MiczFlor/RPi-Jukebox-RFID#944]
## Bug

WEB UI: There are three options for repeat in the web ui player: OFF, PLAYLIST (repeat playlist), TRACK (repeat track). The player ajax will only display either OFF or TRACK.
If TRACK is shown, it will behave like PLAYLIST

### I expected this to happen

Show the correct state and act accordingly

### Further information that might help

The javascript listener needs to consider the mpd state of `repeat` and `single`

Explained:

The loop status requires to check the status track or playlist:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/31a0004e170cc4a84aafc1188d32575ef502d1a8/scripts/playout_controls.sh#L439
~~~
single)
        mpc repeat on
        mpc single on
        ;;
playlist)
        mpc repeat on
        mpc single off
~~~
In the ajax only both are checked:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/31a0004e170cc4a84aafc1188d32575ef502d1a8/htdocs/inc.playerStatus.php#L16
~~~
// Playlist repeat
preg_match('/\nrepeat: (.*)\n/', $status, $output);
$playerStatus['repeat'] = $output[1];
// Single repeat
preg_match('/\nsingle: (.*)\n/', $status, $output);
$playerStatus['single'] = $output[1];
~~~

## Software

Develop branch 20200512
Version (git pull overwrote the version number):
https://github.com/MiczFlor/RPi-Jukebox-RFID/commit/31a0004e170cc4a84aafc1188d32575ef502d1a8

### Base image and version
Buster

### RaspberryPi version

`3 B+`

**Comment by s-martin** [comment]
We had a similar issue recently... 🤔
