### ISSUE TITLE
Call rfid_trigger_play instead of mpc directly

### ISSUE THREAD

**Issue by Luegengladiator** [MiczFlor/RPi-Jukebox-RFID#95]
playerstop:
        $PATHDATA/resume_play.sh -c=savepos && mpc stop
    playerstopafter:
        echo "mpc stop" | at -q s now + $VALUE minute

both call a mpc stop to reduce the direct mpc calls and reduce redundancies playstopafter should look like: 
echo "$PATHDATA/playout_controls.sh -c=playerstop" | at -q s now + $VALUE minute

**Comment by MiczFlor** [comment]
Did you change this in your pull request?

**Comment by Luegengladiator** [comment]
No I didn't. 
I saw this during adding subdirectory support

**Comment by zxa** [comment]
I haven't understood the playstopafter feature yet. What is a use case? Thatswhy i haven't supported it in the web app and made only a sloppy adaption for mpd.

**Comment by Luegengladiator** [comment]
I think the "playstopafter" is needed for the timer feature. 
I didn't check all mpc calls. But I think it's useful to minimize the direct mpc-calls.
If there is a change on the control it's not easy to fix if there are same calls all over the place.

If I understand the example right, the timebased stop will not update the savepos. So your resume_play is the perfect example for this issue.
