### ISSUE TITLE
🐛 | No titles on WebUI when adding spotify playlist

### ISSUE THREAD

**Issue by Groovylein** [MiczFlor/RPi-Jukebox-RFID#975]
### What I did

I added a Spotify playlist via the WebUI and connected it to an RFID card

### What happened

The playlist does not have any title

![Screenshot_20200523-170157](https://user-images.githubusercontent.com/29941729/82733969-efba6400-9d17-11ea-9516-1ac2ad708d6d.png)

**Comment by BerniPi** [comment]
See here: #799

**Comment by Groovylein** [comment]
I installed from latest develop branch.

**Comment by MiczFlor** [comment]
There were two commits that might cause this behaviour. I have no spotify running, who could find the bug?
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/884
by @lovethisshit 
and
https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/953
by @danielhammer

**Comment by danielhammer** [comment]
Just checked out latest develop branch, added several public and private playlist and do not face the issue yet. I will try reinstalling from scratch. Maybe some issue with directory permissions comes up on fresh installs? Let's see...

**Comment by danielhammer** [comment]
I deleted the previously installed folder of RPi-Jukebox-RFID and reinstalled by using the one-line-script as described here [https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/INSTALL-stretch#b-developer-install-script-for-buster](url) and the playlists titles are coming up as expected.

**Comment by danielhammer** [comment]
**Lastly I tested:**

- completely fresh Raspian buster image (raspbian buster lite)
- fresh RPi-Jukebox-RFID installation via [one-line-install-script for developers](https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/INSTALL-stretch#b-developer-install-script-for-buster)
- added several private and public Spotify playlists by URI (format `spotify:playlist:37i9dQZF1DX2TRYkJECvfC`) via "Add new Card" web form.

**Result:**

- Playlist titles and covers get loaded and shown in web UI correctly (Firefox, Safari, Chrome) ✔️
- tested the same for single songs, just to be shore, works fine ✔️


@Groovylein could it be possible, that you are working on a slightly older version of the develop branch? The behaviour you describe in your bug report, is similar to what I observed before integrating my patch that was finally merged in #953 .

**Comment by Groovylein** [comment]
Ok thank you for testing @danielhammer .
I will have a look later on which commit I am and compare it.

**Comment by Groovylein** [comment]
My mistake I was on an older commit.
