### ISSUE TITLE
One line install script doesnt seem to work anymore

### ISSUE THREAD

**Issue by deformatik-debug** [MiczFlor/RPi-Jukebox-RFID#986]
### Sevreal "Fehlschlag beim holen von xxx" notices during the installation, eventhough internet connection is workking. Have tried the installation 10 times, always with the same result.

![CLI_output_during installation](https://user-images.githubusercontent.com/65418215/83247616-0d6a4c00-a1a4-11ea-82db-034704fe3dc3.JPG)

**Comment by s-martin** [comment]
Please execute `sudo apt update` before starting the install script. I assume the apt mirrors are not up to date.

**Comment by deformatik-debug** [comment]
That was the solution. It's weird, I could have sworn that I did sudo apt update as well as sudo apt upgrade when I first set up the pi two days ago. However, thank you for the quick response.
