### ISSUE TITLE
🚀 | Integrate GPIO Control correctly

### ISSUE THREAD

**Issue by s-martin** [MiczFlor/RPi-Jukebox-RFID#991]
Since 2.0 we have added [GPIO Controls](https://github.com/MiczFlor/RPi-Jukebox-RFID/tree/Master/components/gpio_control), many thanks to @veloxidSchweiz.

At the moment it’s not installed yet in the default installation, but is required at least for rotary encoder.

- [ ] Integrate install.sh in regular installation script 
- [ ] Deactivate outdated gpio-buttons and rotary-encoder services and remove old code
- [ ] Update documentation in wiki and `/components/gpio_control`
- [ ] fix also „keep gpio settings“ in the installer script

Information can be found in #900, PR #990 could probably be closed.

My current assumptions are noted here: https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/990#issuecomment-636522290

Integration steps are described here: https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/973#issuecomment-638653806 (to be verified)

**Comment by jlarsch** [comment]
given the GPIO issues with 2.0, is there a one line install routine to roll back and re-install the previous version? Unfortunately, my backup broke

**Comment by arne123** [comment]
just short comment to the wiki page and future documentation https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Audio-RotaryKnobVolume
To reverse the rotation direction of an Rotary Enocder, you just need to Swap the A a B Pins in a Config File

**Comment by themorlan** [comment]
@s-martin 
>     * [ ]  Integrate install.sh in regular installation script

How should this be implemented? As an interactive section in the script, which contains parts of the [https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/develop/components/gpio_control/install.sh](url)?

**Comment by s-martin** [comment]
@themorlan, yes that would be my approach. Similar to the selection of RFID readers already in the script.

**Comment by themorlan** [comment]
Whats the current status? Any work already done? 
I'm a novice in shell scripting but I might try to implement it.

**Comment by s-martin** [comment]
Not really something done, `develop` branch contains everything implemented so far.
