### ISSUE TITLE
🐛 | WEB-Ui Volume control failing since new version

### ISSUE THREAD

**Issue by Piehti** [MiczFlor/RPi-Jukebox-RFID#999]
### What I did

Volume up + down not working + SET volume neighter. Actually no interacting with volume on the webinterface works. Didnt test RFiD-card-changes on volume yet. Might (pretty sure) it's the same error as #973

### What happened

After installing the new version on a (almost) clean Pi3b+ the Sound-Control stopped working. Might have to do with that "audiojack" thingy going on and that MIGHT have to do with rpi-update? Dunno.

**Comment by s-martin** [comment]
I think that’s the same issue than #973, because the web interface uses the same underlying mechanism.

**Comment by Piehti** [comment]
*nods*

**Comment by s-martin** [comment]
Closing as duplicate, please follow up in #973
